// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldAdmin holds the string denoting the admin field in the database.
	FieldAdmin = "admin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldTotalReports holds the string denoting the total_reports field in the database.
	FieldTotalReports = "total_reports"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeLocationReports holds the string denoting the location_reports edge name in mutations.
	EdgeLocationReports = "location_reports"
	// EdgeBloodDeityReports holds the string denoting the blood_deity_reports edge name in mutations.
	EdgeBloodDeityReports = "blood_deity_reports"
	// EdgeRichVampireReports holds the string denoting the rich_vampire_reports edge name in mutations.
	EdgeRichVampireReports = "rich_vampire_reports"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "password_tokens"
	// OwnerInverseTable is the table name for the PasswordToken entity.
	// It exists in this package in order to avoid circular dependency with the "passwordtoken" package.
	OwnerInverseTable = "password_tokens"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
	// LocationReportsTable is the table that holds the location_reports relation/edge.
	LocationReportsTable = "location_reports"
	// LocationReportsInverseTable is the table name for the LocationReport entity.
	// It exists in this package in order to avoid circular dependency with the "locationreport" package.
	LocationReportsInverseTable = "location_reports"
	// LocationReportsColumn is the table column denoting the location_reports relation/edge.
	LocationReportsColumn = "reporter_id"
	// BloodDeityReportsTable is the table that holds the blood_deity_reports relation/edge.
	BloodDeityReportsTable = "blood_deities"
	// BloodDeityReportsInverseTable is the table name for the BloodDeity entity.
	// It exists in this package in order to avoid circular dependency with the "blooddeity" package.
	BloodDeityReportsInverseTable = "blood_deities"
	// BloodDeityReportsColumn is the table column denoting the blood_deity_reports relation/edge.
	BloodDeityReportsColumn = "reporter_id"
	// RichVampireReportsTable is the table that holds the rich_vampire_reports relation/edge.
	RichVampireReportsTable = "rich_vampires"
	// RichVampireReportsInverseTable is the table name for the RichVampire entity.
	// It exists in this package in order to avoid circular dependency with the "richvampire" package.
	RichVampireReportsInverseTable = "rich_vampires"
	// RichVampireReportsColumn is the table column denoting the rich_vampire_reports relation/edge.
	RichVampireReportsColumn = "reporter_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
	FieldVerified,
	FieldAdmin,
	FieldCreatedAt,
	FieldTotalReports,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/mikestefanello/pagoda/ent/runtime"
var (
	Hooks [1]ent.Hook
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultAdmin holds the default value on creation for the "admin" field.
	DefaultAdmin bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultTotalReports holds the default value on creation for the "total_reports" field.
	DefaultTotalReports int
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByAdmin orders the results by the admin field.
func ByAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdmin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTotalReports orders the results by the total_reports field.
func ByTotalReports(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReports, opts...).ToFunc()
}

// ByOwnerCount orders the results by owner count.
func ByOwnerCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnerStep(), opts...)
	}
}

// ByOwner orders the results by owner terms.
func ByOwner(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLocationReportsCount orders the results by location_reports count.
func ByLocationReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLocationReportsStep(), opts...)
	}
}

// ByLocationReports orders the results by location_reports terms.
func ByLocationReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLocationReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBloodDeityReportsCount orders the results by blood_deity_reports count.
func ByBloodDeityReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBloodDeityReportsStep(), opts...)
	}
}

// ByBloodDeityReports orders the results by blood_deity_reports terms.
func ByBloodDeityReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBloodDeityReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRichVampireReportsCount orders the results by rich_vampire_reports count.
func ByRichVampireReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRichVampireReportsStep(), opts...)
	}
}

// ByRichVampireReports orders the results by rich_vampire_reports terms.
func ByRichVampireReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRichVampireReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, OwnerTable, OwnerColumn),
	)
}
func newLocationReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LocationReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, LocationReportsTable, LocationReportsColumn),
	)
}
func newBloodDeityReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BloodDeityReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, BloodDeityReportsTable, BloodDeityReportsColumn),
	)
}
func newRichVampireReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RichVampireReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RichVampireReportsTable, RichVampireReportsColumn),
	)
}
