// Code generated by ent, DO NOT EDIT.
package admin

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/labstack/echo/v4"

	"github.com/mikestefanello/pagoda/ent"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

const dateTimeFormat = "2006-01-02T15:04:05"
const dateTimeFormatNoSeconds = "2006-01-02T15:04"

type Handler struct {
	client *ent.Client
	Config HandlerConfig
}

func NewHandler(client *ent.Client, cfg HandlerConfig) *Handler {
	return &Handler{
		client: client,
		Config: cfg,
	}
}

func (h *Handler) Create(ctx echo.Context, entityType string) error {
	switch entityType {
	case "BloodDeity":
		return h.BloodDeityCreate(ctx)
	case "LocationReport":
		return h.LocationReportCreate(ctx)
	case "PasswordToken":
		return h.PasswordTokenCreate(ctx)
	case "RichVampire":
		return h.RichVampireCreate(ctx)
	case "User":
		return h.UserCreate(ctx)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Get(ctx echo.Context, entityType string, id int) (url.Values, error) {
	switch entityType {
	case "BloodDeity":
		return h.BloodDeityGet(ctx, id)
	case "LocationReport":
		return h.LocationReportGet(ctx, id)
	case "PasswordToken":
		return h.PasswordTokenGet(ctx, id)
	case "RichVampire":
		return h.RichVampireGet(ctx, id)
	case "User":
		return h.UserGet(ctx, id)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Delete(ctx echo.Context, entityType string, id int) error {
	switch entityType {
	case "BloodDeity":
		return h.BloodDeityDelete(ctx, id)
	case "LocationReport":
		return h.LocationReportDelete(ctx, id)
	case "PasswordToken":
		return h.PasswordTokenDelete(ctx, id)
	case "RichVampire":
		return h.RichVampireDelete(ctx, id)
	case "User":
		return h.UserDelete(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Update(ctx echo.Context, entityType string, id int) error {
	switch entityType {
	case "BloodDeity":
		return h.BloodDeityUpdate(ctx, id)
	case "LocationReport":
		return h.LocationReportUpdate(ctx, id)
	case "PasswordToken":
		return h.PasswordTokenUpdate(ctx, id)
	case "RichVampire":
		return h.RichVampireUpdate(ctx, id)
	case "User":
		return h.UserUpdate(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) List(ctx echo.Context, entityType string) (*EntityList, error) {
	switch entityType {
	case "BloodDeity":
		return h.BloodDeityList(ctx)
	case "LocationReport":
		return h.LocationReportList(ctx)
	case "PasswordToken":
		return h.PasswordTokenList(ctx)
	case "RichVampire":
		return h.RichVampireList(ctx)
	case "User":
		return h.UserList(ctx)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) BloodDeityCreate(ctx echo.Context) error {
	var payload BloodDeity
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.BloodDeity.Create()
	op.SetVampireName(payload.VampireName)
	if payload.BloodAmount != nil {
		op.SetBloodAmount(*payload.BloodAmount)
	}
	if payload.LastUpdated != nil {
		op.SetLastUpdated(*payload.LastUpdated)
	}
	if payload.ReporterUsername != nil {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID != nil {
		op.SetReporterID(*payload.ReporterID)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) BloodDeityUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.BloodDeity.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload BloodDeity
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetVampireName(payload.VampireName)
	if payload.BloodAmount == nil {
		var empty int64
		op.SetBloodAmount(empty)
	} else {
		op.SetBloodAmount(*payload.BloodAmount)
	}
	if payload.LastUpdated == nil {
		var empty time.Time
		op.SetLastUpdated(empty)
	} else {
		op.SetLastUpdated(*payload.LastUpdated)
	}
	if payload.ReporterUsername == nil {
		op.ClearReporterUsername()
	} else {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID == nil {
		op.ClearReporterID()
	} else {
		op.SetReporterID(*payload.ReporterID)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) BloodDeityDelete(ctx echo.Context, id int) error {
	return h.client.BloodDeity.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) BloodDeityList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.BloodDeity.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(blooddeity.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Vampire name",
			"Blood amount",
			"Last updated",
			"Reporter username",
			"Reporter ID",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].VampireName,
				fmt.Sprint(res[i].BloodAmount),
				res[i].LastUpdated.Format(h.Config.TimeFormat),
				res[i].ReporterUsername,
				fmt.Sprint(res[i].ReporterID),
			},
		})
	}

	return list, err
}

func (h *Handler) BloodDeityGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.BloodDeity.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("vampire_name", entity.VampireName)
	v.Set("blood_amount", fmt.Sprint(entity.BloodAmount))
	v.Set("last_updated", entity.LastUpdated.Format(dateTimeFormat))
	v.Set("reporter_username", entity.ReporterUsername)
	v.Set("reporter_id", fmt.Sprint(entity.ReporterID))
	return v, err
}

func (h *Handler) LocationReportCreate(ctx echo.Context) error {
	var payload LocationReport
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.LocationReport.Create()
	op.SetBuildingName(payload.BuildingName)
	op.SetBuildingType(payload.BuildingType)
	if payload.CustomItemName != nil {
		op.SetCustomItemName(*payload.CustomItemName)
	}
	if payload.CoordinateX != nil {
		op.SetCoordinateX(*payload.CoordinateX)
	}
	if payload.CoordinateY != nil {
		op.SetCoordinateY(*payload.CoordinateY)
	}
	if payload.StreetName != nil {
		op.SetStreetName(*payload.StreetName)
	}
	if payload.StreetNumber != nil {
		op.SetStreetNumber(*payload.StreetNumber)
	}
	if payload.GuildLevel != nil {
		op.SetGuildLevel(*payload.GuildLevel)
	}
	if payload.ReporterUsername != nil {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID != nil {
		op.SetReporterID(*payload.ReporterID)
	}
	if payload.Confidence != nil {
		op.SetConfidence(*payload.Confidence)
	}
	if payload.Notes != nil {
		op.SetNotes(*payload.Notes)
	}
	if payload.ReportedAt != nil {
		op.SetReportedAt(*payload.ReportedAt)
	}
	if payload.ExpiresAt != nil {
		op.SetExpiresAt(*payload.ExpiresAt)
	}
	op.SetIsActive(payload.IsActive)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) LocationReportUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.LocationReport.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload LocationReport
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetBuildingName(payload.BuildingName)
	op.SetBuildingType(payload.BuildingType)
	if payload.CustomItemName == nil {
		op.ClearCustomItemName()
	} else {
		op.SetCustomItemName(*payload.CustomItemName)
	}
	if payload.CoordinateX == nil {
		op.ClearCoordinateX()
	} else {
		op.SetCoordinateX(*payload.CoordinateX)
	}
	if payload.CoordinateY == nil {
		op.ClearCoordinateY()
	} else {
		op.SetCoordinateY(*payload.CoordinateY)
	}
	if payload.StreetName == nil {
		op.ClearStreetName()
	} else {
		op.SetStreetName(*payload.StreetName)
	}
	if payload.StreetNumber == nil {
		op.ClearStreetNumber()
	} else {
		op.SetStreetNumber(*payload.StreetNumber)
	}
	if payload.GuildLevel == nil {
		op.ClearGuildLevel()
	} else {
		op.SetGuildLevel(*payload.GuildLevel)
	}
	if payload.ReporterUsername == nil {
		op.ClearReporterUsername()
	} else {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID == nil {
		op.ClearReporterID()
	} else {
		op.SetReporterID(*payload.ReporterID)
	}
	if payload.Confidence == nil {
		var empty locationreport.Confidence
		op.SetConfidence(empty)
	} else {
		op.SetConfidence(*payload.Confidence)
	}
	if payload.Notes == nil {
		op.ClearNotes()
	} else {
		op.SetNotes(*payload.Notes)
	}
	if payload.ExpiresAt == nil {
		op.ClearExpiresAt()
	} else {
		op.SetExpiresAt(*payload.ExpiresAt)
	}
	op.SetIsActive(payload.IsActive)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) LocationReportDelete(ctx echo.Context, id int) error {
	return h.client.LocationReport.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) LocationReportList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.LocationReport.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(locationreport.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Building name",
			"Building type",
			"Custom item name",
			"Coordinate x",
			"Coordinate y",
			"Street name",
			"Street number",
			"Guild level",
			"Reporter username",
			"Reporter ID",
			"Confidence",
			"Notes",
			"Reported at",
			"Expires at",
			"Is active",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].BuildingName,
				fmt.Sprint(res[i].BuildingType),
				res[i].CustomItemName,
				fmt.Sprint(res[i].CoordinateX),
				fmt.Sprint(res[i].CoordinateY),
				res[i].StreetName,
				res[i].StreetNumber,
				fmt.Sprint(res[i].GuildLevel),
				res[i].ReporterUsername,
				fmt.Sprint(res[i].ReporterID),
				fmt.Sprint(res[i].Confidence),
				res[i].Notes,
				res[i].ReportedAt.Format(h.Config.TimeFormat),
				res[i].ExpiresAt.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].IsActive),
			},
		})
	}

	return list, err
}

func (h *Handler) LocationReportGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.LocationReport.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("building_name", entity.BuildingName)
	v.Set("building_type", fmt.Sprint(entity.BuildingType))
	v.Set("custom_item_name", entity.CustomItemName)
	v.Set("coordinate_x", fmt.Sprint(entity.CoordinateX))
	v.Set("coordinate_y", fmt.Sprint(entity.CoordinateY))
	v.Set("street_name", entity.StreetName)
	v.Set("street_number", entity.StreetNumber)
	v.Set("guild_level", fmt.Sprint(entity.GuildLevel))
	v.Set("reporter_username", entity.ReporterUsername)
	v.Set("reporter_id", fmt.Sprint(entity.ReporterID))
	v.Set("confidence", fmt.Sprint(entity.Confidence))
	v.Set("notes", entity.Notes)
	v.Set("expires_at", entity.ExpiresAt.Format(dateTimeFormat))
	v.Set("is_active", fmt.Sprint(entity.IsActive))
	return v, err
}

func (h *Handler) PasswordTokenCreate(ctx echo.Context) error {
	var payload PasswordToken
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.PasswordToken.Create()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload PasswordToken
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt == nil {
		var empty time.Time
		op.SetCreatedAt(empty)
	} else {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenDelete(ctx echo.Context, id int) error {
	return h.client.PasswordToken.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) PasswordTokenList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.PasswordToken.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(passwordtoken.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"User ID",
			"Created at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].UserID),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) PasswordTokenGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("user_id", fmt.Sprint(entity.UserID))
	v.Set("created_at", entity.CreatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) RichVampireCreate(ctx echo.Context) error {
	var payload RichVampire
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.RichVampire.Create()
	op.SetVampireName(payload.VampireName)
	if payload.LastUpdated != nil {
		op.SetLastUpdated(*payload.LastUpdated)
	}
	if payload.ReporterUsername != nil {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID != nil {
		op.SetReporterID(*payload.ReporterID)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) RichVampireUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.RichVampire.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload RichVampire
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetVampireName(payload.VampireName)
	if payload.LastUpdated == nil {
		var empty time.Time
		op.SetLastUpdated(empty)
	} else {
		op.SetLastUpdated(*payload.LastUpdated)
	}
	if payload.ReporterUsername == nil {
		op.ClearReporterUsername()
	} else {
		op.SetReporterUsername(*payload.ReporterUsername)
	}
	if payload.ReporterID == nil {
		op.ClearReporterID()
	} else {
		op.SetReporterID(*payload.ReporterID)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) RichVampireDelete(ctx echo.Context, id int) error {
	return h.client.RichVampire.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) RichVampireList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.RichVampire.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(richvampire.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Vampire name",
			"Last updated",
			"Reporter username",
			"Reporter ID",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].VampireName,
				res[i].LastUpdated.Format(h.Config.TimeFormat),
				res[i].ReporterUsername,
				fmt.Sprint(res[i].ReporterID),
			},
		})
	}

	return list, err
}

func (h *Handler) RichVampireGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.RichVampire.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("vampire_name", entity.VampireName)
	v.Set("last_updated", entity.LastUpdated.Format(dateTimeFormat))
	v.Set("reporter_username", entity.ReporterUsername)
	v.Set("reporter_id", fmt.Sprint(entity.ReporterID))
	return v, err
}

func (h *Handler) UserCreate(ctx echo.Context) error {
	var payload User
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.User.Create()
	op.SetName(payload.Name)
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	if payload.TotalReports != nil {
		op.SetTotalReports(*payload.TotalReports)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload User
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetName(payload.Name)
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	if payload.TotalReports == nil {
		var empty int
		op.SetTotalReports(empty)
	} else {
		op.SetTotalReports(*payload.TotalReports)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserDelete(ctx echo.Context, id int) error {
	return h.client.User.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) UserList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.User.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(user.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Name",
			"Email",
			"Verified",
			"Admin",
			"Created at",
			"Total reports",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Name,
				res[i].Email,
				fmt.Sprint(res[i].Verified),
				fmt.Sprint(res[i].Admin),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].TotalReports),
			},
		})
	}

	return list, err
}

func (h *Handler) UserGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("name", entity.Name)
	v.Set("email", entity.Email)
	v.Set("verified", fmt.Sprint(entity.Verified))
	v.Set("admin", fmt.Sprint(entity.Admin))
	v.Set("total_reports", fmt.Sprint(entity.TotalReports))
	return v, err
}

func (h *Handler) getPageAndOffset(ctx echo.Context) (int, int) {
	if page, err := strconv.Atoi(ctx.QueryParam(h.Config.PageQueryKey)); err == nil {
		if page > 1 {
			return page, (page - 1) * h.Config.ItemsPerPage
		}
	}
	return 1, 0
}

func (h *Handler) bind(ctx echo.Context, entity any) error {
	// Echo requires some pre-processing of form values to avoid problems.
	for k, v := range ctx.Request().Form {
		// Remove empty field values so Echo's bind does not fail when trying to parse things like
		// times, etc.
		if len(v) == 1 && len(v[0]) == 0 {
			delete(ctx.Request().Form, k)
			continue
		}

		// Echo expects datetime values to be in a certain format but that does not align with the datetime-local
		// HTML form element format, so we will attempt to convert it here.
		for _, format := range []string{dateTimeFormatNoSeconds, dateTimeFormat} {
			if t, err := time.Parse(format, v[0]); err == nil {
				ctx.Request().Form[k][0] = t.Format(time.RFC3339)
				break
			}
		}
	}
	return ctx.Bind(entity)
}
