// Code generated by ent, DO NOT EDIT.
package admin

import (
	"time"

	"github.com/mikestefanello/pagoda/ent/locationreport"
)

type BloodDeity struct {
	VampireName      string     `form:"vampire_name"`
	BloodAmount      *int64     `form:"blood_amount"`
	LastUpdated      *time.Time `form:"last_updated"`
	ReporterUsername *string    `form:"reporter_username"`
	ReporterID       *int       `form:"reporter_id"`
}

type LocationReport struct {
	BuildingName     string                      `form:"building_name"`
	BuildingType     locationreport.BuildingType `form:"building_type"`
	CustomItemName   *string                     `form:"custom_item_name"`
	CoordinateX      *int                        `form:"coordinate_x"`
	CoordinateY      *int                        `form:"coordinate_y"`
	StreetName       *string                     `form:"street_name"`
	StreetNumber     *string                     `form:"street_number"`
	GuildLevel       *int                        `form:"guild_level"`
	ReporterUsername *string                     `form:"reporter_username"`
	ReporterID       *int                        `form:"reporter_id"`
	Confidence       *locationreport.Confidence  `form:"confidence"`
	Notes            *string                     `form:"notes"`
	ReportedAt       *time.Time                  `form:"reported_at"`
	ExpiresAt        *time.Time                  `form:"expires_at"`
	IsActive         bool                        `form:"is_active"`
}

type PasswordToken struct {
	Token     *string    `form:"token"`
	UserID    int        `form:"user_id"`
	CreatedAt *time.Time `form:"created_at"`
}

type RichVampire struct {
	VampireName      string     `form:"vampire_name"`
	LastUpdated      *time.Time `form:"last_updated"`
	ReporterUsername *string    `form:"reporter_username"`
	ReporterID       *int       `form:"reporter_id"`
}

type User struct {
	Name         string     `form:"name"`
	Email        string     `form:"email"`
	Password     *string    `form:"password"`
	Verified     bool       `form:"verified"`
	Admin        bool       `form:"admin"`
	CreatedAt    *time.Time `form:"created_at"`
	TotalReports *int       `form:"total_reports"`
}

type EntityList struct {
	Columns     []string
	Entities    []EntityValues
	Page        int
	HasNextPage bool
}

type EntityValues struct {
	ID     int
	Values []string
}

type HandlerConfig struct {
	ItemsPerPage int
	PageQueryKey string
	TimeFormat   string
}

func GetEntityTypeNames() []string {
	return []string{
		"BloodDeity",
		"LocationReport",
		"PasswordToken",
		"RichVampire",
		"User",
	}
}
