// Code generated by ent, DO NOT EDIT.

package richvampire

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the richvampire type in the database.
	Label = "rich_vampire"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVampireName holds the string denoting the vampire_name field in the database.
	FieldVampireName = "vampire_name"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// FieldReporterUsername holds the string denoting the reporter_username field in the database.
	FieldReporterUsername = "reporter_username"
	// FieldReporterID holds the string denoting the reporter_id field in the database.
	FieldReporterID = "reporter_id"
	// EdgeReporter holds the string denoting the reporter edge name in mutations.
	EdgeReporter = "reporter"
	// Table holds the table name of the richvampire in the database.
	Table = "rich_vampires"
	// ReporterTable is the table that holds the reporter relation/edge.
	ReporterTable = "rich_vampires"
	// ReporterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReporterInverseTable = "users"
	// ReporterColumn is the table column denoting the reporter relation/edge.
	ReporterColumn = "reporter_id"
)

// Columns holds all SQL columns for richvampire fields.
var Columns = []string{
	FieldID,
	FieldVampireName,
	FieldLastUpdated,
	FieldReporterUsername,
	FieldReporterID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VampireNameValidator is a validator for the "vampire_name" field. It is called by the builders before save.
	VampireNameValidator func(string) error
	// DefaultLastUpdated holds the default value on creation for the "last_updated" field.
	DefaultLastUpdated func() time.Time
)

// OrderOption defines the ordering options for the RichVampire queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVampireName orders the results by the vampire_name field.
func ByVampireName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVampireName, opts...).ToFunc()
}

// ByLastUpdated orders the results by the last_updated field.
func ByLastUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdated, opts...).ToFunc()
}

// ByReporterUsername orders the results by the reporter_username field.
func ByReporterUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterUsername, opts...).ToFunc()
}

// ByReporterID orders the results by the reporter_id field.
func ByReporterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterID, opts...).ToFunc()
}

// ByReporterField orders the results by reporter field.
func ByReporterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReporterStep(), sql.OrderByField(field, opts...))
	}
}
func newReporterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReporterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ReporterTable, ReporterColumn),
	)
}
