// Code generated by ent, DO NOT EDIT.

package richvampire

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLTE(FieldID, id))
}

// VampireName applies equality check predicate on the "vampire_name" field. It's identical to VampireNameEQ.
func VampireName(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldVampireName, v))
}

// LastUpdated applies equality check predicate on the "last_updated" field. It's identical to LastUpdatedEQ.
func LastUpdated(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldLastUpdated, v))
}

// ReporterUsername applies equality check predicate on the "reporter_username" field. It's identical to ReporterUsernameEQ.
func ReporterUsername(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldReporterUsername, v))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldReporterID, v))
}

// VampireNameEQ applies the EQ predicate on the "vampire_name" field.
func VampireNameEQ(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldVampireName, v))
}

// VampireNameNEQ applies the NEQ predicate on the "vampire_name" field.
func VampireNameNEQ(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNEQ(FieldVampireName, v))
}

// VampireNameIn applies the In predicate on the "vampire_name" field.
func VampireNameIn(vs ...string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIn(FieldVampireName, vs...))
}

// VampireNameNotIn applies the NotIn predicate on the "vampire_name" field.
func VampireNameNotIn(vs ...string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotIn(FieldVampireName, vs...))
}

// VampireNameGT applies the GT predicate on the "vampire_name" field.
func VampireNameGT(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGT(FieldVampireName, v))
}

// VampireNameGTE applies the GTE predicate on the "vampire_name" field.
func VampireNameGTE(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGTE(FieldVampireName, v))
}

// VampireNameLT applies the LT predicate on the "vampire_name" field.
func VampireNameLT(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLT(FieldVampireName, v))
}

// VampireNameLTE applies the LTE predicate on the "vampire_name" field.
func VampireNameLTE(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLTE(FieldVampireName, v))
}

// VampireNameContains applies the Contains predicate on the "vampire_name" field.
func VampireNameContains(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldContains(FieldVampireName, v))
}

// VampireNameHasPrefix applies the HasPrefix predicate on the "vampire_name" field.
func VampireNameHasPrefix(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldHasPrefix(FieldVampireName, v))
}

// VampireNameHasSuffix applies the HasSuffix predicate on the "vampire_name" field.
func VampireNameHasSuffix(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldHasSuffix(FieldVampireName, v))
}

// VampireNameEqualFold applies the EqualFold predicate on the "vampire_name" field.
func VampireNameEqualFold(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEqualFold(FieldVampireName, v))
}

// VampireNameContainsFold applies the ContainsFold predicate on the "vampire_name" field.
func VampireNameContainsFold(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldContainsFold(FieldVampireName, v))
}

// LastUpdatedEQ applies the EQ predicate on the "last_updated" field.
func LastUpdatedEQ(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldLastUpdated, v))
}

// LastUpdatedNEQ applies the NEQ predicate on the "last_updated" field.
func LastUpdatedNEQ(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNEQ(FieldLastUpdated, v))
}

// LastUpdatedIn applies the In predicate on the "last_updated" field.
func LastUpdatedIn(vs ...time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIn(FieldLastUpdated, vs...))
}

// LastUpdatedNotIn applies the NotIn predicate on the "last_updated" field.
func LastUpdatedNotIn(vs ...time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotIn(FieldLastUpdated, vs...))
}

// LastUpdatedGT applies the GT predicate on the "last_updated" field.
func LastUpdatedGT(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGT(FieldLastUpdated, v))
}

// LastUpdatedGTE applies the GTE predicate on the "last_updated" field.
func LastUpdatedGTE(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGTE(FieldLastUpdated, v))
}

// LastUpdatedLT applies the LT predicate on the "last_updated" field.
func LastUpdatedLT(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLT(FieldLastUpdated, v))
}

// LastUpdatedLTE applies the LTE predicate on the "last_updated" field.
func LastUpdatedLTE(v time.Time) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLTE(FieldLastUpdated, v))
}

// ReporterUsernameEQ applies the EQ predicate on the "reporter_username" field.
func ReporterUsernameEQ(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldReporterUsername, v))
}

// ReporterUsernameNEQ applies the NEQ predicate on the "reporter_username" field.
func ReporterUsernameNEQ(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNEQ(FieldReporterUsername, v))
}

// ReporterUsernameIn applies the In predicate on the "reporter_username" field.
func ReporterUsernameIn(vs ...string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIn(FieldReporterUsername, vs...))
}

// ReporterUsernameNotIn applies the NotIn predicate on the "reporter_username" field.
func ReporterUsernameNotIn(vs ...string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotIn(FieldReporterUsername, vs...))
}

// ReporterUsernameGT applies the GT predicate on the "reporter_username" field.
func ReporterUsernameGT(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGT(FieldReporterUsername, v))
}

// ReporterUsernameGTE applies the GTE predicate on the "reporter_username" field.
func ReporterUsernameGTE(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldGTE(FieldReporterUsername, v))
}

// ReporterUsernameLT applies the LT predicate on the "reporter_username" field.
func ReporterUsernameLT(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLT(FieldReporterUsername, v))
}

// ReporterUsernameLTE applies the LTE predicate on the "reporter_username" field.
func ReporterUsernameLTE(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldLTE(FieldReporterUsername, v))
}

// ReporterUsernameContains applies the Contains predicate on the "reporter_username" field.
func ReporterUsernameContains(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldContains(FieldReporterUsername, v))
}

// ReporterUsernameHasPrefix applies the HasPrefix predicate on the "reporter_username" field.
func ReporterUsernameHasPrefix(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldHasPrefix(FieldReporterUsername, v))
}

// ReporterUsernameHasSuffix applies the HasSuffix predicate on the "reporter_username" field.
func ReporterUsernameHasSuffix(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldHasSuffix(FieldReporterUsername, v))
}

// ReporterUsernameIsNil applies the IsNil predicate on the "reporter_username" field.
func ReporterUsernameIsNil() predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIsNull(FieldReporterUsername))
}

// ReporterUsernameNotNil applies the NotNil predicate on the "reporter_username" field.
func ReporterUsernameNotNil() predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotNull(FieldReporterUsername))
}

// ReporterUsernameEqualFold applies the EqualFold predicate on the "reporter_username" field.
func ReporterUsernameEqualFold(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEqualFold(FieldReporterUsername, v))
}

// ReporterUsernameContainsFold applies the ContainsFold predicate on the "reporter_username" field.
func ReporterUsernameContainsFold(v string) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldContainsFold(FieldReporterUsername, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...int) predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDIsNil applies the IsNil predicate on the "reporter_id" field.
func ReporterIDIsNil() predicate.RichVampire {
	return predicate.RichVampire(sql.FieldIsNull(FieldReporterID))
}

// ReporterIDNotNil applies the NotNil predicate on the "reporter_id" field.
func ReporterIDNotNil() predicate.RichVampire {
	return predicate.RichVampire(sql.FieldNotNull(FieldReporterID))
}

// HasReporter applies the HasEdge predicate on the "reporter" edge.
func HasReporter() predicate.RichVampire {
	return predicate.RichVampire(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ReporterTable, ReporterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReporterWith applies the HasEdge predicate on the "reporter" edge with a given conditions (other predicates).
func HasReporterWith(preds ...predicate.User) predicate.RichVampire {
	return predicate.RichVampire(func(s *sql.Selector) {
		step := newReporterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RichVampire) predicate.RichVampire {
	return predicate.RichVampire(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RichVampire) predicate.RichVampire {
	return predicate.RichVampire(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RichVampire) predicate.RichVampire {
	return predicate.RichVampire(sql.NotPredicates(p))
}
