// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// BloodDeityUpdate is the builder for updating BloodDeity entities.
type BloodDeityUpdate struct {
	config
	hooks    []Hook
	mutation *BloodDeityMutation
}

// Where appends a list predicates to the BloodDeityUpdate builder.
func (bdu *BloodDeityUpdate) Where(ps ...predicate.BloodDeity) *BloodDeityUpdate {
	bdu.mutation.Where(ps...)
	return bdu
}

// SetVampireName sets the "vampire_name" field.
func (bdu *BloodDeityUpdate) SetVampireName(s string) *BloodDeityUpdate {
	bdu.mutation.SetVampireName(s)
	return bdu
}

// SetNillableVampireName sets the "vampire_name" field if the given value is not nil.
func (bdu *BloodDeityUpdate) SetNillableVampireName(s *string) *BloodDeityUpdate {
	if s != nil {
		bdu.SetVampireName(*s)
	}
	return bdu
}

// SetBloodAmount sets the "blood_amount" field.
func (bdu *BloodDeityUpdate) SetBloodAmount(i int64) *BloodDeityUpdate {
	bdu.mutation.ResetBloodAmount()
	bdu.mutation.SetBloodAmount(i)
	return bdu
}

// SetNillableBloodAmount sets the "blood_amount" field if the given value is not nil.
func (bdu *BloodDeityUpdate) SetNillableBloodAmount(i *int64) *BloodDeityUpdate {
	if i != nil {
		bdu.SetBloodAmount(*i)
	}
	return bdu
}

// AddBloodAmount adds i to the "blood_amount" field.
func (bdu *BloodDeityUpdate) AddBloodAmount(i int64) *BloodDeityUpdate {
	bdu.mutation.AddBloodAmount(i)
	return bdu
}

// SetLastUpdated sets the "last_updated" field.
func (bdu *BloodDeityUpdate) SetLastUpdated(t time.Time) *BloodDeityUpdate {
	bdu.mutation.SetLastUpdated(t)
	return bdu
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (bdu *BloodDeityUpdate) SetNillableLastUpdated(t *time.Time) *BloodDeityUpdate {
	if t != nil {
		bdu.SetLastUpdated(*t)
	}
	return bdu
}

// SetReporterUsername sets the "reporter_username" field.
func (bdu *BloodDeityUpdate) SetReporterUsername(s string) *BloodDeityUpdate {
	bdu.mutation.SetReporterUsername(s)
	return bdu
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (bdu *BloodDeityUpdate) SetNillableReporterUsername(s *string) *BloodDeityUpdate {
	if s != nil {
		bdu.SetReporterUsername(*s)
	}
	return bdu
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (bdu *BloodDeityUpdate) ClearReporterUsername() *BloodDeityUpdate {
	bdu.mutation.ClearReporterUsername()
	return bdu
}

// SetReporterID sets the "reporter_id" field.
func (bdu *BloodDeityUpdate) SetReporterID(i int) *BloodDeityUpdate {
	bdu.mutation.SetReporterID(i)
	return bdu
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (bdu *BloodDeityUpdate) SetNillableReporterID(i *int) *BloodDeityUpdate {
	if i != nil {
		bdu.SetReporterID(*i)
	}
	return bdu
}

// ClearReporterID clears the value of the "reporter_id" field.
func (bdu *BloodDeityUpdate) ClearReporterID() *BloodDeityUpdate {
	bdu.mutation.ClearReporterID()
	return bdu
}

// SetReporter sets the "reporter" edge to the User entity.
func (bdu *BloodDeityUpdate) SetReporter(u *User) *BloodDeityUpdate {
	return bdu.SetReporterID(u.ID)
}

// Mutation returns the BloodDeityMutation object of the builder.
func (bdu *BloodDeityUpdate) Mutation() *BloodDeityMutation {
	return bdu.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (bdu *BloodDeityUpdate) ClearReporter() *BloodDeityUpdate {
	bdu.mutation.ClearReporter()
	return bdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bdu *BloodDeityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bdu.sqlSave, bdu.mutation, bdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bdu *BloodDeityUpdate) SaveX(ctx context.Context) int {
	affected, err := bdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bdu *BloodDeityUpdate) Exec(ctx context.Context) error {
	_, err := bdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdu *BloodDeityUpdate) ExecX(ctx context.Context) {
	if err := bdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bdu *BloodDeityUpdate) check() error {
	if v, ok := bdu.mutation.VampireName(); ok {
		if err := blooddeity.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.vampire_name": %w`, err)}
		}
	}
	if v, ok := bdu.mutation.BloodAmount(); ok {
		if err := blooddeity.BloodAmountValidator(v); err != nil {
			return &ValidationError{Name: "blood_amount", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.blood_amount": %w`, err)}
		}
	}
	return nil
}

func (bdu *BloodDeityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(blooddeity.Table, blooddeity.Columns, sqlgraph.NewFieldSpec(blooddeity.FieldID, field.TypeInt))
	if ps := bdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bdu.mutation.VampireName(); ok {
		_spec.SetField(blooddeity.FieldVampireName, field.TypeString, value)
	}
	if value, ok := bdu.mutation.BloodAmount(); ok {
		_spec.SetField(blooddeity.FieldBloodAmount, field.TypeInt64, value)
	}
	if value, ok := bdu.mutation.AddedBloodAmount(); ok {
		_spec.AddField(blooddeity.FieldBloodAmount, field.TypeInt64, value)
	}
	if value, ok := bdu.mutation.LastUpdated(); ok {
		_spec.SetField(blooddeity.FieldLastUpdated, field.TypeTime, value)
	}
	if value, ok := bdu.mutation.ReporterUsername(); ok {
		_spec.SetField(blooddeity.FieldReporterUsername, field.TypeString, value)
	}
	if bdu.mutation.ReporterUsernameCleared() {
		_spec.ClearField(blooddeity.FieldReporterUsername, field.TypeString)
	}
	if bdu.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   blooddeity.ReporterTable,
			Columns: []string{blooddeity.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bdu.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   blooddeity.ReporterTable,
			Columns: []string{blooddeity.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blooddeity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bdu.mutation.done = true
	return n, nil
}

// BloodDeityUpdateOne is the builder for updating a single BloodDeity entity.
type BloodDeityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BloodDeityMutation
}

// SetVampireName sets the "vampire_name" field.
func (bduo *BloodDeityUpdateOne) SetVampireName(s string) *BloodDeityUpdateOne {
	bduo.mutation.SetVampireName(s)
	return bduo
}

// SetNillableVampireName sets the "vampire_name" field if the given value is not nil.
func (bduo *BloodDeityUpdateOne) SetNillableVampireName(s *string) *BloodDeityUpdateOne {
	if s != nil {
		bduo.SetVampireName(*s)
	}
	return bduo
}

// SetBloodAmount sets the "blood_amount" field.
func (bduo *BloodDeityUpdateOne) SetBloodAmount(i int64) *BloodDeityUpdateOne {
	bduo.mutation.ResetBloodAmount()
	bduo.mutation.SetBloodAmount(i)
	return bduo
}

// SetNillableBloodAmount sets the "blood_amount" field if the given value is not nil.
func (bduo *BloodDeityUpdateOne) SetNillableBloodAmount(i *int64) *BloodDeityUpdateOne {
	if i != nil {
		bduo.SetBloodAmount(*i)
	}
	return bduo
}

// AddBloodAmount adds i to the "blood_amount" field.
func (bduo *BloodDeityUpdateOne) AddBloodAmount(i int64) *BloodDeityUpdateOne {
	bduo.mutation.AddBloodAmount(i)
	return bduo
}

// SetLastUpdated sets the "last_updated" field.
func (bduo *BloodDeityUpdateOne) SetLastUpdated(t time.Time) *BloodDeityUpdateOne {
	bduo.mutation.SetLastUpdated(t)
	return bduo
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (bduo *BloodDeityUpdateOne) SetNillableLastUpdated(t *time.Time) *BloodDeityUpdateOne {
	if t != nil {
		bduo.SetLastUpdated(*t)
	}
	return bduo
}

// SetReporterUsername sets the "reporter_username" field.
func (bduo *BloodDeityUpdateOne) SetReporterUsername(s string) *BloodDeityUpdateOne {
	bduo.mutation.SetReporterUsername(s)
	return bduo
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (bduo *BloodDeityUpdateOne) SetNillableReporterUsername(s *string) *BloodDeityUpdateOne {
	if s != nil {
		bduo.SetReporterUsername(*s)
	}
	return bduo
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (bduo *BloodDeityUpdateOne) ClearReporterUsername() *BloodDeityUpdateOne {
	bduo.mutation.ClearReporterUsername()
	return bduo
}

// SetReporterID sets the "reporter_id" field.
func (bduo *BloodDeityUpdateOne) SetReporterID(i int) *BloodDeityUpdateOne {
	bduo.mutation.SetReporterID(i)
	return bduo
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (bduo *BloodDeityUpdateOne) SetNillableReporterID(i *int) *BloodDeityUpdateOne {
	if i != nil {
		bduo.SetReporterID(*i)
	}
	return bduo
}

// ClearReporterID clears the value of the "reporter_id" field.
func (bduo *BloodDeityUpdateOne) ClearReporterID() *BloodDeityUpdateOne {
	bduo.mutation.ClearReporterID()
	return bduo
}

// SetReporter sets the "reporter" edge to the User entity.
func (bduo *BloodDeityUpdateOne) SetReporter(u *User) *BloodDeityUpdateOne {
	return bduo.SetReporterID(u.ID)
}

// Mutation returns the BloodDeityMutation object of the builder.
func (bduo *BloodDeityUpdateOne) Mutation() *BloodDeityMutation {
	return bduo.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (bduo *BloodDeityUpdateOne) ClearReporter() *BloodDeityUpdateOne {
	bduo.mutation.ClearReporter()
	return bduo
}

// Where appends a list predicates to the BloodDeityUpdate builder.
func (bduo *BloodDeityUpdateOne) Where(ps ...predicate.BloodDeity) *BloodDeityUpdateOne {
	bduo.mutation.Where(ps...)
	return bduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bduo *BloodDeityUpdateOne) Select(field string, fields ...string) *BloodDeityUpdateOne {
	bduo.fields = append([]string{field}, fields...)
	return bduo
}

// Save executes the query and returns the updated BloodDeity entity.
func (bduo *BloodDeityUpdateOne) Save(ctx context.Context) (*BloodDeity, error) {
	return withHooks(ctx, bduo.sqlSave, bduo.mutation, bduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bduo *BloodDeityUpdateOne) SaveX(ctx context.Context) *BloodDeity {
	node, err := bduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bduo *BloodDeityUpdateOne) Exec(ctx context.Context) error {
	_, err := bduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bduo *BloodDeityUpdateOne) ExecX(ctx context.Context) {
	if err := bduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bduo *BloodDeityUpdateOne) check() error {
	if v, ok := bduo.mutation.VampireName(); ok {
		if err := blooddeity.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.vampire_name": %w`, err)}
		}
	}
	if v, ok := bduo.mutation.BloodAmount(); ok {
		if err := blooddeity.BloodAmountValidator(v); err != nil {
			return &ValidationError{Name: "blood_amount", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.blood_amount": %w`, err)}
		}
	}
	return nil
}

func (bduo *BloodDeityUpdateOne) sqlSave(ctx context.Context) (_node *BloodDeity, err error) {
	if err := bduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blooddeity.Table, blooddeity.Columns, sqlgraph.NewFieldSpec(blooddeity.FieldID, field.TypeInt))
	id, ok := bduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BloodDeity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blooddeity.FieldID)
		for _, f := range fields {
			if !blooddeity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blooddeity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bduo.mutation.VampireName(); ok {
		_spec.SetField(blooddeity.FieldVampireName, field.TypeString, value)
	}
	if value, ok := bduo.mutation.BloodAmount(); ok {
		_spec.SetField(blooddeity.FieldBloodAmount, field.TypeInt64, value)
	}
	if value, ok := bduo.mutation.AddedBloodAmount(); ok {
		_spec.AddField(blooddeity.FieldBloodAmount, field.TypeInt64, value)
	}
	if value, ok := bduo.mutation.LastUpdated(); ok {
		_spec.SetField(blooddeity.FieldLastUpdated, field.TypeTime, value)
	}
	if value, ok := bduo.mutation.ReporterUsername(); ok {
		_spec.SetField(blooddeity.FieldReporterUsername, field.TypeString, value)
	}
	if bduo.mutation.ReporterUsernameCleared() {
		_spec.ClearField(blooddeity.FieldReporterUsername, field.TypeString)
	}
	if bduo.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   blooddeity.ReporterTable,
			Columns: []string{blooddeity.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bduo.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   blooddeity.ReporterTable,
			Columns: []string{blooddeity.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BloodDeity{config: bduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blooddeity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bduo.mutation.done = true
	return _node, nil
}
