// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/user"
)

// BloodDeityCreate is the builder for creating a BloodDeity entity.
type BloodDeityCreate struct {
	config
	mutation *BloodDeityMutation
	hooks    []Hook
}

// SetVampireName sets the "vampire_name" field.
func (bdc *BloodDeityCreate) SetVampireName(s string) *BloodDeityCreate {
	bdc.mutation.SetVampireName(s)
	return bdc
}

// SetBloodAmount sets the "blood_amount" field.
func (bdc *BloodDeityCreate) SetBloodAmount(i int64) *BloodDeityCreate {
	bdc.mutation.SetBloodAmount(i)
	return bdc
}

// SetNillableBloodAmount sets the "blood_amount" field if the given value is not nil.
func (bdc *BloodDeityCreate) SetNillableBloodAmount(i *int64) *BloodDeityCreate {
	if i != nil {
		bdc.SetBloodAmount(*i)
	}
	return bdc
}

// SetLastUpdated sets the "last_updated" field.
func (bdc *BloodDeityCreate) SetLastUpdated(t time.Time) *BloodDeityCreate {
	bdc.mutation.SetLastUpdated(t)
	return bdc
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (bdc *BloodDeityCreate) SetNillableLastUpdated(t *time.Time) *BloodDeityCreate {
	if t != nil {
		bdc.SetLastUpdated(*t)
	}
	return bdc
}

// SetReporterUsername sets the "reporter_username" field.
func (bdc *BloodDeityCreate) SetReporterUsername(s string) *BloodDeityCreate {
	bdc.mutation.SetReporterUsername(s)
	return bdc
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (bdc *BloodDeityCreate) SetNillableReporterUsername(s *string) *BloodDeityCreate {
	if s != nil {
		bdc.SetReporterUsername(*s)
	}
	return bdc
}

// SetReporterID sets the "reporter_id" field.
func (bdc *BloodDeityCreate) SetReporterID(i int) *BloodDeityCreate {
	bdc.mutation.SetReporterID(i)
	return bdc
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (bdc *BloodDeityCreate) SetNillableReporterID(i *int) *BloodDeityCreate {
	if i != nil {
		bdc.SetReporterID(*i)
	}
	return bdc
}

// SetReporter sets the "reporter" edge to the User entity.
func (bdc *BloodDeityCreate) SetReporter(u *User) *BloodDeityCreate {
	return bdc.SetReporterID(u.ID)
}

// Mutation returns the BloodDeityMutation object of the builder.
func (bdc *BloodDeityCreate) Mutation() *BloodDeityMutation {
	return bdc.mutation
}

// Save creates the BloodDeity in the database.
func (bdc *BloodDeityCreate) Save(ctx context.Context) (*BloodDeity, error) {
	bdc.defaults()
	return withHooks(ctx, bdc.sqlSave, bdc.mutation, bdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bdc *BloodDeityCreate) SaveX(ctx context.Context) *BloodDeity {
	v, err := bdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bdc *BloodDeityCreate) Exec(ctx context.Context) error {
	_, err := bdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdc *BloodDeityCreate) ExecX(ctx context.Context) {
	if err := bdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bdc *BloodDeityCreate) defaults() {
	if _, ok := bdc.mutation.BloodAmount(); !ok {
		v := blooddeity.DefaultBloodAmount
		bdc.mutation.SetBloodAmount(v)
	}
	if _, ok := bdc.mutation.LastUpdated(); !ok {
		v := blooddeity.DefaultLastUpdated()
		bdc.mutation.SetLastUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bdc *BloodDeityCreate) check() error {
	if _, ok := bdc.mutation.VampireName(); !ok {
		return &ValidationError{Name: "vampire_name", err: errors.New(`ent: missing required field "BloodDeity.vampire_name"`)}
	}
	if v, ok := bdc.mutation.VampireName(); ok {
		if err := blooddeity.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.vampire_name": %w`, err)}
		}
	}
	if _, ok := bdc.mutation.BloodAmount(); !ok {
		return &ValidationError{Name: "blood_amount", err: errors.New(`ent: missing required field "BloodDeity.blood_amount"`)}
	}
	if v, ok := bdc.mutation.BloodAmount(); ok {
		if err := blooddeity.BloodAmountValidator(v); err != nil {
			return &ValidationError{Name: "blood_amount", err: fmt.Errorf(`ent: validator failed for field "BloodDeity.blood_amount": %w`, err)}
		}
	}
	if _, ok := bdc.mutation.LastUpdated(); !ok {
		return &ValidationError{Name: "last_updated", err: errors.New(`ent: missing required field "BloodDeity.last_updated"`)}
	}
	return nil
}

func (bdc *BloodDeityCreate) sqlSave(ctx context.Context) (*BloodDeity, error) {
	if err := bdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bdc.mutation.id = &_node.ID
	bdc.mutation.done = true
	return _node, nil
}

func (bdc *BloodDeityCreate) createSpec() (*BloodDeity, *sqlgraph.CreateSpec) {
	var (
		_node = &BloodDeity{config: bdc.config}
		_spec = sqlgraph.NewCreateSpec(blooddeity.Table, sqlgraph.NewFieldSpec(blooddeity.FieldID, field.TypeInt))
	)
	if value, ok := bdc.mutation.VampireName(); ok {
		_spec.SetField(blooddeity.FieldVampireName, field.TypeString, value)
		_node.VampireName = value
	}
	if value, ok := bdc.mutation.BloodAmount(); ok {
		_spec.SetField(blooddeity.FieldBloodAmount, field.TypeInt64, value)
		_node.BloodAmount = value
	}
	if value, ok := bdc.mutation.LastUpdated(); ok {
		_spec.SetField(blooddeity.FieldLastUpdated, field.TypeTime, value)
		_node.LastUpdated = value
	}
	if value, ok := bdc.mutation.ReporterUsername(); ok {
		_spec.SetField(blooddeity.FieldReporterUsername, field.TypeString, value)
		_node.ReporterUsername = value
	}
	if nodes := bdc.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   blooddeity.ReporterTable,
			Columns: []string{blooddeity.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReporterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BloodDeityCreateBulk is the builder for creating many BloodDeity entities in bulk.
type BloodDeityCreateBulk struct {
	config
	err      error
	builders []*BloodDeityCreate
}

// Save creates the BloodDeity entities in the database.
func (bdcb *BloodDeityCreateBulk) Save(ctx context.Context) ([]*BloodDeity, error) {
	if bdcb.err != nil {
		return nil, bdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bdcb.builders))
	nodes := make([]*BloodDeity, len(bdcb.builders))
	mutators := make([]Mutator, len(bdcb.builders))
	for i := range bdcb.builders {
		func(i int, root context.Context) {
			builder := bdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BloodDeityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bdcb *BloodDeityCreateBulk) SaveX(ctx context.Context) []*BloodDeity {
	v, err := bdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bdcb *BloodDeityCreateBulk) Exec(ctx context.Context) error {
	_, err := bdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bdcb *BloodDeityCreateBulk) ExecX(ctx context.Context) {
	if err := bdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
