// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// BloodDeityDelete is the builder for deleting a BloodDeity entity.
type BloodDeityDelete struct {
	config
	hooks    []Hook
	mutation *BloodDeityMutation
}

// Where appends a list predicates to the BloodDeityDelete builder.
func (bdd *BloodDeityDelete) Where(ps ...predicate.BloodDeity) *BloodDeityDelete {
	bdd.mutation.Where(ps...)
	return bdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bdd *BloodDeityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bdd.sqlExec, bdd.mutation, bdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bdd *BloodDeityDelete) ExecX(ctx context.Context) int {
	n, err := bdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bdd *BloodDeityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(blooddeity.Table, sqlgraph.NewFieldSpec(blooddeity.FieldID, field.TypeInt))
	if ps := bdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bdd.mutation.done = true
	return affected, err
}

// BloodDeityDeleteOne is the builder for deleting a single BloodDeity entity.
type BloodDeityDeleteOne struct {
	bdd *BloodDeityDelete
}

// Where appends a list predicates to the BloodDeityDelete builder.
func (bddo *BloodDeityDeleteOne) Where(ps ...predicate.BloodDeity) *BloodDeityDeleteOne {
	bddo.bdd.mutation.Where(ps...)
	return bddo
}

// Exec executes the deletion query.
func (bddo *BloodDeityDeleteOne) Exec(ctx context.Context) error {
	n, err := bddo.bdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blooddeity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bddo *BloodDeityDeleteOne) ExecX(ctx context.Context) {
	if err := bddo.Exec(ctx); err != nil {
		panic(err)
	}
}
