// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/user"
)

// BloodDeity is the model entity for the BloodDeity schema.
type BloodDeity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name of the vampire
	VampireName string `json:"vampire_name,omitempty"`
	// Amount of blood the vampire has
	BloodAmount int64 `json:"blood_amount,omitempty"`
	// When this entry was last updated
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// Username of the reporter
	ReporterUsername string `json:"reporter_username,omitempty"`
	// ID of the reporter user
	ReporterID int `json:"reporter_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BloodDeityQuery when eager-loading is set.
	Edges        BloodDeityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BloodDeityEdges holds the relations/edges for other nodes in the graph.
type BloodDeityEdges struct {
	// Reporter holds the value of the reporter edge.
	Reporter *User `json:"reporter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReporterOrErr returns the Reporter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BloodDeityEdges) ReporterOrErr() (*User, error) {
	if e.Reporter != nil {
		return e.Reporter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reporter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BloodDeity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blooddeity.FieldID, blooddeity.FieldBloodAmount, blooddeity.FieldReporterID:
			values[i] = new(sql.NullInt64)
		case blooddeity.FieldVampireName, blooddeity.FieldReporterUsername:
			values[i] = new(sql.NullString)
		case blooddeity.FieldLastUpdated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BloodDeity fields.
func (bd *BloodDeity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blooddeity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			bd.ID = int(value.Int64)
		case blooddeity.FieldVampireName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vampire_name", values[i])
			} else if value.Valid {
				bd.VampireName = value.String
			}
		case blooddeity.FieldBloodAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field blood_amount", values[i])
			} else if value.Valid {
				bd.BloodAmount = value.Int64
			}
		case blooddeity.FieldLastUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated", values[i])
			} else if value.Valid {
				bd.LastUpdated = value.Time
			}
		case blooddeity.FieldReporterUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_username", values[i])
			} else if value.Valid {
				bd.ReporterUsername = value.String
			}
		case blooddeity.FieldReporterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_id", values[i])
			} else if value.Valid {
				bd.ReporterID = int(value.Int64)
			}
		default:
			bd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BloodDeity.
// This includes values selected through modifiers, order, etc.
func (bd *BloodDeity) Value(name string) (ent.Value, error) {
	return bd.selectValues.Get(name)
}

// QueryReporter queries the "reporter" edge of the BloodDeity entity.
func (bd *BloodDeity) QueryReporter() *UserQuery {
	return NewBloodDeityClient(bd.config).QueryReporter(bd)
}

// Update returns a builder for updating this BloodDeity.
// Note that you need to call BloodDeity.Unwrap() before calling this method if this BloodDeity
// was returned from a transaction, and the transaction was committed or rolled back.
func (bd *BloodDeity) Update() *BloodDeityUpdateOne {
	return NewBloodDeityClient(bd.config).UpdateOne(bd)
}

// Unwrap unwraps the BloodDeity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bd *BloodDeity) Unwrap() *BloodDeity {
	_tx, ok := bd.config.driver.(*txDriver)
	if !ok {
		panic("ent: BloodDeity is not a transactional entity")
	}
	bd.config.driver = _tx.drv
	return bd
}

// String implements the fmt.Stringer.
func (bd *BloodDeity) String() string {
	var builder strings.Builder
	builder.WriteString("BloodDeity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bd.ID))
	builder.WriteString("vampire_name=")
	builder.WriteString(bd.VampireName)
	builder.WriteString(", ")
	builder.WriteString("blood_amount=")
	builder.WriteString(fmt.Sprintf("%v", bd.BloodAmount))
	builder.WriteString(", ")
	builder.WriteString("last_updated=")
	builder.WriteString(bd.LastUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reporter_username=")
	builder.WriteString(bd.ReporterUsername)
	builder.WriteString(", ")
	builder.WriteString("reporter_id=")
	builder.WriteString(fmt.Sprintf("%v", bd.ReporterID))
	builder.WriteByte(')')
	return builder.String()
}

// BloodDeities is a parsable slice of BloodDeity.
type BloodDeities []*BloodDeity
