// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// BloodDeityQuery is the builder for querying BloodDeity entities.
type BloodDeityQuery struct {
	config
	ctx          *QueryContext
	order        []blooddeity.OrderOption
	inters       []Interceptor
	predicates   []predicate.BloodDeity
	withReporter *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BloodDeityQuery builder.
func (bdq *BloodDeityQuery) Where(ps ...predicate.BloodDeity) *BloodDeityQuery {
	bdq.predicates = append(bdq.predicates, ps...)
	return bdq
}

// Limit the number of records to be returned by this query.
func (bdq *BloodDeityQuery) Limit(limit int) *BloodDeityQuery {
	bdq.ctx.Limit = &limit
	return bdq
}

// Offset to start from.
func (bdq *BloodDeityQuery) Offset(offset int) *BloodDeityQuery {
	bdq.ctx.Offset = &offset
	return bdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bdq *BloodDeityQuery) Unique(unique bool) *BloodDeityQuery {
	bdq.ctx.Unique = &unique
	return bdq
}

// Order specifies how the records should be ordered.
func (bdq *BloodDeityQuery) Order(o ...blooddeity.OrderOption) *BloodDeityQuery {
	bdq.order = append(bdq.order, o...)
	return bdq
}

// QueryReporter chains the current query on the "reporter" edge.
func (bdq *BloodDeityQuery) QueryReporter() *UserQuery {
	query := (&UserClient{config: bdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blooddeity.Table, blooddeity.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blooddeity.ReporterTable, blooddeity.ReporterColumn),
		)
		fromU = sqlgraph.SetNeighbors(bdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BloodDeity entity from the query.
// Returns a *NotFoundError when no BloodDeity was found.
func (bdq *BloodDeityQuery) First(ctx context.Context) (*BloodDeity, error) {
	nodes, err := bdq.Limit(1).All(setContextOp(ctx, bdq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blooddeity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bdq *BloodDeityQuery) FirstX(ctx context.Context) *BloodDeity {
	node, err := bdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BloodDeity ID from the query.
// Returns a *NotFoundError when no BloodDeity ID was found.
func (bdq *BloodDeityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdq.Limit(1).IDs(setContextOp(ctx, bdq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blooddeity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bdq *BloodDeityQuery) FirstIDX(ctx context.Context) int {
	id, err := bdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BloodDeity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BloodDeity entity is found.
// Returns a *NotFoundError when no BloodDeity entities are found.
func (bdq *BloodDeityQuery) Only(ctx context.Context) (*BloodDeity, error) {
	nodes, err := bdq.Limit(2).All(setContextOp(ctx, bdq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blooddeity.Label}
	default:
		return nil, &NotSingularError{blooddeity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bdq *BloodDeityQuery) OnlyX(ctx context.Context) *BloodDeity {
	node, err := bdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BloodDeity ID in the query.
// Returns a *NotSingularError when more than one BloodDeity ID is found.
// Returns a *NotFoundError when no entities are found.
func (bdq *BloodDeityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdq.Limit(2).IDs(setContextOp(ctx, bdq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blooddeity.Label}
	default:
		err = &NotSingularError{blooddeity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bdq *BloodDeityQuery) OnlyIDX(ctx context.Context) int {
	id, err := bdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BloodDeities.
func (bdq *BloodDeityQuery) All(ctx context.Context) ([]*BloodDeity, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryAll)
	if err := bdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BloodDeity, *BloodDeityQuery]()
	return withInterceptors[[]*BloodDeity](ctx, bdq, qr, bdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bdq *BloodDeityQuery) AllX(ctx context.Context) []*BloodDeity {
	nodes, err := bdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BloodDeity IDs.
func (bdq *BloodDeityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bdq.ctx.Unique == nil && bdq.path != nil {
		bdq.Unique(true)
	}
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryIDs)
	if err = bdq.Select(blooddeity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bdq *BloodDeityQuery) IDsX(ctx context.Context) []int {
	ids, err := bdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bdq *BloodDeityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryCount)
	if err := bdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bdq, querierCount[*BloodDeityQuery](), bdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bdq *BloodDeityQuery) CountX(ctx context.Context) int {
	count, err := bdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bdq *BloodDeityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bdq.ctx, ent.OpQueryExist)
	switch _, err := bdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bdq *BloodDeityQuery) ExistX(ctx context.Context) bool {
	exist, err := bdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BloodDeityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bdq *BloodDeityQuery) Clone() *BloodDeityQuery {
	if bdq == nil {
		return nil
	}
	return &BloodDeityQuery{
		config:       bdq.config,
		ctx:          bdq.ctx.Clone(),
		order:        append([]blooddeity.OrderOption{}, bdq.order...),
		inters:       append([]Interceptor{}, bdq.inters...),
		predicates:   append([]predicate.BloodDeity{}, bdq.predicates...),
		withReporter: bdq.withReporter.Clone(),
		// clone intermediate query.
		sql:  bdq.sql.Clone(),
		path: bdq.path,
	}
}

// WithReporter tells the query-builder to eager-load the nodes that are connected to
// the "reporter" edge. The optional arguments are used to configure the query builder of the edge.
func (bdq *BloodDeityQuery) WithReporter(opts ...func(*UserQuery)) *BloodDeityQuery {
	query := (&UserClient{config: bdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdq.withReporter = query
	return bdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VampireName string `json:"vampire_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BloodDeity.Query().
//		GroupBy(blooddeity.FieldVampireName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bdq *BloodDeityQuery) GroupBy(field string, fields ...string) *BloodDeityGroupBy {
	bdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BloodDeityGroupBy{build: bdq}
	grbuild.flds = &bdq.ctx.Fields
	grbuild.label = blooddeity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VampireName string `json:"vampire_name,omitempty"`
//	}
//
//	client.BloodDeity.Query().
//		Select(blooddeity.FieldVampireName).
//		Scan(ctx, &v)
func (bdq *BloodDeityQuery) Select(fields ...string) *BloodDeitySelect {
	bdq.ctx.Fields = append(bdq.ctx.Fields, fields...)
	sbuild := &BloodDeitySelect{BloodDeityQuery: bdq}
	sbuild.label = blooddeity.Label
	sbuild.flds, sbuild.scan = &bdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BloodDeitySelect configured with the given aggregations.
func (bdq *BloodDeityQuery) Aggregate(fns ...AggregateFunc) *BloodDeitySelect {
	return bdq.Select().Aggregate(fns...)
}

func (bdq *BloodDeityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bdq); err != nil {
				return err
			}
		}
	}
	for _, f := range bdq.ctx.Fields {
		if !blooddeity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bdq.path != nil {
		prev, err := bdq.path(ctx)
		if err != nil {
			return err
		}
		bdq.sql = prev
	}
	return nil
}

func (bdq *BloodDeityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BloodDeity, error) {
	var (
		nodes       = []*BloodDeity{}
		_spec       = bdq.querySpec()
		loadedTypes = [1]bool{
			bdq.withReporter != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BloodDeity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BloodDeity{config: bdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bdq.withReporter; query != nil {
		if err := bdq.loadReporter(ctx, query, nodes, nil,
			func(n *BloodDeity, e *User) { n.Edges.Reporter = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bdq *BloodDeityQuery) loadReporter(ctx context.Context, query *UserQuery, nodes []*BloodDeity, init func(*BloodDeity), assign func(*BloodDeity, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BloodDeity)
	for i := range nodes {
		fk := nodes[i].ReporterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reporter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bdq *BloodDeityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bdq.querySpec()
	_spec.Node.Columns = bdq.ctx.Fields
	if len(bdq.ctx.Fields) > 0 {
		_spec.Unique = bdq.ctx.Unique != nil && *bdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bdq.driver, _spec)
}

func (bdq *BloodDeityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blooddeity.Table, blooddeity.Columns, sqlgraph.NewFieldSpec(blooddeity.FieldID, field.TypeInt))
	_spec.From = bdq.sql
	if unique := bdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bdq.path != nil {
		_spec.Unique = true
	}
	if fields := bdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blooddeity.FieldID)
		for i := range fields {
			if fields[i] != blooddeity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bdq.withReporter != nil {
			_spec.Node.AddColumnOnce(blooddeity.FieldReporterID)
		}
	}
	if ps := bdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bdq *BloodDeityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bdq.driver.Dialect())
	t1 := builder.Table(blooddeity.Table)
	columns := bdq.ctx.Fields
	if len(columns) == 0 {
		columns = blooddeity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bdq.sql != nil {
		selector = bdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bdq.ctx.Unique != nil && *bdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bdq.predicates {
		p(selector)
	}
	for _, p := range bdq.order {
		p(selector)
	}
	if offset := bdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BloodDeityGroupBy is the group-by builder for BloodDeity entities.
type BloodDeityGroupBy struct {
	selector
	build *BloodDeityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bdgb *BloodDeityGroupBy) Aggregate(fns ...AggregateFunc) *BloodDeityGroupBy {
	bdgb.fns = append(bdgb.fns, fns...)
	return bdgb
}

// Scan applies the selector query and scans the result into the given value.
func (bdgb *BloodDeityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bdgb.build.ctx, ent.OpQueryGroupBy)
	if err := bdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BloodDeityQuery, *BloodDeityGroupBy](ctx, bdgb.build, bdgb, bdgb.build.inters, v)
}

func (bdgb *BloodDeityGroupBy) sqlScan(ctx context.Context, root *BloodDeityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bdgb.fns))
	for _, fn := range bdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bdgb.flds)+len(bdgb.fns))
		for _, f := range *bdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BloodDeitySelect is the builder for selecting fields of BloodDeity entities.
type BloodDeitySelect struct {
	*BloodDeityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bds *BloodDeitySelect) Aggregate(fns ...AggregateFunc) *BloodDeitySelect {
	bds.fns = append(bds.fns, fns...)
	return bds
}

// Scan applies the selector query and scans the result into the given value.
func (bds *BloodDeitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bds.ctx, ent.OpQuerySelect)
	if err := bds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BloodDeityQuery, *BloodDeitySelect](ctx, bds.BloodDeityQuery, bds, bds.inters, v)
}

func (bds *BloodDeitySelect) sqlScan(ctx context.Context, root *BloodDeityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bds.fns))
	for _, fn := range bds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
