// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/mikestefanello/pagoda/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BloodDeity is the client for interacting with the BloodDeity builders.
	BloodDeity *BloodDeityClient
	// LocationReport is the client for interacting with the LocationReport builders.
	LocationReport *LocationReportClient
	// PasswordToken is the client for interacting with the PasswordToken builders.
	PasswordToken *PasswordTokenClient
	// RichVampire is the client for interacting with the RichVampire builders.
	RichVampire *RichVampireClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BloodDeity = NewBloodDeityClient(c.config)
	c.LocationReport = NewLocationReportClient(c.config)
	c.PasswordToken = NewPasswordTokenClient(c.config)
	c.RichVampire = NewRichVampireClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		BloodDeity:     NewBloodDeityClient(cfg),
		LocationReport: NewLocationReportClient(cfg),
		PasswordToken:  NewPasswordTokenClient(cfg),
		RichVampire:    NewRichVampireClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		BloodDeity:     NewBloodDeityClient(cfg),
		LocationReport: NewLocationReportClient(cfg),
		PasswordToken:  NewPasswordTokenClient(cfg),
		RichVampire:    NewRichVampireClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BloodDeity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.BloodDeity.Use(hooks...)
	c.LocationReport.Use(hooks...)
	c.PasswordToken.Use(hooks...)
	c.RichVampire.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.BloodDeity.Intercept(interceptors...)
	c.LocationReport.Intercept(interceptors...)
	c.PasswordToken.Intercept(interceptors...)
	c.RichVampire.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BloodDeityMutation:
		return c.BloodDeity.mutate(ctx, m)
	case *LocationReportMutation:
		return c.LocationReport.mutate(ctx, m)
	case *PasswordTokenMutation:
		return c.PasswordToken.mutate(ctx, m)
	case *RichVampireMutation:
		return c.RichVampire.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BloodDeityClient is a client for the BloodDeity schema.
type BloodDeityClient struct {
	config
}

// NewBloodDeityClient returns a client for the BloodDeity from the given config.
func NewBloodDeityClient(c config) *BloodDeityClient {
	return &BloodDeityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `blooddeity.Hooks(f(g(h())))`.
func (c *BloodDeityClient) Use(hooks ...Hook) {
	c.hooks.BloodDeity = append(c.hooks.BloodDeity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `blooddeity.Intercept(f(g(h())))`.
func (c *BloodDeityClient) Intercept(interceptors ...Interceptor) {
	c.inters.BloodDeity = append(c.inters.BloodDeity, interceptors...)
}

// Create returns a builder for creating a BloodDeity entity.
func (c *BloodDeityClient) Create() *BloodDeityCreate {
	mutation := newBloodDeityMutation(c.config, OpCreate)
	return &BloodDeityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BloodDeity entities.
func (c *BloodDeityClient) CreateBulk(builders ...*BloodDeityCreate) *BloodDeityCreateBulk {
	return &BloodDeityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BloodDeityClient) MapCreateBulk(slice any, setFunc func(*BloodDeityCreate, int)) *BloodDeityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BloodDeityCreateBulk{err: fmt.Errorf("calling to BloodDeityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BloodDeityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BloodDeityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BloodDeity.
func (c *BloodDeityClient) Update() *BloodDeityUpdate {
	mutation := newBloodDeityMutation(c.config, OpUpdate)
	return &BloodDeityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BloodDeityClient) UpdateOne(bd *BloodDeity) *BloodDeityUpdateOne {
	mutation := newBloodDeityMutation(c.config, OpUpdateOne, withBloodDeity(bd))
	return &BloodDeityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BloodDeityClient) UpdateOneID(id int) *BloodDeityUpdateOne {
	mutation := newBloodDeityMutation(c.config, OpUpdateOne, withBloodDeityID(id))
	return &BloodDeityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BloodDeity.
func (c *BloodDeityClient) Delete() *BloodDeityDelete {
	mutation := newBloodDeityMutation(c.config, OpDelete)
	return &BloodDeityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BloodDeityClient) DeleteOne(bd *BloodDeity) *BloodDeityDeleteOne {
	return c.DeleteOneID(bd.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BloodDeityClient) DeleteOneID(id int) *BloodDeityDeleteOne {
	builder := c.Delete().Where(blooddeity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BloodDeityDeleteOne{builder}
}

// Query returns a query builder for BloodDeity.
func (c *BloodDeityClient) Query() *BloodDeityQuery {
	return &BloodDeityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBloodDeity},
		inters: c.Interceptors(),
	}
}

// Get returns a BloodDeity entity by its id.
func (c *BloodDeityClient) Get(ctx context.Context, id int) (*BloodDeity, error) {
	return c.Query().Where(blooddeity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BloodDeityClient) GetX(ctx context.Context, id int) *BloodDeity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReporter queries the reporter edge of a BloodDeity.
func (c *BloodDeityClient) QueryReporter(bd *BloodDeity) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := bd.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blooddeity.Table, blooddeity.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blooddeity.ReporterTable, blooddeity.ReporterColumn),
		)
		fromV = sqlgraph.Neighbors(bd.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BloodDeityClient) Hooks() []Hook {
	return c.hooks.BloodDeity
}

// Interceptors returns the client interceptors.
func (c *BloodDeityClient) Interceptors() []Interceptor {
	return c.inters.BloodDeity
}

func (c *BloodDeityClient) mutate(ctx context.Context, m *BloodDeityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BloodDeityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BloodDeityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BloodDeityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BloodDeityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BloodDeity mutation op: %q", m.Op())
	}
}

// LocationReportClient is a client for the LocationReport schema.
type LocationReportClient struct {
	config
}

// NewLocationReportClient returns a client for the LocationReport from the given config.
func NewLocationReportClient(c config) *LocationReportClient {
	return &LocationReportClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `locationreport.Hooks(f(g(h())))`.
func (c *LocationReportClient) Use(hooks ...Hook) {
	c.hooks.LocationReport = append(c.hooks.LocationReport, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `locationreport.Intercept(f(g(h())))`.
func (c *LocationReportClient) Intercept(interceptors ...Interceptor) {
	c.inters.LocationReport = append(c.inters.LocationReport, interceptors...)
}

// Create returns a builder for creating a LocationReport entity.
func (c *LocationReportClient) Create() *LocationReportCreate {
	mutation := newLocationReportMutation(c.config, OpCreate)
	return &LocationReportCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LocationReport entities.
func (c *LocationReportClient) CreateBulk(builders ...*LocationReportCreate) *LocationReportCreateBulk {
	return &LocationReportCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LocationReportClient) MapCreateBulk(slice any, setFunc func(*LocationReportCreate, int)) *LocationReportCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LocationReportCreateBulk{err: fmt.Errorf("calling to LocationReportClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LocationReportCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LocationReportCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LocationReport.
func (c *LocationReportClient) Update() *LocationReportUpdate {
	mutation := newLocationReportMutation(c.config, OpUpdate)
	return &LocationReportUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LocationReportClient) UpdateOne(lr *LocationReport) *LocationReportUpdateOne {
	mutation := newLocationReportMutation(c.config, OpUpdateOne, withLocationReport(lr))
	return &LocationReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LocationReportClient) UpdateOneID(id int) *LocationReportUpdateOne {
	mutation := newLocationReportMutation(c.config, OpUpdateOne, withLocationReportID(id))
	return &LocationReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LocationReport.
func (c *LocationReportClient) Delete() *LocationReportDelete {
	mutation := newLocationReportMutation(c.config, OpDelete)
	return &LocationReportDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LocationReportClient) DeleteOne(lr *LocationReport) *LocationReportDeleteOne {
	return c.DeleteOneID(lr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LocationReportClient) DeleteOneID(id int) *LocationReportDeleteOne {
	builder := c.Delete().Where(locationreport.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LocationReportDeleteOne{builder}
}

// Query returns a query builder for LocationReport.
func (c *LocationReportClient) Query() *LocationReportQuery {
	return &LocationReportQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLocationReport},
		inters: c.Interceptors(),
	}
}

// Get returns a LocationReport entity by its id.
func (c *LocationReportClient) Get(ctx context.Context, id int) (*LocationReport, error) {
	return c.Query().Where(locationreport.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LocationReportClient) GetX(ctx context.Context, id int) *LocationReport {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReporter queries the reporter edge of a LocationReport.
func (c *LocationReportClient) QueryReporter(lr *LocationReport) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := lr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(locationreport.Table, locationreport.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, locationreport.ReporterTable, locationreport.ReporterColumn),
		)
		fromV = sqlgraph.Neighbors(lr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LocationReportClient) Hooks() []Hook {
	return c.hooks.LocationReport
}

// Interceptors returns the client interceptors.
func (c *LocationReportClient) Interceptors() []Interceptor {
	return c.inters.LocationReport
}

func (c *LocationReportClient) mutate(ctx context.Context, m *LocationReportMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LocationReportCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LocationReportUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LocationReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LocationReportDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LocationReport mutation op: %q", m.Op())
	}
}

// PasswordTokenClient is a client for the PasswordToken schema.
type PasswordTokenClient struct {
	config
}

// NewPasswordTokenClient returns a client for the PasswordToken from the given config.
func NewPasswordTokenClient(c config) *PasswordTokenClient {
	return &PasswordTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passwordtoken.Hooks(f(g(h())))`.
func (c *PasswordTokenClient) Use(hooks ...Hook) {
	c.hooks.PasswordToken = append(c.hooks.PasswordToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passwordtoken.Intercept(f(g(h())))`.
func (c *PasswordTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.PasswordToken = append(c.inters.PasswordToken, interceptors...)
}

// Create returns a builder for creating a PasswordToken entity.
func (c *PasswordTokenClient) Create() *PasswordTokenCreate {
	mutation := newPasswordTokenMutation(c.config, OpCreate)
	return &PasswordTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasswordToken entities.
func (c *PasswordTokenClient) CreateBulk(builders ...*PasswordTokenCreate) *PasswordTokenCreateBulk {
	return &PasswordTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PasswordTokenClient) MapCreateBulk(slice any, setFunc func(*PasswordTokenCreate, int)) *PasswordTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PasswordTokenCreateBulk{err: fmt.Errorf("calling to PasswordTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PasswordTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PasswordTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasswordToken.
func (c *PasswordTokenClient) Update() *PasswordTokenUpdate {
	mutation := newPasswordTokenMutation(c.config, OpUpdate)
	return &PasswordTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasswordTokenClient) UpdateOne(pt *PasswordToken) *PasswordTokenUpdateOne {
	mutation := newPasswordTokenMutation(c.config, OpUpdateOne, withPasswordToken(pt))
	return &PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasswordTokenClient) UpdateOneID(id int) *PasswordTokenUpdateOne {
	mutation := newPasswordTokenMutation(c.config, OpUpdateOne, withPasswordTokenID(id))
	return &PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasswordToken.
func (c *PasswordTokenClient) Delete() *PasswordTokenDelete {
	mutation := newPasswordTokenMutation(c.config, OpDelete)
	return &PasswordTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasswordTokenClient) DeleteOne(pt *PasswordToken) *PasswordTokenDeleteOne {
	return c.DeleteOneID(pt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasswordTokenClient) DeleteOneID(id int) *PasswordTokenDeleteOne {
	builder := c.Delete().Where(passwordtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasswordTokenDeleteOne{builder}
}

// Query returns a query builder for PasswordToken.
func (c *PasswordTokenClient) Query() *PasswordTokenQuery {
	return &PasswordTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePasswordToken},
		inters: c.Interceptors(),
	}
}

// Get returns a PasswordToken entity by its id.
func (c *PasswordTokenClient) Get(ctx context.Context, id int) (*PasswordToken, error) {
	return c.Query().Where(passwordtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasswordTokenClient) GetX(ctx context.Context, id int) *PasswordToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a PasswordToken.
func (c *PasswordTokenClient) QueryUser(pt *PasswordToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pt.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(passwordtoken.Table, passwordtoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, passwordtoken.UserTable, passwordtoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(pt.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PasswordTokenClient) Hooks() []Hook {
	hooks := c.hooks.PasswordToken
	return append(hooks[:len(hooks):len(hooks)], passwordtoken.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *PasswordTokenClient) Interceptors() []Interceptor {
	return c.inters.PasswordToken
}

func (c *PasswordTokenClient) mutate(ctx context.Context, m *PasswordTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PasswordTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PasswordTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PasswordTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PasswordToken mutation op: %q", m.Op())
	}
}

// RichVampireClient is a client for the RichVampire schema.
type RichVampireClient struct {
	config
}

// NewRichVampireClient returns a client for the RichVampire from the given config.
func NewRichVampireClient(c config) *RichVampireClient {
	return &RichVampireClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `richvampire.Hooks(f(g(h())))`.
func (c *RichVampireClient) Use(hooks ...Hook) {
	c.hooks.RichVampire = append(c.hooks.RichVampire, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `richvampire.Intercept(f(g(h())))`.
func (c *RichVampireClient) Intercept(interceptors ...Interceptor) {
	c.inters.RichVampire = append(c.inters.RichVampire, interceptors...)
}

// Create returns a builder for creating a RichVampire entity.
func (c *RichVampireClient) Create() *RichVampireCreate {
	mutation := newRichVampireMutation(c.config, OpCreate)
	return &RichVampireCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RichVampire entities.
func (c *RichVampireClient) CreateBulk(builders ...*RichVampireCreate) *RichVampireCreateBulk {
	return &RichVampireCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RichVampireClient) MapCreateBulk(slice any, setFunc func(*RichVampireCreate, int)) *RichVampireCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RichVampireCreateBulk{err: fmt.Errorf("calling to RichVampireClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RichVampireCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RichVampireCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RichVampire.
func (c *RichVampireClient) Update() *RichVampireUpdate {
	mutation := newRichVampireMutation(c.config, OpUpdate)
	return &RichVampireUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RichVampireClient) UpdateOne(rv *RichVampire) *RichVampireUpdateOne {
	mutation := newRichVampireMutation(c.config, OpUpdateOne, withRichVampire(rv))
	return &RichVampireUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RichVampireClient) UpdateOneID(id int) *RichVampireUpdateOne {
	mutation := newRichVampireMutation(c.config, OpUpdateOne, withRichVampireID(id))
	return &RichVampireUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RichVampire.
func (c *RichVampireClient) Delete() *RichVampireDelete {
	mutation := newRichVampireMutation(c.config, OpDelete)
	return &RichVampireDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RichVampireClient) DeleteOne(rv *RichVampire) *RichVampireDeleteOne {
	return c.DeleteOneID(rv.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RichVampireClient) DeleteOneID(id int) *RichVampireDeleteOne {
	builder := c.Delete().Where(richvampire.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RichVampireDeleteOne{builder}
}

// Query returns a query builder for RichVampire.
func (c *RichVampireClient) Query() *RichVampireQuery {
	return &RichVampireQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRichVampire},
		inters: c.Interceptors(),
	}
}

// Get returns a RichVampire entity by its id.
func (c *RichVampireClient) Get(ctx context.Context, id int) (*RichVampire, error) {
	return c.Query().Where(richvampire.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RichVampireClient) GetX(ctx context.Context, id int) *RichVampire {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryReporter queries the reporter edge of a RichVampire.
func (c *RichVampireClient) QueryReporter(rv *RichVampire) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rv.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(richvampire.Table, richvampire.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, richvampire.ReporterTable, richvampire.ReporterColumn),
		)
		fromV = sqlgraph.Neighbors(rv.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RichVampireClient) Hooks() []Hook {
	return c.hooks.RichVampire
}

// Interceptors returns the client interceptors.
func (c *RichVampireClient) Interceptors() []Interceptor {
	return c.inters.RichVampire
}

func (c *RichVampireClient) mutate(ctx context.Context, m *RichVampireMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RichVampireCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RichVampireUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RichVampireUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RichVampireDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RichVampire mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a User.
func (c *UserClient) QueryOwner(u *User) *PasswordTokenQuery {
	query := (&PasswordTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(passwordtoken.Table, passwordtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.OwnerTable, user.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLocationReports queries the location_reports edge of a User.
func (c *UserClient) QueryLocationReports(u *User) *LocationReportQuery {
	query := (&LocationReportClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(locationreport.Table, locationreport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.LocationReportsTable, user.LocationReportsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBloodDeityReports queries the blood_deity_reports edge of a User.
func (c *UserClient) QueryBloodDeityReports(u *User) *BloodDeityQuery {
	query := (&BloodDeityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(blooddeity.Table, blooddeity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.BloodDeityReportsTable, user.BloodDeityReportsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRichVampireReports queries the rich_vampire_reports edge of a User.
func (c *UserClient) QueryRichVampireReports(u *User) *RichVampireQuery {
	query := (&RichVampireClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(richvampire.Table, richvampire.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.RichVampireReportsTable, user.RichVampireReportsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BloodDeity, LocationReport, PasswordToken, RichVampire, User []ent.Hook
	}
	inters struct {
		BloodDeity, LocationReport, PasswordToken, RichVampire, User []ent.Interceptor
	}
)
