// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// LocationReportUpdate is the builder for updating LocationReport entities.
type LocationReportUpdate struct {
	config
	hooks    []Hook
	mutation *LocationReportMutation
}

// Where appends a list predicates to the LocationReportUpdate builder.
func (lru *LocationReportUpdate) Where(ps ...predicate.LocationReport) *LocationReportUpdate {
	lru.mutation.Where(ps...)
	return lru
}

// SetBuildingName sets the "building_name" field.
func (lru *LocationReportUpdate) SetBuildingName(s string) *LocationReportUpdate {
	lru.mutation.SetBuildingName(s)
	return lru
}

// SetNillableBuildingName sets the "building_name" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableBuildingName(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetBuildingName(*s)
	}
	return lru
}

// SetBuildingType sets the "building_type" field.
func (lru *LocationReportUpdate) SetBuildingType(lt locationreport.BuildingType) *LocationReportUpdate {
	lru.mutation.SetBuildingType(lt)
	return lru
}

// SetNillableBuildingType sets the "building_type" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableBuildingType(lt *locationreport.BuildingType) *LocationReportUpdate {
	if lt != nil {
		lru.SetBuildingType(*lt)
	}
	return lru
}

// SetCustomItemName sets the "custom_item_name" field.
func (lru *LocationReportUpdate) SetCustomItemName(s string) *LocationReportUpdate {
	lru.mutation.SetCustomItemName(s)
	return lru
}

// SetNillableCustomItemName sets the "custom_item_name" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableCustomItemName(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetCustomItemName(*s)
	}
	return lru
}

// ClearCustomItemName clears the value of the "custom_item_name" field.
func (lru *LocationReportUpdate) ClearCustomItemName() *LocationReportUpdate {
	lru.mutation.ClearCustomItemName()
	return lru
}

// SetCoordinateX sets the "coordinate_x" field.
func (lru *LocationReportUpdate) SetCoordinateX(i int) *LocationReportUpdate {
	lru.mutation.ResetCoordinateX()
	lru.mutation.SetCoordinateX(i)
	return lru
}

// SetNillableCoordinateX sets the "coordinate_x" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableCoordinateX(i *int) *LocationReportUpdate {
	if i != nil {
		lru.SetCoordinateX(*i)
	}
	return lru
}

// AddCoordinateX adds i to the "coordinate_x" field.
func (lru *LocationReportUpdate) AddCoordinateX(i int) *LocationReportUpdate {
	lru.mutation.AddCoordinateX(i)
	return lru
}

// ClearCoordinateX clears the value of the "coordinate_x" field.
func (lru *LocationReportUpdate) ClearCoordinateX() *LocationReportUpdate {
	lru.mutation.ClearCoordinateX()
	return lru
}

// SetCoordinateY sets the "coordinate_y" field.
func (lru *LocationReportUpdate) SetCoordinateY(i int) *LocationReportUpdate {
	lru.mutation.ResetCoordinateY()
	lru.mutation.SetCoordinateY(i)
	return lru
}

// SetNillableCoordinateY sets the "coordinate_y" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableCoordinateY(i *int) *LocationReportUpdate {
	if i != nil {
		lru.SetCoordinateY(*i)
	}
	return lru
}

// AddCoordinateY adds i to the "coordinate_y" field.
func (lru *LocationReportUpdate) AddCoordinateY(i int) *LocationReportUpdate {
	lru.mutation.AddCoordinateY(i)
	return lru
}

// ClearCoordinateY clears the value of the "coordinate_y" field.
func (lru *LocationReportUpdate) ClearCoordinateY() *LocationReportUpdate {
	lru.mutation.ClearCoordinateY()
	return lru
}

// SetStreetName sets the "street_name" field.
func (lru *LocationReportUpdate) SetStreetName(s string) *LocationReportUpdate {
	lru.mutation.SetStreetName(s)
	return lru
}

// SetNillableStreetName sets the "street_name" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableStreetName(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetStreetName(*s)
	}
	return lru
}

// ClearStreetName clears the value of the "street_name" field.
func (lru *LocationReportUpdate) ClearStreetName() *LocationReportUpdate {
	lru.mutation.ClearStreetName()
	return lru
}

// SetStreetNumber sets the "street_number" field.
func (lru *LocationReportUpdate) SetStreetNumber(s string) *LocationReportUpdate {
	lru.mutation.SetStreetNumber(s)
	return lru
}

// SetNillableStreetNumber sets the "street_number" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableStreetNumber(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetStreetNumber(*s)
	}
	return lru
}

// ClearStreetNumber clears the value of the "street_number" field.
func (lru *LocationReportUpdate) ClearStreetNumber() *LocationReportUpdate {
	lru.mutation.ClearStreetNumber()
	return lru
}

// SetGuildLevel sets the "guild_level" field.
func (lru *LocationReportUpdate) SetGuildLevel(i int) *LocationReportUpdate {
	lru.mutation.ResetGuildLevel()
	lru.mutation.SetGuildLevel(i)
	return lru
}

// SetNillableGuildLevel sets the "guild_level" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableGuildLevel(i *int) *LocationReportUpdate {
	if i != nil {
		lru.SetGuildLevel(*i)
	}
	return lru
}

// AddGuildLevel adds i to the "guild_level" field.
func (lru *LocationReportUpdate) AddGuildLevel(i int) *LocationReportUpdate {
	lru.mutation.AddGuildLevel(i)
	return lru
}

// ClearGuildLevel clears the value of the "guild_level" field.
func (lru *LocationReportUpdate) ClearGuildLevel() *LocationReportUpdate {
	lru.mutation.ClearGuildLevel()
	return lru
}

// SetReporterUsername sets the "reporter_username" field.
func (lru *LocationReportUpdate) SetReporterUsername(s string) *LocationReportUpdate {
	lru.mutation.SetReporterUsername(s)
	return lru
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableReporterUsername(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetReporterUsername(*s)
	}
	return lru
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (lru *LocationReportUpdate) ClearReporterUsername() *LocationReportUpdate {
	lru.mutation.ClearReporterUsername()
	return lru
}

// SetReporterID sets the "reporter_id" field.
func (lru *LocationReportUpdate) SetReporterID(i int) *LocationReportUpdate {
	lru.mutation.SetReporterID(i)
	return lru
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableReporterID(i *int) *LocationReportUpdate {
	if i != nil {
		lru.SetReporterID(*i)
	}
	return lru
}

// ClearReporterID clears the value of the "reporter_id" field.
func (lru *LocationReportUpdate) ClearReporterID() *LocationReportUpdate {
	lru.mutation.ClearReporterID()
	return lru
}

// SetConfidence sets the "confidence" field.
func (lru *LocationReportUpdate) SetConfidence(l locationreport.Confidence) *LocationReportUpdate {
	lru.mutation.SetConfidence(l)
	return lru
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableConfidence(l *locationreport.Confidence) *LocationReportUpdate {
	if l != nil {
		lru.SetConfidence(*l)
	}
	return lru
}

// SetNotes sets the "notes" field.
func (lru *LocationReportUpdate) SetNotes(s string) *LocationReportUpdate {
	lru.mutation.SetNotes(s)
	return lru
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableNotes(s *string) *LocationReportUpdate {
	if s != nil {
		lru.SetNotes(*s)
	}
	return lru
}

// ClearNotes clears the value of the "notes" field.
func (lru *LocationReportUpdate) ClearNotes() *LocationReportUpdate {
	lru.mutation.ClearNotes()
	return lru
}

// SetExpiresAt sets the "expires_at" field.
func (lru *LocationReportUpdate) SetExpiresAt(t time.Time) *LocationReportUpdate {
	lru.mutation.SetExpiresAt(t)
	return lru
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableExpiresAt(t *time.Time) *LocationReportUpdate {
	if t != nil {
		lru.SetExpiresAt(*t)
	}
	return lru
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (lru *LocationReportUpdate) ClearExpiresAt() *LocationReportUpdate {
	lru.mutation.ClearExpiresAt()
	return lru
}

// SetIsActive sets the "is_active" field.
func (lru *LocationReportUpdate) SetIsActive(b bool) *LocationReportUpdate {
	lru.mutation.SetIsActive(b)
	return lru
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (lru *LocationReportUpdate) SetNillableIsActive(b *bool) *LocationReportUpdate {
	if b != nil {
		lru.SetIsActive(*b)
	}
	return lru
}

// SetReporter sets the "reporter" edge to the User entity.
func (lru *LocationReportUpdate) SetReporter(u *User) *LocationReportUpdate {
	return lru.SetReporterID(u.ID)
}

// Mutation returns the LocationReportMutation object of the builder.
func (lru *LocationReportUpdate) Mutation() *LocationReportMutation {
	return lru.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (lru *LocationReportUpdate) ClearReporter() *LocationReportUpdate {
	lru.mutation.ClearReporter()
	return lru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lru *LocationReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lru.sqlSave, lru.mutation, lru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lru *LocationReportUpdate) SaveX(ctx context.Context) int {
	affected, err := lru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lru *LocationReportUpdate) Exec(ctx context.Context) error {
	_, err := lru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lru *LocationReportUpdate) ExecX(ctx context.Context) {
	if err := lru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lru *LocationReportUpdate) check() error {
	if v, ok := lru.mutation.BuildingName(); ok {
		if err := locationreport.BuildingNameValidator(v); err != nil {
			return &ValidationError{Name: "building_name", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_name": %w`, err)}
		}
	}
	if v, ok := lru.mutation.BuildingType(); ok {
		if err := locationreport.BuildingTypeValidator(v); err != nil {
			return &ValidationError{Name: "building_type", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_type": %w`, err)}
		}
	}
	if v, ok := lru.mutation.CoordinateX(); ok {
		if err := locationreport.CoordinateXValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_x", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_x": %w`, err)}
		}
	}
	if v, ok := lru.mutation.CoordinateY(); ok {
		if err := locationreport.CoordinateYValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_y", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_y": %w`, err)}
		}
	}
	if v, ok := lru.mutation.GuildLevel(); ok {
		if err := locationreport.GuildLevelValidator(v); err != nil {
			return &ValidationError{Name: "guild_level", err: fmt.Errorf(`ent: validator failed for field "LocationReport.guild_level": %w`, err)}
		}
	}
	if v, ok := lru.mutation.Confidence(); ok {
		if err := locationreport.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "LocationReport.confidence": %w`, err)}
		}
	}
	return nil
}

func (lru *LocationReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationreport.Table, locationreport.Columns, sqlgraph.NewFieldSpec(locationreport.FieldID, field.TypeInt))
	if ps := lru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lru.mutation.BuildingName(); ok {
		_spec.SetField(locationreport.FieldBuildingName, field.TypeString, value)
	}
	if value, ok := lru.mutation.BuildingType(); ok {
		_spec.SetField(locationreport.FieldBuildingType, field.TypeEnum, value)
	}
	if value, ok := lru.mutation.CustomItemName(); ok {
		_spec.SetField(locationreport.FieldCustomItemName, field.TypeString, value)
	}
	if lru.mutation.CustomItemNameCleared() {
		_spec.ClearField(locationreport.FieldCustomItemName, field.TypeString)
	}
	if value, ok := lru.mutation.CoordinateX(); ok {
		_spec.SetField(locationreport.FieldCoordinateX, field.TypeInt, value)
	}
	if value, ok := lru.mutation.AddedCoordinateX(); ok {
		_spec.AddField(locationreport.FieldCoordinateX, field.TypeInt, value)
	}
	if lru.mutation.CoordinateXCleared() {
		_spec.ClearField(locationreport.FieldCoordinateX, field.TypeInt)
	}
	if value, ok := lru.mutation.CoordinateY(); ok {
		_spec.SetField(locationreport.FieldCoordinateY, field.TypeInt, value)
	}
	if value, ok := lru.mutation.AddedCoordinateY(); ok {
		_spec.AddField(locationreport.FieldCoordinateY, field.TypeInt, value)
	}
	if lru.mutation.CoordinateYCleared() {
		_spec.ClearField(locationreport.FieldCoordinateY, field.TypeInt)
	}
	if value, ok := lru.mutation.StreetName(); ok {
		_spec.SetField(locationreport.FieldStreetName, field.TypeString, value)
	}
	if lru.mutation.StreetNameCleared() {
		_spec.ClearField(locationreport.FieldStreetName, field.TypeString)
	}
	if value, ok := lru.mutation.StreetNumber(); ok {
		_spec.SetField(locationreport.FieldStreetNumber, field.TypeString, value)
	}
	if lru.mutation.StreetNumberCleared() {
		_spec.ClearField(locationreport.FieldStreetNumber, field.TypeString)
	}
	if value, ok := lru.mutation.GuildLevel(); ok {
		_spec.SetField(locationreport.FieldGuildLevel, field.TypeInt, value)
	}
	if value, ok := lru.mutation.AddedGuildLevel(); ok {
		_spec.AddField(locationreport.FieldGuildLevel, field.TypeInt, value)
	}
	if lru.mutation.GuildLevelCleared() {
		_spec.ClearField(locationreport.FieldGuildLevel, field.TypeInt)
	}
	if value, ok := lru.mutation.ReporterUsername(); ok {
		_spec.SetField(locationreport.FieldReporterUsername, field.TypeString, value)
	}
	if lru.mutation.ReporterUsernameCleared() {
		_spec.ClearField(locationreport.FieldReporterUsername, field.TypeString)
	}
	if value, ok := lru.mutation.Confidence(); ok {
		_spec.SetField(locationreport.FieldConfidence, field.TypeEnum, value)
	}
	if value, ok := lru.mutation.Notes(); ok {
		_spec.SetField(locationreport.FieldNotes, field.TypeString, value)
	}
	if lru.mutation.NotesCleared() {
		_spec.ClearField(locationreport.FieldNotes, field.TypeString)
	}
	if value, ok := lru.mutation.ExpiresAt(); ok {
		_spec.SetField(locationreport.FieldExpiresAt, field.TypeTime, value)
	}
	if lru.mutation.ExpiresAtCleared() {
		_spec.ClearField(locationreport.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := lru.mutation.IsActive(); ok {
		_spec.SetField(locationreport.FieldIsActive, field.TypeBool, value)
	}
	if lru.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationreport.ReporterTable,
			Columns: []string{locationreport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lru.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationreport.ReporterTable,
			Columns: []string{locationreport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lru.mutation.done = true
	return n, nil
}

// LocationReportUpdateOne is the builder for updating a single LocationReport entity.
type LocationReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationReportMutation
}

// SetBuildingName sets the "building_name" field.
func (lruo *LocationReportUpdateOne) SetBuildingName(s string) *LocationReportUpdateOne {
	lruo.mutation.SetBuildingName(s)
	return lruo
}

// SetNillableBuildingName sets the "building_name" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableBuildingName(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetBuildingName(*s)
	}
	return lruo
}

// SetBuildingType sets the "building_type" field.
func (lruo *LocationReportUpdateOne) SetBuildingType(lt locationreport.BuildingType) *LocationReportUpdateOne {
	lruo.mutation.SetBuildingType(lt)
	return lruo
}

// SetNillableBuildingType sets the "building_type" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableBuildingType(lt *locationreport.BuildingType) *LocationReportUpdateOne {
	if lt != nil {
		lruo.SetBuildingType(*lt)
	}
	return lruo
}

// SetCustomItemName sets the "custom_item_name" field.
func (lruo *LocationReportUpdateOne) SetCustomItemName(s string) *LocationReportUpdateOne {
	lruo.mutation.SetCustomItemName(s)
	return lruo
}

// SetNillableCustomItemName sets the "custom_item_name" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableCustomItemName(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetCustomItemName(*s)
	}
	return lruo
}

// ClearCustomItemName clears the value of the "custom_item_name" field.
func (lruo *LocationReportUpdateOne) ClearCustomItemName() *LocationReportUpdateOne {
	lruo.mutation.ClearCustomItemName()
	return lruo
}

// SetCoordinateX sets the "coordinate_x" field.
func (lruo *LocationReportUpdateOne) SetCoordinateX(i int) *LocationReportUpdateOne {
	lruo.mutation.ResetCoordinateX()
	lruo.mutation.SetCoordinateX(i)
	return lruo
}

// SetNillableCoordinateX sets the "coordinate_x" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableCoordinateX(i *int) *LocationReportUpdateOne {
	if i != nil {
		lruo.SetCoordinateX(*i)
	}
	return lruo
}

// AddCoordinateX adds i to the "coordinate_x" field.
func (lruo *LocationReportUpdateOne) AddCoordinateX(i int) *LocationReportUpdateOne {
	lruo.mutation.AddCoordinateX(i)
	return lruo
}

// ClearCoordinateX clears the value of the "coordinate_x" field.
func (lruo *LocationReportUpdateOne) ClearCoordinateX() *LocationReportUpdateOne {
	lruo.mutation.ClearCoordinateX()
	return lruo
}

// SetCoordinateY sets the "coordinate_y" field.
func (lruo *LocationReportUpdateOne) SetCoordinateY(i int) *LocationReportUpdateOne {
	lruo.mutation.ResetCoordinateY()
	lruo.mutation.SetCoordinateY(i)
	return lruo
}

// SetNillableCoordinateY sets the "coordinate_y" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableCoordinateY(i *int) *LocationReportUpdateOne {
	if i != nil {
		lruo.SetCoordinateY(*i)
	}
	return lruo
}

// AddCoordinateY adds i to the "coordinate_y" field.
func (lruo *LocationReportUpdateOne) AddCoordinateY(i int) *LocationReportUpdateOne {
	lruo.mutation.AddCoordinateY(i)
	return lruo
}

// ClearCoordinateY clears the value of the "coordinate_y" field.
func (lruo *LocationReportUpdateOne) ClearCoordinateY() *LocationReportUpdateOne {
	lruo.mutation.ClearCoordinateY()
	return lruo
}

// SetStreetName sets the "street_name" field.
func (lruo *LocationReportUpdateOne) SetStreetName(s string) *LocationReportUpdateOne {
	lruo.mutation.SetStreetName(s)
	return lruo
}

// SetNillableStreetName sets the "street_name" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableStreetName(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetStreetName(*s)
	}
	return lruo
}

// ClearStreetName clears the value of the "street_name" field.
func (lruo *LocationReportUpdateOne) ClearStreetName() *LocationReportUpdateOne {
	lruo.mutation.ClearStreetName()
	return lruo
}

// SetStreetNumber sets the "street_number" field.
func (lruo *LocationReportUpdateOne) SetStreetNumber(s string) *LocationReportUpdateOne {
	lruo.mutation.SetStreetNumber(s)
	return lruo
}

// SetNillableStreetNumber sets the "street_number" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableStreetNumber(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetStreetNumber(*s)
	}
	return lruo
}

// ClearStreetNumber clears the value of the "street_number" field.
func (lruo *LocationReportUpdateOne) ClearStreetNumber() *LocationReportUpdateOne {
	lruo.mutation.ClearStreetNumber()
	return lruo
}

// SetGuildLevel sets the "guild_level" field.
func (lruo *LocationReportUpdateOne) SetGuildLevel(i int) *LocationReportUpdateOne {
	lruo.mutation.ResetGuildLevel()
	lruo.mutation.SetGuildLevel(i)
	return lruo
}

// SetNillableGuildLevel sets the "guild_level" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableGuildLevel(i *int) *LocationReportUpdateOne {
	if i != nil {
		lruo.SetGuildLevel(*i)
	}
	return lruo
}

// AddGuildLevel adds i to the "guild_level" field.
func (lruo *LocationReportUpdateOne) AddGuildLevel(i int) *LocationReportUpdateOne {
	lruo.mutation.AddGuildLevel(i)
	return lruo
}

// ClearGuildLevel clears the value of the "guild_level" field.
func (lruo *LocationReportUpdateOne) ClearGuildLevel() *LocationReportUpdateOne {
	lruo.mutation.ClearGuildLevel()
	return lruo
}

// SetReporterUsername sets the "reporter_username" field.
func (lruo *LocationReportUpdateOne) SetReporterUsername(s string) *LocationReportUpdateOne {
	lruo.mutation.SetReporterUsername(s)
	return lruo
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableReporterUsername(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetReporterUsername(*s)
	}
	return lruo
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (lruo *LocationReportUpdateOne) ClearReporterUsername() *LocationReportUpdateOne {
	lruo.mutation.ClearReporterUsername()
	return lruo
}

// SetReporterID sets the "reporter_id" field.
func (lruo *LocationReportUpdateOne) SetReporterID(i int) *LocationReportUpdateOne {
	lruo.mutation.SetReporterID(i)
	return lruo
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableReporterID(i *int) *LocationReportUpdateOne {
	if i != nil {
		lruo.SetReporterID(*i)
	}
	return lruo
}

// ClearReporterID clears the value of the "reporter_id" field.
func (lruo *LocationReportUpdateOne) ClearReporterID() *LocationReportUpdateOne {
	lruo.mutation.ClearReporterID()
	return lruo
}

// SetConfidence sets the "confidence" field.
func (lruo *LocationReportUpdateOne) SetConfidence(l locationreport.Confidence) *LocationReportUpdateOne {
	lruo.mutation.SetConfidence(l)
	return lruo
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableConfidence(l *locationreport.Confidence) *LocationReportUpdateOne {
	if l != nil {
		lruo.SetConfidence(*l)
	}
	return lruo
}

// SetNotes sets the "notes" field.
func (lruo *LocationReportUpdateOne) SetNotes(s string) *LocationReportUpdateOne {
	lruo.mutation.SetNotes(s)
	return lruo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableNotes(s *string) *LocationReportUpdateOne {
	if s != nil {
		lruo.SetNotes(*s)
	}
	return lruo
}

// ClearNotes clears the value of the "notes" field.
func (lruo *LocationReportUpdateOne) ClearNotes() *LocationReportUpdateOne {
	lruo.mutation.ClearNotes()
	return lruo
}

// SetExpiresAt sets the "expires_at" field.
func (lruo *LocationReportUpdateOne) SetExpiresAt(t time.Time) *LocationReportUpdateOne {
	lruo.mutation.SetExpiresAt(t)
	return lruo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableExpiresAt(t *time.Time) *LocationReportUpdateOne {
	if t != nil {
		lruo.SetExpiresAt(*t)
	}
	return lruo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (lruo *LocationReportUpdateOne) ClearExpiresAt() *LocationReportUpdateOne {
	lruo.mutation.ClearExpiresAt()
	return lruo
}

// SetIsActive sets the "is_active" field.
func (lruo *LocationReportUpdateOne) SetIsActive(b bool) *LocationReportUpdateOne {
	lruo.mutation.SetIsActive(b)
	return lruo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (lruo *LocationReportUpdateOne) SetNillableIsActive(b *bool) *LocationReportUpdateOne {
	if b != nil {
		lruo.SetIsActive(*b)
	}
	return lruo
}

// SetReporter sets the "reporter" edge to the User entity.
func (lruo *LocationReportUpdateOne) SetReporter(u *User) *LocationReportUpdateOne {
	return lruo.SetReporterID(u.ID)
}

// Mutation returns the LocationReportMutation object of the builder.
func (lruo *LocationReportUpdateOne) Mutation() *LocationReportMutation {
	return lruo.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (lruo *LocationReportUpdateOne) ClearReporter() *LocationReportUpdateOne {
	lruo.mutation.ClearReporter()
	return lruo
}

// Where appends a list predicates to the LocationReportUpdate builder.
func (lruo *LocationReportUpdateOne) Where(ps ...predicate.LocationReport) *LocationReportUpdateOne {
	lruo.mutation.Where(ps...)
	return lruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lruo *LocationReportUpdateOne) Select(field string, fields ...string) *LocationReportUpdateOne {
	lruo.fields = append([]string{field}, fields...)
	return lruo
}

// Save executes the query and returns the updated LocationReport entity.
func (lruo *LocationReportUpdateOne) Save(ctx context.Context) (*LocationReport, error) {
	return withHooks(ctx, lruo.sqlSave, lruo.mutation, lruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lruo *LocationReportUpdateOne) SaveX(ctx context.Context) *LocationReport {
	node, err := lruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lruo *LocationReportUpdateOne) Exec(ctx context.Context) error {
	_, err := lruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lruo *LocationReportUpdateOne) ExecX(ctx context.Context) {
	if err := lruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lruo *LocationReportUpdateOne) check() error {
	if v, ok := lruo.mutation.BuildingName(); ok {
		if err := locationreport.BuildingNameValidator(v); err != nil {
			return &ValidationError{Name: "building_name", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_name": %w`, err)}
		}
	}
	if v, ok := lruo.mutation.BuildingType(); ok {
		if err := locationreport.BuildingTypeValidator(v); err != nil {
			return &ValidationError{Name: "building_type", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_type": %w`, err)}
		}
	}
	if v, ok := lruo.mutation.CoordinateX(); ok {
		if err := locationreport.CoordinateXValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_x", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_x": %w`, err)}
		}
	}
	if v, ok := lruo.mutation.CoordinateY(); ok {
		if err := locationreport.CoordinateYValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_y", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_y": %w`, err)}
		}
	}
	if v, ok := lruo.mutation.GuildLevel(); ok {
		if err := locationreport.GuildLevelValidator(v); err != nil {
			return &ValidationError{Name: "guild_level", err: fmt.Errorf(`ent: validator failed for field "LocationReport.guild_level": %w`, err)}
		}
	}
	if v, ok := lruo.mutation.Confidence(); ok {
		if err := locationreport.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "LocationReport.confidence": %w`, err)}
		}
	}
	return nil
}

func (lruo *LocationReportUpdateOne) sqlSave(ctx context.Context) (_node *LocationReport, err error) {
	if err := lruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(locationreport.Table, locationreport.Columns, sqlgraph.NewFieldSpec(locationreport.FieldID, field.TypeInt))
	id, ok := lruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LocationReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationreport.FieldID)
		for _, f := range fields {
			if !locationreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != locationreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lruo.mutation.BuildingName(); ok {
		_spec.SetField(locationreport.FieldBuildingName, field.TypeString, value)
	}
	if value, ok := lruo.mutation.BuildingType(); ok {
		_spec.SetField(locationreport.FieldBuildingType, field.TypeEnum, value)
	}
	if value, ok := lruo.mutation.CustomItemName(); ok {
		_spec.SetField(locationreport.FieldCustomItemName, field.TypeString, value)
	}
	if lruo.mutation.CustomItemNameCleared() {
		_spec.ClearField(locationreport.FieldCustomItemName, field.TypeString)
	}
	if value, ok := lruo.mutation.CoordinateX(); ok {
		_spec.SetField(locationreport.FieldCoordinateX, field.TypeInt, value)
	}
	if value, ok := lruo.mutation.AddedCoordinateX(); ok {
		_spec.AddField(locationreport.FieldCoordinateX, field.TypeInt, value)
	}
	if lruo.mutation.CoordinateXCleared() {
		_spec.ClearField(locationreport.FieldCoordinateX, field.TypeInt)
	}
	if value, ok := lruo.mutation.CoordinateY(); ok {
		_spec.SetField(locationreport.FieldCoordinateY, field.TypeInt, value)
	}
	if value, ok := lruo.mutation.AddedCoordinateY(); ok {
		_spec.AddField(locationreport.FieldCoordinateY, field.TypeInt, value)
	}
	if lruo.mutation.CoordinateYCleared() {
		_spec.ClearField(locationreport.FieldCoordinateY, field.TypeInt)
	}
	if value, ok := lruo.mutation.StreetName(); ok {
		_spec.SetField(locationreport.FieldStreetName, field.TypeString, value)
	}
	if lruo.mutation.StreetNameCleared() {
		_spec.ClearField(locationreport.FieldStreetName, field.TypeString)
	}
	if value, ok := lruo.mutation.StreetNumber(); ok {
		_spec.SetField(locationreport.FieldStreetNumber, field.TypeString, value)
	}
	if lruo.mutation.StreetNumberCleared() {
		_spec.ClearField(locationreport.FieldStreetNumber, field.TypeString)
	}
	if value, ok := lruo.mutation.GuildLevel(); ok {
		_spec.SetField(locationreport.FieldGuildLevel, field.TypeInt, value)
	}
	if value, ok := lruo.mutation.AddedGuildLevel(); ok {
		_spec.AddField(locationreport.FieldGuildLevel, field.TypeInt, value)
	}
	if lruo.mutation.GuildLevelCleared() {
		_spec.ClearField(locationreport.FieldGuildLevel, field.TypeInt)
	}
	if value, ok := lruo.mutation.ReporterUsername(); ok {
		_spec.SetField(locationreport.FieldReporterUsername, field.TypeString, value)
	}
	if lruo.mutation.ReporterUsernameCleared() {
		_spec.ClearField(locationreport.FieldReporterUsername, field.TypeString)
	}
	if value, ok := lruo.mutation.Confidence(); ok {
		_spec.SetField(locationreport.FieldConfidence, field.TypeEnum, value)
	}
	if value, ok := lruo.mutation.Notes(); ok {
		_spec.SetField(locationreport.FieldNotes, field.TypeString, value)
	}
	if lruo.mutation.NotesCleared() {
		_spec.ClearField(locationreport.FieldNotes, field.TypeString)
	}
	if value, ok := lruo.mutation.ExpiresAt(); ok {
		_spec.SetField(locationreport.FieldExpiresAt, field.TypeTime, value)
	}
	if lruo.mutation.ExpiresAtCleared() {
		_spec.ClearField(locationreport.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := lruo.mutation.IsActive(); ok {
		_spec.SetField(locationreport.FieldIsActive, field.TypeBool, value)
	}
	if lruo.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationreport.ReporterTable,
			Columns: []string{locationreport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lruo.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationreport.ReporterTable,
			Columns: []string{locationreport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LocationReport{config: lruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{locationreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lruo.mutation.done = true
	return _node, nil
}
