// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/user"
)

// LocationReportCreate is the builder for creating a LocationReport entity.
type LocationReportCreate struct {
	config
	mutation *LocationReportMutation
	hooks    []Hook
}

// SetBuildingName sets the "building_name" field.
func (lrc *LocationReportCreate) SetBuildingName(s string) *LocationReportCreate {
	lrc.mutation.SetBuildingName(s)
	return lrc
}

// SetBuildingType sets the "building_type" field.
func (lrc *LocationReportCreate) SetBuildingType(lt locationreport.BuildingType) *LocationReportCreate {
	lrc.mutation.SetBuildingType(lt)
	return lrc
}

// SetCustomItemName sets the "custom_item_name" field.
func (lrc *LocationReportCreate) SetCustomItemName(s string) *LocationReportCreate {
	lrc.mutation.SetCustomItemName(s)
	return lrc
}

// SetNillableCustomItemName sets the "custom_item_name" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableCustomItemName(s *string) *LocationReportCreate {
	if s != nil {
		lrc.SetCustomItemName(*s)
	}
	return lrc
}

// SetCoordinateX sets the "coordinate_x" field.
func (lrc *LocationReportCreate) SetCoordinateX(i int) *LocationReportCreate {
	lrc.mutation.SetCoordinateX(i)
	return lrc
}

// SetNillableCoordinateX sets the "coordinate_x" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableCoordinateX(i *int) *LocationReportCreate {
	if i != nil {
		lrc.SetCoordinateX(*i)
	}
	return lrc
}

// SetCoordinateY sets the "coordinate_y" field.
func (lrc *LocationReportCreate) SetCoordinateY(i int) *LocationReportCreate {
	lrc.mutation.SetCoordinateY(i)
	return lrc
}

// SetNillableCoordinateY sets the "coordinate_y" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableCoordinateY(i *int) *LocationReportCreate {
	if i != nil {
		lrc.SetCoordinateY(*i)
	}
	return lrc
}

// SetStreetName sets the "street_name" field.
func (lrc *LocationReportCreate) SetStreetName(s string) *LocationReportCreate {
	lrc.mutation.SetStreetName(s)
	return lrc
}

// SetNillableStreetName sets the "street_name" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableStreetName(s *string) *LocationReportCreate {
	if s != nil {
		lrc.SetStreetName(*s)
	}
	return lrc
}

// SetStreetNumber sets the "street_number" field.
func (lrc *LocationReportCreate) SetStreetNumber(s string) *LocationReportCreate {
	lrc.mutation.SetStreetNumber(s)
	return lrc
}

// SetNillableStreetNumber sets the "street_number" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableStreetNumber(s *string) *LocationReportCreate {
	if s != nil {
		lrc.SetStreetNumber(*s)
	}
	return lrc
}

// SetGuildLevel sets the "guild_level" field.
func (lrc *LocationReportCreate) SetGuildLevel(i int) *LocationReportCreate {
	lrc.mutation.SetGuildLevel(i)
	return lrc
}

// SetNillableGuildLevel sets the "guild_level" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableGuildLevel(i *int) *LocationReportCreate {
	if i != nil {
		lrc.SetGuildLevel(*i)
	}
	return lrc
}

// SetReporterUsername sets the "reporter_username" field.
func (lrc *LocationReportCreate) SetReporterUsername(s string) *LocationReportCreate {
	lrc.mutation.SetReporterUsername(s)
	return lrc
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableReporterUsername(s *string) *LocationReportCreate {
	if s != nil {
		lrc.SetReporterUsername(*s)
	}
	return lrc
}

// SetReporterID sets the "reporter_id" field.
func (lrc *LocationReportCreate) SetReporterID(i int) *LocationReportCreate {
	lrc.mutation.SetReporterID(i)
	return lrc
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableReporterID(i *int) *LocationReportCreate {
	if i != nil {
		lrc.SetReporterID(*i)
	}
	return lrc
}

// SetConfidence sets the "confidence" field.
func (lrc *LocationReportCreate) SetConfidence(l locationreport.Confidence) *LocationReportCreate {
	lrc.mutation.SetConfidence(l)
	return lrc
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableConfidence(l *locationreport.Confidence) *LocationReportCreate {
	if l != nil {
		lrc.SetConfidence(*l)
	}
	return lrc
}

// SetNotes sets the "notes" field.
func (lrc *LocationReportCreate) SetNotes(s string) *LocationReportCreate {
	lrc.mutation.SetNotes(s)
	return lrc
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableNotes(s *string) *LocationReportCreate {
	if s != nil {
		lrc.SetNotes(*s)
	}
	return lrc
}

// SetReportedAt sets the "reported_at" field.
func (lrc *LocationReportCreate) SetReportedAt(t time.Time) *LocationReportCreate {
	lrc.mutation.SetReportedAt(t)
	return lrc
}

// SetNillableReportedAt sets the "reported_at" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableReportedAt(t *time.Time) *LocationReportCreate {
	if t != nil {
		lrc.SetReportedAt(*t)
	}
	return lrc
}

// SetExpiresAt sets the "expires_at" field.
func (lrc *LocationReportCreate) SetExpiresAt(t time.Time) *LocationReportCreate {
	lrc.mutation.SetExpiresAt(t)
	return lrc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableExpiresAt(t *time.Time) *LocationReportCreate {
	if t != nil {
		lrc.SetExpiresAt(*t)
	}
	return lrc
}

// SetIsActive sets the "is_active" field.
func (lrc *LocationReportCreate) SetIsActive(b bool) *LocationReportCreate {
	lrc.mutation.SetIsActive(b)
	return lrc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (lrc *LocationReportCreate) SetNillableIsActive(b *bool) *LocationReportCreate {
	if b != nil {
		lrc.SetIsActive(*b)
	}
	return lrc
}

// SetReporter sets the "reporter" edge to the User entity.
func (lrc *LocationReportCreate) SetReporter(u *User) *LocationReportCreate {
	return lrc.SetReporterID(u.ID)
}

// Mutation returns the LocationReportMutation object of the builder.
func (lrc *LocationReportCreate) Mutation() *LocationReportMutation {
	return lrc.mutation
}

// Save creates the LocationReport in the database.
func (lrc *LocationReportCreate) Save(ctx context.Context) (*LocationReport, error) {
	lrc.defaults()
	return withHooks(ctx, lrc.sqlSave, lrc.mutation, lrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lrc *LocationReportCreate) SaveX(ctx context.Context) *LocationReport {
	v, err := lrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lrc *LocationReportCreate) Exec(ctx context.Context) error {
	_, err := lrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrc *LocationReportCreate) ExecX(ctx context.Context) {
	if err := lrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lrc *LocationReportCreate) defaults() {
	if _, ok := lrc.mutation.Confidence(); !ok {
		v := locationreport.DefaultConfidence
		lrc.mutation.SetConfidence(v)
	}
	if _, ok := lrc.mutation.ReportedAt(); !ok {
		v := locationreport.DefaultReportedAt()
		lrc.mutation.SetReportedAt(v)
	}
	if _, ok := lrc.mutation.IsActive(); !ok {
		v := locationreport.DefaultIsActive
		lrc.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lrc *LocationReportCreate) check() error {
	if _, ok := lrc.mutation.BuildingName(); !ok {
		return &ValidationError{Name: "building_name", err: errors.New(`ent: missing required field "LocationReport.building_name"`)}
	}
	if v, ok := lrc.mutation.BuildingName(); ok {
		if err := locationreport.BuildingNameValidator(v); err != nil {
			return &ValidationError{Name: "building_name", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_name": %w`, err)}
		}
	}
	if _, ok := lrc.mutation.BuildingType(); !ok {
		return &ValidationError{Name: "building_type", err: errors.New(`ent: missing required field "LocationReport.building_type"`)}
	}
	if v, ok := lrc.mutation.BuildingType(); ok {
		if err := locationreport.BuildingTypeValidator(v); err != nil {
			return &ValidationError{Name: "building_type", err: fmt.Errorf(`ent: validator failed for field "LocationReport.building_type": %w`, err)}
		}
	}
	if v, ok := lrc.mutation.CoordinateX(); ok {
		if err := locationreport.CoordinateXValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_x", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_x": %w`, err)}
		}
	}
	if v, ok := lrc.mutation.CoordinateY(); ok {
		if err := locationreport.CoordinateYValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_y", err: fmt.Errorf(`ent: validator failed for field "LocationReport.coordinate_y": %w`, err)}
		}
	}
	if v, ok := lrc.mutation.GuildLevel(); ok {
		if err := locationreport.GuildLevelValidator(v); err != nil {
			return &ValidationError{Name: "guild_level", err: fmt.Errorf(`ent: validator failed for field "LocationReport.guild_level": %w`, err)}
		}
	}
	if _, ok := lrc.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "LocationReport.confidence"`)}
	}
	if v, ok := lrc.mutation.Confidence(); ok {
		if err := locationreport.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "LocationReport.confidence": %w`, err)}
		}
	}
	if _, ok := lrc.mutation.ReportedAt(); !ok {
		return &ValidationError{Name: "reported_at", err: errors.New(`ent: missing required field "LocationReport.reported_at"`)}
	}
	if _, ok := lrc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "LocationReport.is_active"`)}
	}
	return nil
}

func (lrc *LocationReportCreate) sqlSave(ctx context.Context) (*LocationReport, error) {
	if err := lrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lrc.mutation.id = &_node.ID
	lrc.mutation.done = true
	return _node, nil
}

func (lrc *LocationReportCreate) createSpec() (*LocationReport, *sqlgraph.CreateSpec) {
	var (
		_node = &LocationReport{config: lrc.config}
		_spec = sqlgraph.NewCreateSpec(locationreport.Table, sqlgraph.NewFieldSpec(locationreport.FieldID, field.TypeInt))
	)
	if value, ok := lrc.mutation.BuildingName(); ok {
		_spec.SetField(locationreport.FieldBuildingName, field.TypeString, value)
		_node.BuildingName = value
	}
	if value, ok := lrc.mutation.BuildingType(); ok {
		_spec.SetField(locationreport.FieldBuildingType, field.TypeEnum, value)
		_node.BuildingType = value
	}
	if value, ok := lrc.mutation.CustomItemName(); ok {
		_spec.SetField(locationreport.FieldCustomItemName, field.TypeString, value)
		_node.CustomItemName = value
	}
	if value, ok := lrc.mutation.CoordinateX(); ok {
		_spec.SetField(locationreport.FieldCoordinateX, field.TypeInt, value)
		_node.CoordinateX = value
	}
	if value, ok := lrc.mutation.CoordinateY(); ok {
		_spec.SetField(locationreport.FieldCoordinateY, field.TypeInt, value)
		_node.CoordinateY = value
	}
	if value, ok := lrc.mutation.StreetName(); ok {
		_spec.SetField(locationreport.FieldStreetName, field.TypeString, value)
		_node.StreetName = value
	}
	if value, ok := lrc.mutation.StreetNumber(); ok {
		_spec.SetField(locationreport.FieldStreetNumber, field.TypeString, value)
		_node.StreetNumber = value
	}
	if value, ok := lrc.mutation.GuildLevel(); ok {
		_spec.SetField(locationreport.FieldGuildLevel, field.TypeInt, value)
		_node.GuildLevel = value
	}
	if value, ok := lrc.mutation.ReporterUsername(); ok {
		_spec.SetField(locationreport.FieldReporterUsername, field.TypeString, value)
		_node.ReporterUsername = value
	}
	if value, ok := lrc.mutation.Confidence(); ok {
		_spec.SetField(locationreport.FieldConfidence, field.TypeEnum, value)
		_node.Confidence = value
	}
	if value, ok := lrc.mutation.Notes(); ok {
		_spec.SetField(locationreport.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := lrc.mutation.ReportedAt(); ok {
		_spec.SetField(locationreport.FieldReportedAt, field.TypeTime, value)
		_node.ReportedAt = value
	}
	if value, ok := lrc.mutation.ExpiresAt(); ok {
		_spec.SetField(locationreport.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := lrc.mutation.IsActive(); ok {
		_spec.SetField(locationreport.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := lrc.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   locationreport.ReporterTable,
			Columns: []string{locationreport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReporterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LocationReportCreateBulk is the builder for creating many LocationReport entities in bulk.
type LocationReportCreateBulk struct {
	config
	err      error
	builders []*LocationReportCreate
}

// Save creates the LocationReport entities in the database.
func (lrcb *LocationReportCreateBulk) Save(ctx context.Context) ([]*LocationReport, error) {
	if lrcb.err != nil {
		return nil, lrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lrcb.builders))
	nodes := make([]*LocationReport, len(lrcb.builders))
	mutators := make([]Mutator, len(lrcb.builders))
	for i := range lrcb.builders {
		func(i int, root context.Context) {
			builder := lrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocationReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lrcb *LocationReportCreateBulk) SaveX(ctx context.Context) []*LocationReport {
	v, err := lrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lrcb *LocationReportCreateBulk) Exec(ctx context.Context) error {
	_, err := lrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrcb *LocationReportCreateBulk) ExecX(ctx context.Context) {
	if err := lrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
