// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/user"
)

// LocationReport is the model entity for the LocationReport schema.
type LocationReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name of the building
	BuildingName string `json:"building_name,omitempty"`
	// Type of building
	BuildingType locationreport.BuildingType `json:"building_type,omitempty"`
	// Custom item name when building_type is 'item'
	CustomItemName string `json:"custom_item_name,omitempty"`
	// X coordinate (1-200)
	CoordinateX int `json:"coordinate_x,omitempty"`
	// Y coordinate (1-200)
	CoordinateY int `json:"coordinate_y,omitempty"`
	// Street name
	StreetName string `json:"street_name,omitempty"`
	// Street number
	StreetNumber string `json:"street_number,omitempty"`
	// Guild level (1-3) for guild buildings
	GuildLevel int `json:"guild_level,omitempty"`
	// Username of the reporter
	ReporterUsername string `json:"reporter_username,omitempty"`
	// ID of the reporter user
	ReporterID int `json:"reporter_id,omitempty"`
	// Confidence level of the report
	Confidence locationreport.Confidence `json:"confidence,omitempty"`
	// Additional notes about the location
	Notes string `json:"notes,omitempty"`
	// When the report was created
	ReportedAt time.Time `json:"reported_at,omitempty"`
	// When this report expires
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Whether this report is active
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationReportQuery when eager-loading is set.
	Edges        LocationReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LocationReportEdges holds the relations/edges for other nodes in the graph.
type LocationReportEdges struct {
	// Reporter holds the value of the reporter edge.
	Reporter *User `json:"reporter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReporterOrErr returns the Reporter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationReportEdges) ReporterOrErr() (*User, error) {
	if e.Reporter != nil {
		return e.Reporter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reporter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LocationReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case locationreport.FieldIsActive:
			values[i] = new(sql.NullBool)
		case locationreport.FieldID, locationreport.FieldCoordinateX, locationreport.FieldCoordinateY, locationreport.FieldGuildLevel, locationreport.FieldReporterID:
			values[i] = new(sql.NullInt64)
		case locationreport.FieldBuildingName, locationreport.FieldBuildingType, locationreport.FieldCustomItemName, locationreport.FieldStreetName, locationreport.FieldStreetNumber, locationreport.FieldReporterUsername, locationreport.FieldConfidence, locationreport.FieldNotes:
			values[i] = new(sql.NullString)
		case locationreport.FieldReportedAt, locationreport.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LocationReport fields.
func (lr *LocationReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locationreport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lr.ID = int(value.Int64)
		case locationreport.FieldBuildingName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field building_name", values[i])
			} else if value.Valid {
				lr.BuildingName = value.String
			}
		case locationreport.FieldBuildingType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field building_type", values[i])
			} else if value.Valid {
				lr.BuildingType = locationreport.BuildingType(value.String)
			}
		case locationreport.FieldCustomItemName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_item_name", values[i])
			} else if value.Valid {
				lr.CustomItemName = value.String
			}
		case locationreport.FieldCoordinateX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field coordinate_x", values[i])
			} else if value.Valid {
				lr.CoordinateX = int(value.Int64)
			}
		case locationreport.FieldCoordinateY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field coordinate_y", values[i])
			} else if value.Valid {
				lr.CoordinateY = int(value.Int64)
			}
		case locationreport.FieldStreetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street_name", values[i])
			} else if value.Valid {
				lr.StreetName = value.String
			}
		case locationreport.FieldStreetNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street_number", values[i])
			} else if value.Valid {
				lr.StreetNumber = value.String
			}
		case locationreport.FieldGuildLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field guild_level", values[i])
			} else if value.Valid {
				lr.GuildLevel = int(value.Int64)
			}
		case locationreport.FieldReporterUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_username", values[i])
			} else if value.Valid {
				lr.ReporterUsername = value.String
			}
		case locationreport.FieldReporterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_id", values[i])
			} else if value.Valid {
				lr.ReporterID = int(value.Int64)
			}
		case locationreport.FieldConfidence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				lr.Confidence = locationreport.Confidence(value.String)
			}
		case locationreport.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				lr.Notes = value.String
			}
		case locationreport.FieldReportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reported_at", values[i])
			} else if value.Valid {
				lr.ReportedAt = value.Time
			}
		case locationreport.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				lr.ExpiresAt = value.Time
			}
		case locationreport.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				lr.IsActive = value.Bool
			}
		default:
			lr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LocationReport.
// This includes values selected through modifiers, order, etc.
func (lr *LocationReport) Value(name string) (ent.Value, error) {
	return lr.selectValues.Get(name)
}

// QueryReporter queries the "reporter" edge of the LocationReport entity.
func (lr *LocationReport) QueryReporter() *UserQuery {
	return NewLocationReportClient(lr.config).QueryReporter(lr)
}

// Update returns a builder for updating this LocationReport.
// Note that you need to call LocationReport.Unwrap() before calling this method if this LocationReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (lr *LocationReport) Update() *LocationReportUpdateOne {
	return NewLocationReportClient(lr.config).UpdateOne(lr)
}

// Unwrap unwraps the LocationReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lr *LocationReport) Unwrap() *LocationReport {
	_tx, ok := lr.config.driver.(*txDriver)
	if !ok {
		panic("ent: LocationReport is not a transactional entity")
	}
	lr.config.driver = _tx.drv
	return lr
}

// String implements the fmt.Stringer.
func (lr *LocationReport) String() string {
	var builder strings.Builder
	builder.WriteString("LocationReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lr.ID))
	builder.WriteString("building_name=")
	builder.WriteString(lr.BuildingName)
	builder.WriteString(", ")
	builder.WriteString("building_type=")
	builder.WriteString(fmt.Sprintf("%v", lr.BuildingType))
	builder.WriteString(", ")
	builder.WriteString("custom_item_name=")
	builder.WriteString(lr.CustomItemName)
	builder.WriteString(", ")
	builder.WriteString("coordinate_x=")
	builder.WriteString(fmt.Sprintf("%v", lr.CoordinateX))
	builder.WriteString(", ")
	builder.WriteString("coordinate_y=")
	builder.WriteString(fmt.Sprintf("%v", lr.CoordinateY))
	builder.WriteString(", ")
	builder.WriteString("street_name=")
	builder.WriteString(lr.StreetName)
	builder.WriteString(", ")
	builder.WriteString("street_number=")
	builder.WriteString(lr.StreetNumber)
	builder.WriteString(", ")
	builder.WriteString("guild_level=")
	builder.WriteString(fmt.Sprintf("%v", lr.GuildLevel))
	builder.WriteString(", ")
	builder.WriteString("reporter_username=")
	builder.WriteString(lr.ReporterUsername)
	builder.WriteString(", ")
	builder.WriteString("reporter_id=")
	builder.WriteString(fmt.Sprintf("%v", lr.ReporterID))
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", lr.Confidence))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(lr.Notes)
	builder.WriteString(", ")
	builder.WriteString("reported_at=")
	builder.WriteString(lr.ReportedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(lr.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", lr.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// LocationReports is a parsable slice of LocationReport.
type LocationReports []*LocationReport
