// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// LocationReportQuery is the builder for querying LocationReport entities.
type LocationReportQuery struct {
	config
	ctx          *QueryContext
	order        []locationreport.OrderOption
	inters       []Interceptor
	predicates   []predicate.LocationReport
	withReporter *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LocationReportQuery builder.
func (lrq *LocationReportQuery) Where(ps ...predicate.LocationReport) *LocationReportQuery {
	lrq.predicates = append(lrq.predicates, ps...)
	return lrq
}

// Limit the number of records to be returned by this query.
func (lrq *LocationReportQuery) Limit(limit int) *LocationReportQuery {
	lrq.ctx.Limit = &limit
	return lrq
}

// Offset to start from.
func (lrq *LocationReportQuery) Offset(offset int) *LocationReportQuery {
	lrq.ctx.Offset = &offset
	return lrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrq *LocationReportQuery) Unique(unique bool) *LocationReportQuery {
	lrq.ctx.Unique = &unique
	return lrq
}

// Order specifies how the records should be ordered.
func (lrq *LocationReportQuery) Order(o ...locationreport.OrderOption) *LocationReportQuery {
	lrq.order = append(lrq.order, o...)
	return lrq
}

// QueryReporter chains the current query on the "reporter" edge.
func (lrq *LocationReportQuery) QueryReporter() *UserQuery {
	query := (&UserClient{config: lrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(locationreport.Table, locationreport.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, locationreport.ReporterTable, locationreport.ReporterColumn),
		)
		fromU = sqlgraph.SetNeighbors(lrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LocationReport entity from the query.
// Returns a *NotFoundError when no LocationReport was found.
func (lrq *LocationReportQuery) First(ctx context.Context) (*LocationReport, error) {
	nodes, err := lrq.Limit(1).All(setContextOp(ctx, lrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{locationreport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrq *LocationReportQuery) FirstX(ctx context.Context) *LocationReport {
	node, err := lrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LocationReport ID from the query.
// Returns a *NotFoundError when no LocationReport ID was found.
func (lrq *LocationReportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(1).IDs(setContextOp(ctx, lrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{locationreport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrq *LocationReportQuery) FirstIDX(ctx context.Context) int {
	id, err := lrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LocationReport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LocationReport entity is found.
// Returns a *NotFoundError when no LocationReport entities are found.
func (lrq *LocationReportQuery) Only(ctx context.Context) (*LocationReport, error) {
	nodes, err := lrq.Limit(2).All(setContextOp(ctx, lrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{locationreport.Label}
	default:
		return nil, &NotSingularError{locationreport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrq *LocationReportQuery) OnlyX(ctx context.Context) *LocationReport {
	node, err := lrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LocationReport ID in the query.
// Returns a *NotSingularError when more than one LocationReport ID is found.
// Returns a *NotFoundError when no entities are found.
func (lrq *LocationReportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(2).IDs(setContextOp(ctx, lrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{locationreport.Label}
	default:
		err = &NotSingularError{locationreport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrq *LocationReportQuery) OnlyIDX(ctx context.Context) int {
	id, err := lrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LocationReports.
func (lrq *LocationReportQuery) All(ctx context.Context) ([]*LocationReport, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryAll)
	if err := lrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LocationReport, *LocationReportQuery]()
	return withInterceptors[[]*LocationReport](ctx, lrq, qr, lrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lrq *LocationReportQuery) AllX(ctx context.Context) []*LocationReport {
	nodes, err := lrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LocationReport IDs.
func (lrq *LocationReportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lrq.ctx.Unique == nil && lrq.path != nil {
		lrq.Unique(true)
	}
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryIDs)
	if err = lrq.Select(locationreport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrq *LocationReportQuery) IDsX(ctx context.Context) []int {
	ids, err := lrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrq *LocationReportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryCount)
	if err := lrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lrq, querierCount[*LocationReportQuery](), lrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lrq *LocationReportQuery) CountX(ctx context.Context) int {
	count, err := lrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrq *LocationReportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lrq.ctx, ent.OpQueryExist)
	switch _, err := lrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lrq *LocationReportQuery) ExistX(ctx context.Context) bool {
	exist, err := lrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LocationReportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrq *LocationReportQuery) Clone() *LocationReportQuery {
	if lrq == nil {
		return nil
	}
	return &LocationReportQuery{
		config:       lrq.config,
		ctx:          lrq.ctx.Clone(),
		order:        append([]locationreport.OrderOption{}, lrq.order...),
		inters:       append([]Interceptor{}, lrq.inters...),
		predicates:   append([]predicate.LocationReport{}, lrq.predicates...),
		withReporter: lrq.withReporter.Clone(),
		// clone intermediate query.
		sql:  lrq.sql.Clone(),
		path: lrq.path,
	}
}

// WithReporter tells the query-builder to eager-load the nodes that are connected to
// the "reporter" edge. The optional arguments are used to configure the query builder of the edge.
func (lrq *LocationReportQuery) WithReporter(opts ...func(*UserQuery)) *LocationReportQuery {
	query := (&UserClient{config: lrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lrq.withReporter = query
	return lrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BuildingName string `json:"building_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LocationReport.Query().
//		GroupBy(locationreport.FieldBuildingName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lrq *LocationReportQuery) GroupBy(field string, fields ...string) *LocationReportGroupBy {
	lrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LocationReportGroupBy{build: lrq}
	grbuild.flds = &lrq.ctx.Fields
	grbuild.label = locationreport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BuildingName string `json:"building_name,omitempty"`
//	}
//
//	client.LocationReport.Query().
//		Select(locationreport.FieldBuildingName).
//		Scan(ctx, &v)
func (lrq *LocationReportQuery) Select(fields ...string) *LocationReportSelect {
	lrq.ctx.Fields = append(lrq.ctx.Fields, fields...)
	sbuild := &LocationReportSelect{LocationReportQuery: lrq}
	sbuild.label = locationreport.Label
	sbuild.flds, sbuild.scan = &lrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LocationReportSelect configured with the given aggregations.
func (lrq *LocationReportQuery) Aggregate(fns ...AggregateFunc) *LocationReportSelect {
	return lrq.Select().Aggregate(fns...)
}

func (lrq *LocationReportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lrq); err != nil {
				return err
			}
		}
	}
	for _, f := range lrq.ctx.Fields {
		if !locationreport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrq.path != nil {
		prev, err := lrq.path(ctx)
		if err != nil {
			return err
		}
		lrq.sql = prev
	}
	return nil
}

func (lrq *LocationReportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LocationReport, error) {
	var (
		nodes       = []*LocationReport{}
		_spec       = lrq.querySpec()
		loadedTypes = [1]bool{
			lrq.withReporter != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LocationReport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LocationReport{config: lrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lrq.withReporter; query != nil {
		if err := lrq.loadReporter(ctx, query, nodes, nil,
			func(n *LocationReport, e *User) { n.Edges.Reporter = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lrq *LocationReportQuery) loadReporter(ctx context.Context, query *UserQuery, nodes []*LocationReport, init func(*LocationReport), assign func(*LocationReport, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LocationReport)
	for i := range nodes {
		fk := nodes[i].ReporterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reporter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lrq *LocationReportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrq.querySpec()
	_spec.Node.Columns = lrq.ctx.Fields
	if len(lrq.ctx.Fields) > 0 {
		_spec.Unique = lrq.ctx.Unique != nil && *lrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lrq.driver, _spec)
}

func (lrq *LocationReportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(locationreport.Table, locationreport.Columns, sqlgraph.NewFieldSpec(locationreport.FieldID, field.TypeInt))
	_spec.From = lrq.sql
	if unique := lrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lrq.path != nil {
		_spec.Unique = true
	}
	if fields := lrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, locationreport.FieldID)
		for i := range fields {
			if fields[i] != locationreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if lrq.withReporter != nil {
			_spec.Node.AddColumnOnce(locationreport.FieldReporterID)
		}
	}
	if ps := lrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrq *LocationReportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrq.driver.Dialect())
	t1 := builder.Table(locationreport.Table)
	columns := lrq.ctx.Fields
	if len(columns) == 0 {
		columns = locationreport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrq.sql != nil {
		selector = lrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lrq.ctx.Unique != nil && *lrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lrq.predicates {
		p(selector)
	}
	for _, p := range lrq.order {
		p(selector)
	}
	if offset := lrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LocationReportGroupBy is the group-by builder for LocationReport entities.
type LocationReportGroupBy struct {
	selector
	build *LocationReportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrgb *LocationReportGroupBy) Aggregate(fns ...AggregateFunc) *LocationReportGroupBy {
	lrgb.fns = append(lrgb.fns, fns...)
	return lrgb
}

// Scan applies the selector query and scans the result into the given value.
func (lrgb *LocationReportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrgb.build.ctx, ent.OpQueryGroupBy)
	if err := lrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationReportQuery, *LocationReportGroupBy](ctx, lrgb.build, lrgb, lrgb.build.inters, v)
}

func (lrgb *LocationReportGroupBy) sqlScan(ctx context.Context, root *LocationReportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lrgb.fns))
	for _, fn := range lrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lrgb.flds)+len(lrgb.fns))
		for _, f := range *lrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LocationReportSelect is the builder for selecting fields of LocationReport entities.
type LocationReportSelect struct {
	*LocationReportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lrs *LocationReportSelect) Aggregate(fns ...AggregateFunc) *LocationReportSelect {
	lrs.fns = append(lrs.fns, fns...)
	return lrs
}

// Scan applies the selector query and scans the result into the given value.
func (lrs *LocationReportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrs.ctx, ent.OpQuerySelect)
	if err := lrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LocationReportQuery, *LocationReportSelect](ctx, lrs.LocationReportQuery, lrs, lrs.inters, v)
}

func (lrs *LocationReportSelect) sqlScan(ctx context.Context, root *LocationReportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lrs.fns))
	for _, fn := range lrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
