// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

// RichVampire is the model entity for the RichVampire schema.
type RichVampire struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name of the vampire
	VampireName string `json:"vampire_name,omitempty"`
	// When this entry was last updated
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// Username of the reporter
	ReporterUsername string `json:"reporter_username,omitempty"`
	// ID of the reporter user
	ReporterID int `json:"reporter_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RichVampireQuery when eager-loading is set.
	Edges        RichVampireEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RichVampireEdges holds the relations/edges for other nodes in the graph.
type RichVampireEdges struct {
	// Reporter holds the value of the reporter edge.
	Reporter *User `json:"reporter,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReporterOrErr returns the Reporter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RichVampireEdges) ReporterOrErr() (*User, error) {
	if e.Reporter != nil {
		return e.Reporter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reporter"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RichVampire) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case richvampire.FieldID, richvampire.FieldReporterID:
			values[i] = new(sql.NullInt64)
		case richvampire.FieldVampireName, richvampire.FieldReporterUsername:
			values[i] = new(sql.NullString)
		case richvampire.FieldLastUpdated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RichVampire fields.
func (rv *RichVampire) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case richvampire.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rv.ID = int(value.Int64)
		case richvampire.FieldVampireName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vampire_name", values[i])
			} else if value.Valid {
				rv.VampireName = value.String
			}
		case richvampire.FieldLastUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated", values[i])
			} else if value.Valid {
				rv.LastUpdated = value.Time
			}
		case richvampire.FieldReporterUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_username", values[i])
			} else if value.Valid {
				rv.ReporterUsername = value.String
			}
		case richvampire.FieldReporterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_id", values[i])
			} else if value.Valid {
				rv.ReporterID = int(value.Int64)
			}
		default:
			rv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RichVampire.
// This includes values selected through modifiers, order, etc.
func (rv *RichVampire) Value(name string) (ent.Value, error) {
	return rv.selectValues.Get(name)
}

// QueryReporter queries the "reporter" edge of the RichVampire entity.
func (rv *RichVampire) QueryReporter() *UserQuery {
	return NewRichVampireClient(rv.config).QueryReporter(rv)
}

// Update returns a builder for updating this RichVampire.
// Note that you need to call RichVampire.Unwrap() before calling this method if this RichVampire
// was returned from a transaction, and the transaction was committed or rolled back.
func (rv *RichVampire) Update() *RichVampireUpdateOne {
	return NewRichVampireClient(rv.config).UpdateOne(rv)
}

// Unwrap unwraps the RichVampire entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rv *RichVampire) Unwrap() *RichVampire {
	_tx, ok := rv.config.driver.(*txDriver)
	if !ok {
		panic("ent: RichVampire is not a transactional entity")
	}
	rv.config.driver = _tx.drv
	return rv
}

// String implements the fmt.Stringer.
func (rv *RichVampire) String() string {
	var builder strings.Builder
	builder.WriteString("RichVampire(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rv.ID))
	builder.WriteString("vampire_name=")
	builder.WriteString(rv.VampireName)
	builder.WriteString(", ")
	builder.WriteString("last_updated=")
	builder.WriteString(rv.LastUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reporter_username=")
	builder.WriteString(rv.ReporterUsername)
	builder.WriteString(", ")
	builder.WriteString("reporter_id=")
	builder.WriteString(fmt.Sprintf("%v", rv.ReporterID))
	builder.WriteByte(')')
	return builder.String()
}

// RichVampires is a parsable slice of RichVampire.
type RichVampires []*RichVampire
