// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/richvampire"
)

// RichVampireDelete is the builder for deleting a RichVampire entity.
type RichVampireDelete struct {
	config
	hooks    []Hook
	mutation *RichVampireMutation
}

// Where appends a list predicates to the RichVampireDelete builder.
func (rvd *RichVampireDelete) Where(ps ...predicate.RichVampire) *RichVampireDelete {
	rvd.mutation.Where(ps...)
	return rvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rvd *RichVampireDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rvd.sqlExec, rvd.mutation, rvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rvd *RichVampireDelete) ExecX(ctx context.Context) int {
	n, err := rvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rvd *RichVampireDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(richvampire.Table, sqlgraph.NewFieldSpec(richvampire.FieldID, field.TypeInt))
	if ps := rvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rvd.mutation.done = true
	return affected, err
}

// RichVampireDeleteOne is the builder for deleting a single RichVampire entity.
type RichVampireDeleteOne struct {
	rvd *RichVampireDelete
}

// Where appends a list predicates to the RichVampireDelete builder.
func (rvdo *RichVampireDeleteOne) Where(ps ...predicate.RichVampire) *RichVampireDeleteOne {
	rvdo.rvd.mutation.Where(ps...)
	return rvdo
}

// Exec executes the deletion query.
func (rvdo *RichVampireDeleteOne) Exec(ctx context.Context) error {
	n, err := rvdo.rvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{richvampire.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rvdo *RichVampireDeleteOne) ExecX(ctx context.Context) {
	if err := rvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
