// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

// RichVampireQuery is the builder for querying RichVampire entities.
type RichVampireQuery struct {
	config
	ctx          *QueryContext
	order        []richvampire.OrderOption
	inters       []Interceptor
	predicates   []predicate.RichVampire
	withReporter *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RichVampireQuery builder.
func (rvq *RichVampireQuery) Where(ps ...predicate.RichVampire) *RichVampireQuery {
	rvq.predicates = append(rvq.predicates, ps...)
	return rvq
}

// Limit the number of records to be returned by this query.
func (rvq *RichVampireQuery) Limit(limit int) *RichVampireQuery {
	rvq.ctx.Limit = &limit
	return rvq
}

// Offset to start from.
func (rvq *RichVampireQuery) Offset(offset int) *RichVampireQuery {
	rvq.ctx.Offset = &offset
	return rvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rvq *RichVampireQuery) Unique(unique bool) *RichVampireQuery {
	rvq.ctx.Unique = &unique
	return rvq
}

// Order specifies how the records should be ordered.
func (rvq *RichVampireQuery) Order(o ...richvampire.OrderOption) *RichVampireQuery {
	rvq.order = append(rvq.order, o...)
	return rvq
}

// QueryReporter chains the current query on the "reporter" edge.
func (rvq *RichVampireQuery) QueryReporter() *UserQuery {
	query := (&UserClient{config: rvq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(richvampire.Table, richvampire.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, richvampire.ReporterTable, richvampire.ReporterColumn),
		)
		fromU = sqlgraph.SetNeighbors(rvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RichVampire entity from the query.
// Returns a *NotFoundError when no RichVampire was found.
func (rvq *RichVampireQuery) First(ctx context.Context) (*RichVampire, error) {
	nodes, err := rvq.Limit(1).All(setContextOp(ctx, rvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{richvampire.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rvq *RichVampireQuery) FirstX(ctx context.Context) *RichVampire {
	node, err := rvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RichVampire ID from the query.
// Returns a *NotFoundError when no RichVampire ID was found.
func (rvq *RichVampireQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rvq.Limit(1).IDs(setContextOp(ctx, rvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{richvampire.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rvq *RichVampireQuery) FirstIDX(ctx context.Context) int {
	id, err := rvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RichVampire entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RichVampire entity is found.
// Returns a *NotFoundError when no RichVampire entities are found.
func (rvq *RichVampireQuery) Only(ctx context.Context) (*RichVampire, error) {
	nodes, err := rvq.Limit(2).All(setContextOp(ctx, rvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{richvampire.Label}
	default:
		return nil, &NotSingularError{richvampire.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rvq *RichVampireQuery) OnlyX(ctx context.Context) *RichVampire {
	node, err := rvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RichVampire ID in the query.
// Returns a *NotSingularError when more than one RichVampire ID is found.
// Returns a *NotFoundError when no entities are found.
func (rvq *RichVampireQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rvq.Limit(2).IDs(setContextOp(ctx, rvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{richvampire.Label}
	default:
		err = &NotSingularError{richvampire.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rvq *RichVampireQuery) OnlyIDX(ctx context.Context) int {
	id, err := rvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RichVampires.
func (rvq *RichVampireQuery) All(ctx context.Context) ([]*RichVampire, error) {
	ctx = setContextOp(ctx, rvq.ctx, ent.OpQueryAll)
	if err := rvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RichVampire, *RichVampireQuery]()
	return withInterceptors[[]*RichVampire](ctx, rvq, qr, rvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rvq *RichVampireQuery) AllX(ctx context.Context) []*RichVampire {
	nodes, err := rvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RichVampire IDs.
func (rvq *RichVampireQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rvq.ctx.Unique == nil && rvq.path != nil {
		rvq.Unique(true)
	}
	ctx = setContextOp(ctx, rvq.ctx, ent.OpQueryIDs)
	if err = rvq.Select(richvampire.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rvq *RichVampireQuery) IDsX(ctx context.Context) []int {
	ids, err := rvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rvq *RichVampireQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rvq.ctx, ent.OpQueryCount)
	if err := rvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rvq, querierCount[*RichVampireQuery](), rvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rvq *RichVampireQuery) CountX(ctx context.Context) int {
	count, err := rvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rvq *RichVampireQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rvq.ctx, ent.OpQueryExist)
	switch _, err := rvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rvq *RichVampireQuery) ExistX(ctx context.Context) bool {
	exist, err := rvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RichVampireQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rvq *RichVampireQuery) Clone() *RichVampireQuery {
	if rvq == nil {
		return nil
	}
	return &RichVampireQuery{
		config:       rvq.config,
		ctx:          rvq.ctx.Clone(),
		order:        append([]richvampire.OrderOption{}, rvq.order...),
		inters:       append([]Interceptor{}, rvq.inters...),
		predicates:   append([]predicate.RichVampire{}, rvq.predicates...),
		withReporter: rvq.withReporter.Clone(),
		// clone intermediate query.
		sql:  rvq.sql.Clone(),
		path: rvq.path,
	}
}

// WithReporter tells the query-builder to eager-load the nodes that are connected to
// the "reporter" edge. The optional arguments are used to configure the query builder of the edge.
func (rvq *RichVampireQuery) WithReporter(opts ...func(*UserQuery)) *RichVampireQuery {
	query := (&UserClient{config: rvq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rvq.withReporter = query
	return rvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VampireName string `json:"vampire_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RichVampire.Query().
//		GroupBy(richvampire.FieldVampireName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rvq *RichVampireQuery) GroupBy(field string, fields ...string) *RichVampireGroupBy {
	rvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RichVampireGroupBy{build: rvq}
	grbuild.flds = &rvq.ctx.Fields
	grbuild.label = richvampire.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VampireName string `json:"vampire_name,omitempty"`
//	}
//
//	client.RichVampire.Query().
//		Select(richvampire.FieldVampireName).
//		Scan(ctx, &v)
func (rvq *RichVampireQuery) Select(fields ...string) *RichVampireSelect {
	rvq.ctx.Fields = append(rvq.ctx.Fields, fields...)
	sbuild := &RichVampireSelect{RichVampireQuery: rvq}
	sbuild.label = richvampire.Label
	sbuild.flds, sbuild.scan = &rvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RichVampireSelect configured with the given aggregations.
func (rvq *RichVampireQuery) Aggregate(fns ...AggregateFunc) *RichVampireSelect {
	return rvq.Select().Aggregate(fns...)
}

func (rvq *RichVampireQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rvq); err != nil {
				return err
			}
		}
	}
	for _, f := range rvq.ctx.Fields {
		if !richvampire.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rvq.path != nil {
		prev, err := rvq.path(ctx)
		if err != nil {
			return err
		}
		rvq.sql = prev
	}
	return nil
}

func (rvq *RichVampireQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RichVampire, error) {
	var (
		nodes       = []*RichVampire{}
		_spec       = rvq.querySpec()
		loadedTypes = [1]bool{
			rvq.withReporter != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RichVampire).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RichVampire{config: rvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rvq.withReporter; query != nil {
		if err := rvq.loadReporter(ctx, query, nodes, nil,
			func(n *RichVampire, e *User) { n.Edges.Reporter = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rvq *RichVampireQuery) loadReporter(ctx context.Context, query *UserQuery, nodes []*RichVampire, init func(*RichVampire), assign func(*RichVampire, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RichVampire)
	for i := range nodes {
		fk := nodes[i].ReporterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reporter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rvq *RichVampireQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rvq.querySpec()
	_spec.Node.Columns = rvq.ctx.Fields
	if len(rvq.ctx.Fields) > 0 {
		_spec.Unique = rvq.ctx.Unique != nil && *rvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rvq.driver, _spec)
}

func (rvq *RichVampireQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(richvampire.Table, richvampire.Columns, sqlgraph.NewFieldSpec(richvampire.FieldID, field.TypeInt))
	_spec.From = rvq.sql
	if unique := rvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rvq.path != nil {
		_spec.Unique = true
	}
	if fields := rvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, richvampire.FieldID)
		for i := range fields {
			if fields[i] != richvampire.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rvq.withReporter != nil {
			_spec.Node.AddColumnOnce(richvampire.FieldReporterID)
		}
	}
	if ps := rvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rvq *RichVampireQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rvq.driver.Dialect())
	t1 := builder.Table(richvampire.Table)
	columns := rvq.ctx.Fields
	if len(columns) == 0 {
		columns = richvampire.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rvq.sql != nil {
		selector = rvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rvq.ctx.Unique != nil && *rvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rvq.predicates {
		p(selector)
	}
	for _, p := range rvq.order {
		p(selector)
	}
	if offset := rvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RichVampireGroupBy is the group-by builder for RichVampire entities.
type RichVampireGroupBy struct {
	selector
	build *RichVampireQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rvgb *RichVampireGroupBy) Aggregate(fns ...AggregateFunc) *RichVampireGroupBy {
	rvgb.fns = append(rvgb.fns, fns...)
	return rvgb
}

// Scan applies the selector query and scans the result into the given value.
func (rvgb *RichVampireGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rvgb.build.ctx, ent.OpQueryGroupBy)
	if err := rvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RichVampireQuery, *RichVampireGroupBy](ctx, rvgb.build, rvgb, rvgb.build.inters, v)
}

func (rvgb *RichVampireGroupBy) sqlScan(ctx context.Context, root *RichVampireQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rvgb.fns))
	for _, fn := range rvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rvgb.flds)+len(rvgb.fns))
		for _, f := range *rvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RichVampireSelect is the builder for selecting fields of RichVampire entities.
type RichVampireSelect struct {
	*RichVampireQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rvs *RichVampireSelect) Aggregate(fns ...AggregateFunc) *RichVampireSelect {
	rvs.fns = append(rvs.fns, fns...)
	return rvs
}

// Scan applies the selector query and scans the result into the given value.
func (rvs *RichVampireSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rvs.ctx, ent.OpQuerySelect)
	if err := rvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RichVampireQuery, *RichVampireSelect](ctx, rvs.RichVampireQuery, rvs, rvs.inters, v)
}

func (rvs *RichVampireSelect) sqlScan(ctx context.Context, root *RichVampireQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rvs.fns))
	for _, fn := range rvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
