// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

// RichVampireCreate is the builder for creating a RichVampire entity.
type RichVampireCreate struct {
	config
	mutation *RichVampireMutation
	hooks    []Hook
}

// SetVampireName sets the "vampire_name" field.
func (rvc *RichVampireCreate) SetVampireName(s string) *RichVampireCreate {
	rvc.mutation.SetVampireName(s)
	return rvc
}

// SetLastUpdated sets the "last_updated" field.
func (rvc *RichVampireCreate) SetLastUpdated(t time.Time) *RichVampireCreate {
	rvc.mutation.SetLastUpdated(t)
	return rvc
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (rvc *RichVampireCreate) SetNillableLastUpdated(t *time.Time) *RichVampireCreate {
	if t != nil {
		rvc.SetLastUpdated(*t)
	}
	return rvc
}

// SetReporterUsername sets the "reporter_username" field.
func (rvc *RichVampireCreate) SetReporterUsername(s string) *RichVampireCreate {
	rvc.mutation.SetReporterUsername(s)
	return rvc
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (rvc *RichVampireCreate) SetNillableReporterUsername(s *string) *RichVampireCreate {
	if s != nil {
		rvc.SetReporterUsername(*s)
	}
	return rvc
}

// SetReporterID sets the "reporter_id" field.
func (rvc *RichVampireCreate) SetReporterID(i int) *RichVampireCreate {
	rvc.mutation.SetReporterID(i)
	return rvc
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (rvc *RichVampireCreate) SetNillableReporterID(i *int) *RichVampireCreate {
	if i != nil {
		rvc.SetReporterID(*i)
	}
	return rvc
}

// SetReporter sets the "reporter" edge to the User entity.
func (rvc *RichVampireCreate) SetReporter(u *User) *RichVampireCreate {
	return rvc.SetReporterID(u.ID)
}

// Mutation returns the RichVampireMutation object of the builder.
func (rvc *RichVampireCreate) Mutation() *RichVampireMutation {
	return rvc.mutation
}

// Save creates the RichVampire in the database.
func (rvc *RichVampireCreate) Save(ctx context.Context) (*RichVampire, error) {
	rvc.defaults()
	return withHooks(ctx, rvc.sqlSave, rvc.mutation, rvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rvc *RichVampireCreate) SaveX(ctx context.Context) *RichVampire {
	v, err := rvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rvc *RichVampireCreate) Exec(ctx context.Context) error {
	_, err := rvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvc *RichVampireCreate) ExecX(ctx context.Context) {
	if err := rvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rvc *RichVampireCreate) defaults() {
	if _, ok := rvc.mutation.LastUpdated(); !ok {
		v := richvampire.DefaultLastUpdated()
		rvc.mutation.SetLastUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rvc *RichVampireCreate) check() error {
	if _, ok := rvc.mutation.VampireName(); !ok {
		return &ValidationError{Name: "vampire_name", err: errors.New(`ent: missing required field "RichVampire.vampire_name"`)}
	}
	if v, ok := rvc.mutation.VampireName(); ok {
		if err := richvampire.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "RichVampire.vampire_name": %w`, err)}
		}
	}
	if _, ok := rvc.mutation.LastUpdated(); !ok {
		return &ValidationError{Name: "last_updated", err: errors.New(`ent: missing required field "RichVampire.last_updated"`)}
	}
	return nil
}

func (rvc *RichVampireCreate) sqlSave(ctx context.Context) (*RichVampire, error) {
	if err := rvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rvc.mutation.id = &_node.ID
	rvc.mutation.done = true
	return _node, nil
}

func (rvc *RichVampireCreate) createSpec() (*RichVampire, *sqlgraph.CreateSpec) {
	var (
		_node = &RichVampire{config: rvc.config}
		_spec = sqlgraph.NewCreateSpec(richvampire.Table, sqlgraph.NewFieldSpec(richvampire.FieldID, field.TypeInt))
	)
	if value, ok := rvc.mutation.VampireName(); ok {
		_spec.SetField(richvampire.FieldVampireName, field.TypeString, value)
		_node.VampireName = value
	}
	if value, ok := rvc.mutation.LastUpdated(); ok {
		_spec.SetField(richvampire.FieldLastUpdated, field.TypeTime, value)
		_node.LastUpdated = value
	}
	if value, ok := rvc.mutation.ReporterUsername(); ok {
		_spec.SetField(richvampire.FieldReporterUsername, field.TypeString, value)
		_node.ReporterUsername = value
	}
	if nodes := rvc.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   richvampire.ReporterTable,
			Columns: []string{richvampire.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReporterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RichVampireCreateBulk is the builder for creating many RichVampire entities in bulk.
type RichVampireCreateBulk struct {
	config
	err      error
	builders []*RichVampireCreate
}

// Save creates the RichVampire entities in the database.
func (rvcb *RichVampireCreateBulk) Save(ctx context.Context) ([]*RichVampire, error) {
	if rvcb.err != nil {
		return nil, rvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rvcb.builders))
	nodes := make([]*RichVampire, len(rvcb.builders))
	mutators := make([]Mutator, len(rvcb.builders))
	for i := range rvcb.builders {
		func(i int, root context.Context) {
			builder := rvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RichVampireMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rvcb *RichVampireCreateBulk) SaveX(ctx context.Context) []*RichVampire {
	v, err := rvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rvcb *RichVampireCreateBulk) Exec(ctx context.Context) error {
	_, err := rvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvcb *RichVampireCreateBulk) ExecX(ctx context.Context) {
	if err := rvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
