// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/user"
)

// RichVampireUpdate is the builder for updating RichVampire entities.
type RichVampireUpdate struct {
	config
	hooks    []Hook
	mutation *RichVampireMutation
}

// Where appends a list predicates to the RichVampireUpdate builder.
func (rvu *RichVampireUpdate) Where(ps ...predicate.RichVampire) *RichVampireUpdate {
	rvu.mutation.Where(ps...)
	return rvu
}

// SetVampireName sets the "vampire_name" field.
func (rvu *RichVampireUpdate) SetVampireName(s string) *RichVampireUpdate {
	rvu.mutation.SetVampireName(s)
	return rvu
}

// SetNillableVampireName sets the "vampire_name" field if the given value is not nil.
func (rvu *RichVampireUpdate) SetNillableVampireName(s *string) *RichVampireUpdate {
	if s != nil {
		rvu.SetVampireName(*s)
	}
	return rvu
}

// SetLastUpdated sets the "last_updated" field.
func (rvu *RichVampireUpdate) SetLastUpdated(t time.Time) *RichVampireUpdate {
	rvu.mutation.SetLastUpdated(t)
	return rvu
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (rvu *RichVampireUpdate) SetNillableLastUpdated(t *time.Time) *RichVampireUpdate {
	if t != nil {
		rvu.SetLastUpdated(*t)
	}
	return rvu
}

// SetReporterUsername sets the "reporter_username" field.
func (rvu *RichVampireUpdate) SetReporterUsername(s string) *RichVampireUpdate {
	rvu.mutation.SetReporterUsername(s)
	return rvu
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (rvu *RichVampireUpdate) SetNillableReporterUsername(s *string) *RichVampireUpdate {
	if s != nil {
		rvu.SetReporterUsername(*s)
	}
	return rvu
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (rvu *RichVampireUpdate) ClearReporterUsername() *RichVampireUpdate {
	rvu.mutation.ClearReporterUsername()
	return rvu
}

// SetReporterID sets the "reporter_id" field.
func (rvu *RichVampireUpdate) SetReporterID(i int) *RichVampireUpdate {
	rvu.mutation.SetReporterID(i)
	return rvu
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (rvu *RichVampireUpdate) SetNillableReporterID(i *int) *RichVampireUpdate {
	if i != nil {
		rvu.SetReporterID(*i)
	}
	return rvu
}

// ClearReporterID clears the value of the "reporter_id" field.
func (rvu *RichVampireUpdate) ClearReporterID() *RichVampireUpdate {
	rvu.mutation.ClearReporterID()
	return rvu
}

// SetReporter sets the "reporter" edge to the User entity.
func (rvu *RichVampireUpdate) SetReporter(u *User) *RichVampireUpdate {
	return rvu.SetReporterID(u.ID)
}

// Mutation returns the RichVampireMutation object of the builder.
func (rvu *RichVampireUpdate) Mutation() *RichVampireMutation {
	return rvu.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (rvu *RichVampireUpdate) ClearReporter() *RichVampireUpdate {
	rvu.mutation.ClearReporter()
	return rvu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rvu *RichVampireUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rvu.sqlSave, rvu.mutation, rvu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rvu *RichVampireUpdate) SaveX(ctx context.Context) int {
	affected, err := rvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rvu *RichVampireUpdate) Exec(ctx context.Context) error {
	_, err := rvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvu *RichVampireUpdate) ExecX(ctx context.Context) {
	if err := rvu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rvu *RichVampireUpdate) check() error {
	if v, ok := rvu.mutation.VampireName(); ok {
		if err := richvampire.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "RichVampire.vampire_name": %w`, err)}
		}
	}
	return nil
}

func (rvu *RichVampireUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rvu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(richvampire.Table, richvampire.Columns, sqlgraph.NewFieldSpec(richvampire.FieldID, field.TypeInt))
	if ps := rvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rvu.mutation.VampireName(); ok {
		_spec.SetField(richvampire.FieldVampireName, field.TypeString, value)
	}
	if value, ok := rvu.mutation.LastUpdated(); ok {
		_spec.SetField(richvampire.FieldLastUpdated, field.TypeTime, value)
	}
	if value, ok := rvu.mutation.ReporterUsername(); ok {
		_spec.SetField(richvampire.FieldReporterUsername, field.TypeString, value)
	}
	if rvu.mutation.ReporterUsernameCleared() {
		_spec.ClearField(richvampire.FieldReporterUsername, field.TypeString)
	}
	if rvu.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   richvampire.ReporterTable,
			Columns: []string{richvampire.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rvu.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   richvampire.ReporterTable,
			Columns: []string{richvampire.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{richvampire.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rvu.mutation.done = true
	return n, nil
}

// RichVampireUpdateOne is the builder for updating a single RichVampire entity.
type RichVampireUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RichVampireMutation
}

// SetVampireName sets the "vampire_name" field.
func (rvuo *RichVampireUpdateOne) SetVampireName(s string) *RichVampireUpdateOne {
	rvuo.mutation.SetVampireName(s)
	return rvuo
}

// SetNillableVampireName sets the "vampire_name" field if the given value is not nil.
func (rvuo *RichVampireUpdateOne) SetNillableVampireName(s *string) *RichVampireUpdateOne {
	if s != nil {
		rvuo.SetVampireName(*s)
	}
	return rvuo
}

// SetLastUpdated sets the "last_updated" field.
func (rvuo *RichVampireUpdateOne) SetLastUpdated(t time.Time) *RichVampireUpdateOne {
	rvuo.mutation.SetLastUpdated(t)
	return rvuo
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (rvuo *RichVampireUpdateOne) SetNillableLastUpdated(t *time.Time) *RichVampireUpdateOne {
	if t != nil {
		rvuo.SetLastUpdated(*t)
	}
	return rvuo
}

// SetReporterUsername sets the "reporter_username" field.
func (rvuo *RichVampireUpdateOne) SetReporterUsername(s string) *RichVampireUpdateOne {
	rvuo.mutation.SetReporterUsername(s)
	return rvuo
}

// SetNillableReporterUsername sets the "reporter_username" field if the given value is not nil.
func (rvuo *RichVampireUpdateOne) SetNillableReporterUsername(s *string) *RichVampireUpdateOne {
	if s != nil {
		rvuo.SetReporterUsername(*s)
	}
	return rvuo
}

// ClearReporterUsername clears the value of the "reporter_username" field.
func (rvuo *RichVampireUpdateOne) ClearReporterUsername() *RichVampireUpdateOne {
	rvuo.mutation.ClearReporterUsername()
	return rvuo
}

// SetReporterID sets the "reporter_id" field.
func (rvuo *RichVampireUpdateOne) SetReporterID(i int) *RichVampireUpdateOne {
	rvuo.mutation.SetReporterID(i)
	return rvuo
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (rvuo *RichVampireUpdateOne) SetNillableReporterID(i *int) *RichVampireUpdateOne {
	if i != nil {
		rvuo.SetReporterID(*i)
	}
	return rvuo
}

// ClearReporterID clears the value of the "reporter_id" field.
func (rvuo *RichVampireUpdateOne) ClearReporterID() *RichVampireUpdateOne {
	rvuo.mutation.ClearReporterID()
	return rvuo
}

// SetReporter sets the "reporter" edge to the User entity.
func (rvuo *RichVampireUpdateOne) SetReporter(u *User) *RichVampireUpdateOne {
	return rvuo.SetReporterID(u.ID)
}

// Mutation returns the RichVampireMutation object of the builder.
func (rvuo *RichVampireUpdateOne) Mutation() *RichVampireMutation {
	return rvuo.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (rvuo *RichVampireUpdateOne) ClearReporter() *RichVampireUpdateOne {
	rvuo.mutation.ClearReporter()
	return rvuo
}

// Where appends a list predicates to the RichVampireUpdate builder.
func (rvuo *RichVampireUpdateOne) Where(ps ...predicate.RichVampire) *RichVampireUpdateOne {
	rvuo.mutation.Where(ps...)
	return rvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rvuo *RichVampireUpdateOne) Select(field string, fields ...string) *RichVampireUpdateOne {
	rvuo.fields = append([]string{field}, fields...)
	return rvuo
}

// Save executes the query and returns the updated RichVampire entity.
func (rvuo *RichVampireUpdateOne) Save(ctx context.Context) (*RichVampire, error) {
	return withHooks(ctx, rvuo.sqlSave, rvuo.mutation, rvuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rvuo *RichVampireUpdateOne) SaveX(ctx context.Context) *RichVampire {
	node, err := rvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rvuo *RichVampireUpdateOne) Exec(ctx context.Context) error {
	_, err := rvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rvuo *RichVampireUpdateOne) ExecX(ctx context.Context) {
	if err := rvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rvuo *RichVampireUpdateOne) check() error {
	if v, ok := rvuo.mutation.VampireName(); ok {
		if err := richvampire.VampireNameValidator(v); err != nil {
			return &ValidationError{Name: "vampire_name", err: fmt.Errorf(`ent: validator failed for field "RichVampire.vampire_name": %w`, err)}
		}
	}
	return nil
}

func (rvuo *RichVampireUpdateOne) sqlSave(ctx context.Context) (_node *RichVampire, err error) {
	if err := rvuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(richvampire.Table, richvampire.Columns, sqlgraph.NewFieldSpec(richvampire.FieldID, field.TypeInt))
	id, ok := rvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RichVampire.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, richvampire.FieldID)
		for _, f := range fields {
			if !richvampire.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != richvampire.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rvuo.mutation.VampireName(); ok {
		_spec.SetField(richvampire.FieldVampireName, field.TypeString, value)
	}
	if value, ok := rvuo.mutation.LastUpdated(); ok {
		_spec.SetField(richvampire.FieldLastUpdated, field.TypeTime, value)
	}
	if value, ok := rvuo.mutation.ReporterUsername(); ok {
		_spec.SetField(richvampire.FieldReporterUsername, field.TypeString, value)
	}
	if rvuo.mutation.ReporterUsernameCleared() {
		_spec.ClearField(richvampire.FieldReporterUsername, field.TypeString)
	}
	if rvuo.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   richvampire.ReporterTable,
			Columns: []string{richvampire.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rvuo.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   richvampire.ReporterTable,
			Columns: []string{richvampire.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RichVampire{config: rvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{richvampire.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rvuo.mutation.done = true
	return _node, nil
}
