// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/mikestefanello/pagoda/ent/blooddeity"
	"github.com/mikestefanello/pagoda/ent/locationreport"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/richvampire"
	"github.com/mikestefanello/pagoda/ent/schema"
	"github.com/mikestefanello/pagoda/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blooddeityFields := schema.BloodDeity{}.Fields()
	_ = blooddeityFields
	// blooddeityDescVampireName is the schema descriptor for vampire_name field.
	blooddeityDescVampireName := blooddeityFields[0].Descriptor()
	// blooddeity.VampireNameValidator is a validator for the "vampire_name" field. It is called by the builders before save.
	blooddeity.VampireNameValidator = blooddeityDescVampireName.Validators[0].(func(string) error)
	// blooddeityDescBloodAmount is the schema descriptor for blood_amount field.
	blooddeityDescBloodAmount := blooddeityFields[1].Descriptor()
	// blooddeity.DefaultBloodAmount holds the default value on creation for the blood_amount field.
	blooddeity.DefaultBloodAmount = blooddeityDescBloodAmount.Default.(int64)
	// blooddeity.BloodAmountValidator is a validator for the "blood_amount" field. It is called by the builders before save.
	blooddeity.BloodAmountValidator = blooddeityDescBloodAmount.Validators[0].(func(int64) error)
	// blooddeityDescLastUpdated is the schema descriptor for last_updated field.
	blooddeityDescLastUpdated := blooddeityFields[2].Descriptor()
	// blooddeity.DefaultLastUpdated holds the default value on creation for the last_updated field.
	blooddeity.DefaultLastUpdated = blooddeityDescLastUpdated.Default.(func() time.Time)
	locationreportFields := schema.LocationReport{}.Fields()
	_ = locationreportFields
	// locationreportDescBuildingName is the schema descriptor for building_name field.
	locationreportDescBuildingName := locationreportFields[0].Descriptor()
	// locationreport.BuildingNameValidator is a validator for the "building_name" field. It is called by the builders before save.
	locationreport.BuildingNameValidator = locationreportDescBuildingName.Validators[0].(func(string) error)
	// locationreportDescCoordinateX is the schema descriptor for coordinate_x field.
	locationreportDescCoordinateX := locationreportFields[3].Descriptor()
	// locationreport.CoordinateXValidator is a validator for the "coordinate_x" field. It is called by the builders before save.
	locationreport.CoordinateXValidator = func() func(int) error {
		validators := locationreportDescCoordinateX.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(coordinate_x int) error {
			for _, fn := range fns {
				if err := fn(coordinate_x); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// locationreportDescCoordinateY is the schema descriptor for coordinate_y field.
	locationreportDescCoordinateY := locationreportFields[4].Descriptor()
	// locationreport.CoordinateYValidator is a validator for the "coordinate_y" field. It is called by the builders before save.
	locationreport.CoordinateYValidator = func() func(int) error {
		validators := locationreportDescCoordinateY.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(coordinate_y int) error {
			for _, fn := range fns {
				if err := fn(coordinate_y); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// locationreportDescGuildLevel is the schema descriptor for guild_level field.
	locationreportDescGuildLevel := locationreportFields[7].Descriptor()
	// locationreport.GuildLevelValidator is a validator for the "guild_level" field. It is called by the builders before save.
	locationreport.GuildLevelValidator = func() func(int) error {
		validators := locationreportDescGuildLevel.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(guild_level int) error {
			for _, fn := range fns {
				if err := fn(guild_level); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// locationreportDescReportedAt is the schema descriptor for reported_at field.
	locationreportDescReportedAt := locationreportFields[12].Descriptor()
	// locationreport.DefaultReportedAt holds the default value on creation for the reported_at field.
	locationreport.DefaultReportedAt = locationreportDescReportedAt.Default.(func() time.Time)
	// locationreportDescIsActive is the schema descriptor for is_active field.
	locationreportDescIsActive := locationreportFields[14].Descriptor()
	// locationreport.DefaultIsActive holds the default value on creation for the is_active field.
	locationreport.DefaultIsActive = locationreportDescIsActive.Default.(bool)
	passwordtokenHooks := schema.PasswordToken{}.Hooks()
	passwordtoken.Hooks[0] = passwordtokenHooks[0]
	passwordtokenFields := schema.PasswordToken{}.Fields()
	_ = passwordtokenFields
	// passwordtokenDescToken is the schema descriptor for token field.
	passwordtokenDescToken := passwordtokenFields[0].Descriptor()
	// passwordtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	passwordtoken.TokenValidator = passwordtokenDescToken.Validators[0].(func(string) error)
	// passwordtokenDescCreatedAt is the schema descriptor for created_at field.
	passwordtokenDescCreatedAt := passwordtokenFields[2].Descriptor()
	// passwordtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordtoken.DefaultCreatedAt = passwordtokenDescCreatedAt.Default.(func() time.Time)
	richvampireFields := schema.RichVampire{}.Fields()
	_ = richvampireFields
	// richvampireDescVampireName is the schema descriptor for vampire_name field.
	richvampireDescVampireName := richvampireFields[0].Descriptor()
	// richvampire.VampireNameValidator is a validator for the "vampire_name" field. It is called by the builders before save.
	richvampire.VampireNameValidator = richvampireDescVampireName.Validators[0].(func(string) error)
	// richvampireDescLastUpdated is the schema descriptor for last_updated field.
	richvampireDescLastUpdated := richvampireFields[1].Descriptor()
	// richvampire.DefaultLastUpdated holds the default value on creation for the last_updated field.
	richvampire.DefaultLastUpdated = richvampireDescLastUpdated.Default.(func() time.Time)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[4].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescTotalReports is the schema descriptor for total_reports field.
	userDescTotalReports := userFields[6].Descriptor()
	// user.DefaultTotalReports holds the default value on creation for the total_reports field.
	user.DefaultTotalReports = userDescTotalReports.Default.(int)
}

const (
	Version = "v0.14.4"                                         // Version of ent codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent codegen.
)
