// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BloodDeitiesColumns holds the columns for the "blood_deities" table.
	BloodDeitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "vampire_name", Type: field.TypeString, Unique: true},
		{Name: "blood_amount", Type: field.TypeInt64, Default: 0},
		{Name: "last_updated", Type: field.TypeTime},
		{Name: "reporter_username", Type: field.TypeString, Nullable: true},
		{Name: "reporter_id", Type: field.TypeInt, Nullable: true},
	}
	// BloodDeitiesTable holds the schema information for the "blood_deities" table.
	BloodDeitiesTable = &schema.Table{
		Name:       "blood_deities",
		Columns:    BloodDeitiesColumns,
		PrimaryKey: []*schema.Column{BloodDeitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blood_deities_users_reporter",
				Columns:    []*schema.Column{BloodDeitiesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "blooddeity_blood_amount",
				Unique:  false,
				Columns: []*schema.Column{BloodDeitiesColumns[2]},
			},
			{
				Name:    "blooddeity_reporter_id",
				Unique:  false,
				Columns: []*schema.Column{BloodDeitiesColumns[5]},
			},
			{
				Name:    "blooddeity_vampire_name",
				Unique:  false,
				Columns: []*schema.Column{BloodDeitiesColumns[1]},
			},
		},
	}
	// LocationReportsColumns holds the columns for the "location_reports" table.
	LocationReportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "building_name", Type: field.TypeString},
		{Name: "building_type", Type: field.TypeEnum, Enums: []string{"shop", "guild", "hunter", "paladin", "werewolf", "item", "blood_deity", "rich_vampire"}},
		{Name: "custom_item_name", Type: field.TypeString, Nullable: true},
		{Name: "coordinate_x", Type: field.TypeInt, Nullable: true},
		{Name: "coordinate_y", Type: field.TypeInt, Nullable: true},
		{Name: "street_name", Type: field.TypeString, Nullable: true},
		{Name: "street_number", Type: field.TypeString, Nullable: true},
		{Name: "guild_level", Type: field.TypeInt, Nullable: true},
		{Name: "reporter_username", Type: field.TypeString, Nullable: true},
		{Name: "confidence", Type: field.TypeEnum, Enums: []string{"confirmed", "unverified"}, Default: "unverified"},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "reported_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "reporter_id", Type: field.TypeInt, Nullable: true},
	}
	// LocationReportsTable holds the schema information for the "location_reports" table.
	LocationReportsTable = &schema.Table{
		Name:       "location_reports",
		Columns:    LocationReportsColumns,
		PrimaryKey: []*schema.Column{LocationReportsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "location_reports_users_reporter",
				Columns:    []*schema.Column{LocationReportsColumns[15]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "locationreport_building_type",
				Unique:  false,
				Columns: []*schema.Column{LocationReportsColumns[2]},
			},
			{
				Name:    "locationreport_coordinate_x_coordinate_y",
				Unique:  false,
				Columns: []*schema.Column{LocationReportsColumns[4], LocationReportsColumns[5]},
			},
			{
				Name:    "locationreport_is_active_expires_at",
				Unique:  false,
				Columns: []*schema.Column{LocationReportsColumns[14], LocationReportsColumns[13]},
			},
			{
				Name:    "locationreport_reporter_id",
				Unique:  false,
				Columns: []*schema.Column{LocationReportsColumns[15]},
			},
			{
				Name:    "locationreport_reported_at",
				Unique:  false,
				Columns: []*schema.Column{LocationReportsColumns[12]},
			},
		},
	}
	// PasswordTokensColumns holds the columns for the "password_tokens" table.
	PasswordTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// PasswordTokensTable holds the schema information for the "password_tokens" table.
	PasswordTokensTable = &schema.Table{
		Name:       "password_tokens",
		Columns:    PasswordTokensColumns,
		PrimaryKey: []*schema.Column{PasswordTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_tokens_users_user",
				Columns:    []*schema.Column{PasswordTokensColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RichVampiresColumns holds the columns for the "rich_vampires" table.
	RichVampiresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "vampire_name", Type: field.TypeString, Unique: true},
		{Name: "last_updated", Type: field.TypeTime},
		{Name: "reporter_username", Type: field.TypeString, Nullable: true},
		{Name: "reporter_id", Type: field.TypeInt, Nullable: true},
	}
	// RichVampiresTable holds the schema information for the "rich_vampires" table.
	RichVampiresTable = &schema.Table{
		Name:       "rich_vampires",
		Columns:    RichVampiresColumns,
		PrimaryKey: []*schema.Column{RichVampiresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rich_vampires_users_reporter",
				Columns:    []*schema.Column{RichVampiresColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "richvampire_vampire_name",
				Unique:  false,
				Columns: []*schema.Column{RichVampiresColumns[1]},
			},
			{
				Name:    "richvampire_reporter_id",
				Unique:  false,
				Columns: []*schema.Column{RichVampiresColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "total_reports", Type: field.TypeInt, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BloodDeitiesTable,
		LocationReportsTable,
		PasswordTokensTable,
		RichVampiresTable,
		UsersTable,
	}
)

func init() {
	BloodDeitiesTable.ForeignKeys[0].RefTable = UsersTable
	LocationReportsTable.ForeignKeys[0].RefTable = UsersTable
	PasswordTokensTable.ForeignKeys[0].RefTable = UsersTable
	RichVampiresTable.ForeignKeys[0].RefTable = UsersTable
}
