// Code generated by ent, DO NOT EDIT.

package locationreport

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the locationreport type in the database.
	Label = "location_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBuildingName holds the string denoting the building_name field in the database.
	FieldBuildingName = "building_name"
	// FieldBuildingType holds the string denoting the building_type field in the database.
	FieldBuildingType = "building_type"
	// FieldCustomItemName holds the string denoting the custom_item_name field in the database.
	FieldCustomItemName = "custom_item_name"
	// FieldCoordinateX holds the string denoting the coordinate_x field in the database.
	FieldCoordinateX = "coordinate_x"
	// FieldCoordinateY holds the string denoting the coordinate_y field in the database.
	FieldCoordinateY = "coordinate_y"
	// FieldStreetName holds the string denoting the street_name field in the database.
	FieldStreetName = "street_name"
	// FieldStreetNumber holds the string denoting the street_number field in the database.
	FieldStreetNumber = "street_number"
	// FieldGuildLevel holds the string denoting the guild_level field in the database.
	FieldGuildLevel = "guild_level"
	// FieldReporterUsername holds the string denoting the reporter_username field in the database.
	FieldReporterUsername = "reporter_username"
	// FieldReporterID holds the string denoting the reporter_id field in the database.
	FieldReporterID = "reporter_id"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldReportedAt holds the string denoting the reported_at field in the database.
	FieldReportedAt = "reported_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeReporter holds the string denoting the reporter edge name in mutations.
	EdgeReporter = "reporter"
	// Table holds the table name of the locationreport in the database.
	Table = "location_reports"
	// ReporterTable is the table that holds the reporter relation/edge.
	ReporterTable = "location_reports"
	// ReporterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReporterInverseTable = "users"
	// ReporterColumn is the table column denoting the reporter relation/edge.
	ReporterColumn = "reporter_id"
)

// Columns holds all SQL columns for locationreport fields.
var Columns = []string{
	FieldID,
	FieldBuildingName,
	FieldBuildingType,
	FieldCustomItemName,
	FieldCoordinateX,
	FieldCoordinateY,
	FieldStreetName,
	FieldStreetNumber,
	FieldGuildLevel,
	FieldReporterUsername,
	FieldReporterID,
	FieldConfidence,
	FieldNotes,
	FieldReportedAt,
	FieldExpiresAt,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BuildingNameValidator is a validator for the "building_name" field. It is called by the builders before save.
	BuildingNameValidator func(string) error
	// CoordinateXValidator is a validator for the "coordinate_x" field. It is called by the builders before save.
	CoordinateXValidator func(int) error
	// CoordinateYValidator is a validator for the "coordinate_y" field. It is called by the builders before save.
	CoordinateYValidator func(int) error
	// GuildLevelValidator is a validator for the "guild_level" field. It is called by the builders before save.
	GuildLevelValidator func(int) error
	// DefaultReportedAt holds the default value on creation for the "reported_at" field.
	DefaultReportedAt func() time.Time
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
)

// BuildingType defines the type for the "building_type" enum field.
type BuildingType string

// BuildingType values.
const (
	BuildingTypeShop        BuildingType = "shop"
	BuildingTypeGuild       BuildingType = "guild"
	BuildingTypeHunter      BuildingType = "hunter"
	BuildingTypePaladin     BuildingType = "paladin"
	BuildingTypeWerewolf    BuildingType = "werewolf"
	BuildingTypeItem        BuildingType = "item"
	BuildingTypeBloodDeity  BuildingType = "blood_deity"
	BuildingTypeRichVampire BuildingType = "rich_vampire"
)

func (bt BuildingType) String() string {
	return string(bt)
}

// BuildingTypeValidator is a validator for the "building_type" field enum values. It is called by the builders before save.
func BuildingTypeValidator(bt BuildingType) error {
	switch bt {
	case BuildingTypeShop, BuildingTypeGuild, BuildingTypeHunter, BuildingTypePaladin, BuildingTypeWerewolf, BuildingTypeItem, BuildingTypeBloodDeity, BuildingTypeRichVampire:
		return nil
	default:
		return fmt.Errorf("locationreport: invalid enum value for building_type field: %q", bt)
	}
}

// Confidence defines the type for the "confidence" enum field.
type Confidence string

// ConfidenceUnverified is the default value of the Confidence enum.
const DefaultConfidence = ConfidenceUnverified

// Confidence values.
const (
	ConfidenceConfirmed  Confidence = "confirmed"
	ConfidenceUnverified Confidence = "unverified"
)

func (c Confidence) String() string {
	return string(c)
}

// ConfidenceValidator is a validator for the "confidence" field enum values. It is called by the builders before save.
func ConfidenceValidator(c Confidence) error {
	switch c {
	case ConfidenceConfirmed, ConfidenceUnverified:
		return nil
	default:
		return fmt.Errorf("locationreport: invalid enum value for confidence field: %q", c)
	}
}

// OrderOption defines the ordering options for the LocationReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBuildingName orders the results by the building_name field.
func ByBuildingName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuildingName, opts...).ToFunc()
}

// ByBuildingType orders the results by the building_type field.
func ByBuildingType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuildingType, opts...).ToFunc()
}

// ByCustomItemName orders the results by the custom_item_name field.
func ByCustomItemName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomItemName, opts...).ToFunc()
}

// ByCoordinateX orders the results by the coordinate_x field.
func ByCoordinateX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoordinateX, opts...).ToFunc()
}

// ByCoordinateY orders the results by the coordinate_y field.
func ByCoordinateY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoordinateY, opts...).ToFunc()
}

// ByStreetName orders the results by the street_name field.
func ByStreetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreetName, opts...).ToFunc()
}

// ByStreetNumber orders the results by the street_number field.
func ByStreetNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreetNumber, opts...).ToFunc()
}

// ByGuildLevel orders the results by the guild_level field.
func ByGuildLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildLevel, opts...).ToFunc()
}

// ByReporterUsername orders the results by the reporter_username field.
func ByReporterUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterUsername, opts...).ToFunc()
}

// ByReporterID orders the results by the reporter_id field.
func ByReporterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterID, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByReportedAt orders the results by the reported_at field.
func ByReportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByReporterField orders the results by reporter field.
func ByReporterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReporterStep(), sql.OrderByField(field, opts...))
	}
}
func newReporterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReporterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ReporterTable, ReporterColumn),
	)
}
