// Code generated by ent, DO NOT EDIT.

package locationreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldID, id))
}

// BuildingName applies equality check predicate on the "building_name" field. It's identical to BuildingNameEQ.
func BuildingName(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldBuildingName, v))
}

// CustomItemName applies equality check predicate on the "custom_item_name" field. It's identical to CustomItemNameEQ.
func CustomItemName(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCustomItemName, v))
}

// CoordinateX applies equality check predicate on the "coordinate_x" field. It's identical to CoordinateXEQ.
func CoordinateX(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCoordinateX, v))
}

// CoordinateY applies equality check predicate on the "coordinate_y" field. It's identical to CoordinateYEQ.
func CoordinateY(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCoordinateY, v))
}

// StreetName applies equality check predicate on the "street_name" field. It's identical to StreetNameEQ.
func StreetName(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldStreetName, v))
}

// StreetNumber applies equality check predicate on the "street_number" field. It's identical to StreetNumberEQ.
func StreetNumber(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldStreetNumber, v))
}

// GuildLevel applies equality check predicate on the "guild_level" field. It's identical to GuildLevelEQ.
func GuildLevel(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldGuildLevel, v))
}

// ReporterUsername applies equality check predicate on the "reporter_username" field. It's identical to ReporterUsernameEQ.
func ReporterUsername(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReporterUsername, v))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReporterID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldNotes, v))
}

// ReportedAt applies equality check predicate on the "reported_at" field. It's identical to ReportedAtEQ.
func ReportedAt(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReportedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldExpiresAt, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldIsActive, v))
}

// BuildingNameEQ applies the EQ predicate on the "building_name" field.
func BuildingNameEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldBuildingName, v))
}

// BuildingNameNEQ applies the NEQ predicate on the "building_name" field.
func BuildingNameNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldBuildingName, v))
}

// BuildingNameIn applies the In predicate on the "building_name" field.
func BuildingNameIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldBuildingName, vs...))
}

// BuildingNameNotIn applies the NotIn predicate on the "building_name" field.
func BuildingNameNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldBuildingName, vs...))
}

// BuildingNameGT applies the GT predicate on the "building_name" field.
func BuildingNameGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldBuildingName, v))
}

// BuildingNameGTE applies the GTE predicate on the "building_name" field.
func BuildingNameGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldBuildingName, v))
}

// BuildingNameLT applies the LT predicate on the "building_name" field.
func BuildingNameLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldBuildingName, v))
}

// BuildingNameLTE applies the LTE predicate on the "building_name" field.
func BuildingNameLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldBuildingName, v))
}

// BuildingNameContains applies the Contains predicate on the "building_name" field.
func BuildingNameContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldBuildingName, v))
}

// BuildingNameHasPrefix applies the HasPrefix predicate on the "building_name" field.
func BuildingNameHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldBuildingName, v))
}

// BuildingNameHasSuffix applies the HasSuffix predicate on the "building_name" field.
func BuildingNameHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldBuildingName, v))
}

// BuildingNameEqualFold applies the EqualFold predicate on the "building_name" field.
func BuildingNameEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldBuildingName, v))
}

// BuildingNameContainsFold applies the ContainsFold predicate on the "building_name" field.
func BuildingNameContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldBuildingName, v))
}

// BuildingTypeEQ applies the EQ predicate on the "building_type" field.
func BuildingTypeEQ(v BuildingType) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldBuildingType, v))
}

// BuildingTypeNEQ applies the NEQ predicate on the "building_type" field.
func BuildingTypeNEQ(v BuildingType) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldBuildingType, v))
}

// BuildingTypeIn applies the In predicate on the "building_type" field.
func BuildingTypeIn(vs ...BuildingType) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldBuildingType, vs...))
}

// BuildingTypeNotIn applies the NotIn predicate on the "building_type" field.
func BuildingTypeNotIn(vs ...BuildingType) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldBuildingType, vs...))
}

// CustomItemNameEQ applies the EQ predicate on the "custom_item_name" field.
func CustomItemNameEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCustomItemName, v))
}

// CustomItemNameNEQ applies the NEQ predicate on the "custom_item_name" field.
func CustomItemNameNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldCustomItemName, v))
}

// CustomItemNameIn applies the In predicate on the "custom_item_name" field.
func CustomItemNameIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldCustomItemName, vs...))
}

// CustomItemNameNotIn applies the NotIn predicate on the "custom_item_name" field.
func CustomItemNameNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldCustomItemName, vs...))
}

// CustomItemNameGT applies the GT predicate on the "custom_item_name" field.
func CustomItemNameGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldCustomItemName, v))
}

// CustomItemNameGTE applies the GTE predicate on the "custom_item_name" field.
func CustomItemNameGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldCustomItemName, v))
}

// CustomItemNameLT applies the LT predicate on the "custom_item_name" field.
func CustomItemNameLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldCustomItemName, v))
}

// CustomItemNameLTE applies the LTE predicate on the "custom_item_name" field.
func CustomItemNameLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldCustomItemName, v))
}

// CustomItemNameContains applies the Contains predicate on the "custom_item_name" field.
func CustomItemNameContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldCustomItemName, v))
}

// CustomItemNameHasPrefix applies the HasPrefix predicate on the "custom_item_name" field.
func CustomItemNameHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldCustomItemName, v))
}

// CustomItemNameHasSuffix applies the HasSuffix predicate on the "custom_item_name" field.
func CustomItemNameHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldCustomItemName, v))
}

// CustomItemNameIsNil applies the IsNil predicate on the "custom_item_name" field.
func CustomItemNameIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldCustomItemName))
}

// CustomItemNameNotNil applies the NotNil predicate on the "custom_item_name" field.
func CustomItemNameNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldCustomItemName))
}

// CustomItemNameEqualFold applies the EqualFold predicate on the "custom_item_name" field.
func CustomItemNameEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldCustomItemName, v))
}

// CustomItemNameContainsFold applies the ContainsFold predicate on the "custom_item_name" field.
func CustomItemNameContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldCustomItemName, v))
}

// CoordinateXEQ applies the EQ predicate on the "coordinate_x" field.
func CoordinateXEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCoordinateX, v))
}

// CoordinateXNEQ applies the NEQ predicate on the "coordinate_x" field.
func CoordinateXNEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldCoordinateX, v))
}

// CoordinateXIn applies the In predicate on the "coordinate_x" field.
func CoordinateXIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldCoordinateX, vs...))
}

// CoordinateXNotIn applies the NotIn predicate on the "coordinate_x" field.
func CoordinateXNotIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldCoordinateX, vs...))
}

// CoordinateXGT applies the GT predicate on the "coordinate_x" field.
func CoordinateXGT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldCoordinateX, v))
}

// CoordinateXGTE applies the GTE predicate on the "coordinate_x" field.
func CoordinateXGTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldCoordinateX, v))
}

// CoordinateXLT applies the LT predicate on the "coordinate_x" field.
func CoordinateXLT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldCoordinateX, v))
}

// CoordinateXLTE applies the LTE predicate on the "coordinate_x" field.
func CoordinateXLTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldCoordinateX, v))
}

// CoordinateXIsNil applies the IsNil predicate on the "coordinate_x" field.
func CoordinateXIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldCoordinateX))
}

// CoordinateXNotNil applies the NotNil predicate on the "coordinate_x" field.
func CoordinateXNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldCoordinateX))
}

// CoordinateYEQ applies the EQ predicate on the "coordinate_y" field.
func CoordinateYEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldCoordinateY, v))
}

// CoordinateYNEQ applies the NEQ predicate on the "coordinate_y" field.
func CoordinateYNEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldCoordinateY, v))
}

// CoordinateYIn applies the In predicate on the "coordinate_y" field.
func CoordinateYIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldCoordinateY, vs...))
}

// CoordinateYNotIn applies the NotIn predicate on the "coordinate_y" field.
func CoordinateYNotIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldCoordinateY, vs...))
}

// CoordinateYGT applies the GT predicate on the "coordinate_y" field.
func CoordinateYGT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldCoordinateY, v))
}

// CoordinateYGTE applies the GTE predicate on the "coordinate_y" field.
func CoordinateYGTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldCoordinateY, v))
}

// CoordinateYLT applies the LT predicate on the "coordinate_y" field.
func CoordinateYLT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldCoordinateY, v))
}

// CoordinateYLTE applies the LTE predicate on the "coordinate_y" field.
func CoordinateYLTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldCoordinateY, v))
}

// CoordinateYIsNil applies the IsNil predicate on the "coordinate_y" field.
func CoordinateYIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldCoordinateY))
}

// CoordinateYNotNil applies the NotNil predicate on the "coordinate_y" field.
func CoordinateYNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldCoordinateY))
}

// StreetNameEQ applies the EQ predicate on the "street_name" field.
func StreetNameEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldStreetName, v))
}

// StreetNameNEQ applies the NEQ predicate on the "street_name" field.
func StreetNameNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldStreetName, v))
}

// StreetNameIn applies the In predicate on the "street_name" field.
func StreetNameIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldStreetName, vs...))
}

// StreetNameNotIn applies the NotIn predicate on the "street_name" field.
func StreetNameNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldStreetName, vs...))
}

// StreetNameGT applies the GT predicate on the "street_name" field.
func StreetNameGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldStreetName, v))
}

// StreetNameGTE applies the GTE predicate on the "street_name" field.
func StreetNameGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldStreetName, v))
}

// StreetNameLT applies the LT predicate on the "street_name" field.
func StreetNameLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldStreetName, v))
}

// StreetNameLTE applies the LTE predicate on the "street_name" field.
func StreetNameLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldStreetName, v))
}

// StreetNameContains applies the Contains predicate on the "street_name" field.
func StreetNameContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldStreetName, v))
}

// StreetNameHasPrefix applies the HasPrefix predicate on the "street_name" field.
func StreetNameHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldStreetName, v))
}

// StreetNameHasSuffix applies the HasSuffix predicate on the "street_name" field.
func StreetNameHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldStreetName, v))
}

// StreetNameIsNil applies the IsNil predicate on the "street_name" field.
func StreetNameIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldStreetName))
}

// StreetNameNotNil applies the NotNil predicate on the "street_name" field.
func StreetNameNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldStreetName))
}

// StreetNameEqualFold applies the EqualFold predicate on the "street_name" field.
func StreetNameEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldStreetName, v))
}

// StreetNameContainsFold applies the ContainsFold predicate on the "street_name" field.
func StreetNameContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldStreetName, v))
}

// StreetNumberEQ applies the EQ predicate on the "street_number" field.
func StreetNumberEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldStreetNumber, v))
}

// StreetNumberNEQ applies the NEQ predicate on the "street_number" field.
func StreetNumberNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldStreetNumber, v))
}

// StreetNumberIn applies the In predicate on the "street_number" field.
func StreetNumberIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldStreetNumber, vs...))
}

// StreetNumberNotIn applies the NotIn predicate on the "street_number" field.
func StreetNumberNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldStreetNumber, vs...))
}

// StreetNumberGT applies the GT predicate on the "street_number" field.
func StreetNumberGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldStreetNumber, v))
}

// StreetNumberGTE applies the GTE predicate on the "street_number" field.
func StreetNumberGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldStreetNumber, v))
}

// StreetNumberLT applies the LT predicate on the "street_number" field.
func StreetNumberLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldStreetNumber, v))
}

// StreetNumberLTE applies the LTE predicate on the "street_number" field.
func StreetNumberLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldStreetNumber, v))
}

// StreetNumberContains applies the Contains predicate on the "street_number" field.
func StreetNumberContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldStreetNumber, v))
}

// StreetNumberHasPrefix applies the HasPrefix predicate on the "street_number" field.
func StreetNumberHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldStreetNumber, v))
}

// StreetNumberHasSuffix applies the HasSuffix predicate on the "street_number" field.
func StreetNumberHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldStreetNumber, v))
}

// StreetNumberIsNil applies the IsNil predicate on the "street_number" field.
func StreetNumberIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldStreetNumber))
}

// StreetNumberNotNil applies the NotNil predicate on the "street_number" field.
func StreetNumberNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldStreetNumber))
}

// StreetNumberEqualFold applies the EqualFold predicate on the "street_number" field.
func StreetNumberEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldStreetNumber, v))
}

// StreetNumberContainsFold applies the ContainsFold predicate on the "street_number" field.
func StreetNumberContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldStreetNumber, v))
}

// GuildLevelEQ applies the EQ predicate on the "guild_level" field.
func GuildLevelEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldGuildLevel, v))
}

// GuildLevelNEQ applies the NEQ predicate on the "guild_level" field.
func GuildLevelNEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldGuildLevel, v))
}

// GuildLevelIn applies the In predicate on the "guild_level" field.
func GuildLevelIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldGuildLevel, vs...))
}

// GuildLevelNotIn applies the NotIn predicate on the "guild_level" field.
func GuildLevelNotIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldGuildLevel, vs...))
}

// GuildLevelGT applies the GT predicate on the "guild_level" field.
func GuildLevelGT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldGuildLevel, v))
}

// GuildLevelGTE applies the GTE predicate on the "guild_level" field.
func GuildLevelGTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldGuildLevel, v))
}

// GuildLevelLT applies the LT predicate on the "guild_level" field.
func GuildLevelLT(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldGuildLevel, v))
}

// GuildLevelLTE applies the LTE predicate on the "guild_level" field.
func GuildLevelLTE(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldGuildLevel, v))
}

// GuildLevelIsNil applies the IsNil predicate on the "guild_level" field.
func GuildLevelIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldGuildLevel))
}

// GuildLevelNotNil applies the NotNil predicate on the "guild_level" field.
func GuildLevelNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldGuildLevel))
}

// ReporterUsernameEQ applies the EQ predicate on the "reporter_username" field.
func ReporterUsernameEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReporterUsername, v))
}

// ReporterUsernameNEQ applies the NEQ predicate on the "reporter_username" field.
func ReporterUsernameNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldReporterUsername, v))
}

// ReporterUsernameIn applies the In predicate on the "reporter_username" field.
func ReporterUsernameIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldReporterUsername, vs...))
}

// ReporterUsernameNotIn applies the NotIn predicate on the "reporter_username" field.
func ReporterUsernameNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldReporterUsername, vs...))
}

// ReporterUsernameGT applies the GT predicate on the "reporter_username" field.
func ReporterUsernameGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldReporterUsername, v))
}

// ReporterUsernameGTE applies the GTE predicate on the "reporter_username" field.
func ReporterUsernameGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldReporterUsername, v))
}

// ReporterUsernameLT applies the LT predicate on the "reporter_username" field.
func ReporterUsernameLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldReporterUsername, v))
}

// ReporterUsernameLTE applies the LTE predicate on the "reporter_username" field.
func ReporterUsernameLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldReporterUsername, v))
}

// ReporterUsernameContains applies the Contains predicate on the "reporter_username" field.
func ReporterUsernameContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldReporterUsername, v))
}

// ReporterUsernameHasPrefix applies the HasPrefix predicate on the "reporter_username" field.
func ReporterUsernameHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldReporterUsername, v))
}

// ReporterUsernameHasSuffix applies the HasSuffix predicate on the "reporter_username" field.
func ReporterUsernameHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldReporterUsername, v))
}

// ReporterUsernameIsNil applies the IsNil predicate on the "reporter_username" field.
func ReporterUsernameIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldReporterUsername))
}

// ReporterUsernameNotNil applies the NotNil predicate on the "reporter_username" field.
func ReporterUsernameNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldReporterUsername))
}

// ReporterUsernameEqualFold applies the EqualFold predicate on the "reporter_username" field.
func ReporterUsernameEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldReporterUsername, v))
}

// ReporterUsernameContainsFold applies the ContainsFold predicate on the "reporter_username" field.
func ReporterUsernameContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldReporterUsername, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...int) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDIsNil applies the IsNil predicate on the "reporter_id" field.
func ReporterIDIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldReporterID))
}

// ReporterIDNotNil applies the NotNil predicate on the "reporter_id" field.
func ReporterIDNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldReporterID))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v Confidence) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v Confidence) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...Confidence) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...Confidence) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldConfidence, vs...))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldContainsFold(FieldNotes, v))
}

// ReportedAtEQ applies the EQ predicate on the "reported_at" field.
func ReportedAtEQ(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldReportedAt, v))
}

// ReportedAtNEQ applies the NEQ predicate on the "reported_at" field.
func ReportedAtNEQ(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldReportedAt, v))
}

// ReportedAtIn applies the In predicate on the "reported_at" field.
func ReportedAtIn(vs ...time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldReportedAt, vs...))
}

// ReportedAtNotIn applies the NotIn predicate on the "reported_at" field.
func ReportedAtNotIn(vs ...time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldReportedAt, vs...))
}

// ReportedAtGT applies the GT predicate on the "reported_at" field.
func ReportedAtGT(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldReportedAt, v))
}

// ReportedAtGTE applies the GTE predicate on the "reported_at" field.
func ReportedAtGTE(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldReportedAt, v))
}

// ReportedAtLT applies the LT predicate on the "reported_at" field.
func ReportedAtLT(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldReportedAt, v))
}

// ReportedAtLTE applies the LTE predicate on the "reported_at" field.
func ReportedAtLTE(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldReportedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNotNull(FieldExpiresAt))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.LocationReport {
	return predicate.LocationReport(sql.FieldNEQ(FieldIsActive, v))
}

// HasReporter applies the HasEdge predicate on the "reporter" edge.
func HasReporter() predicate.LocationReport {
	return predicate.LocationReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ReporterTable, ReporterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReporterWith applies the HasEdge predicate on the "reporter" edge with a given conditions (other predicates).
func HasReporterWith(preds ...predicate.User) predicate.LocationReport {
	return predicate.LocationReport(func(s *sql.Selector) {
		step := newReporterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LocationReport) predicate.LocationReport {
	return predicate.LocationReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LocationReport) predicate.LocationReport {
	return predicate.LocationReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LocationReport) predicate.LocationReport {
	return predicate.LocationReport(sql.NotPredicates(p))
}
