// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BloodDeity is the predicate function for blooddeity builders.
type BloodDeity func(*sql.Selector)

// LocationReport is the predicate function for locationreport builders.
type LocationReport func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// RichVampire is the predicate function for richvampire builders.
type RichVampire func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
